# auto-generated by debugs/build_glyph_reference.py — do not edit
"""Left-to-right index -> glyph-character lookup for the
glyph_daily_*.png reference atlases in this directory. No per-glyph
coordinates are stored -- re-isolate glyphs from the PNG yourself via
a plain threshold + cv2.findContours pass, sort by x, then look up
each contour's position here. Regenerate via:
    python debugs/build_glyph_reference.py
"""
DATA = {
  "glyph_daily_score.png": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9"
  },
  "glyph_daily_header.png": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "K",
    "11": "M"
  },
  "glyph_daily_pct.png": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "."
  },
  "glyph_daily_val.png": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "K"
  }
}
