# -*- coding: utf-8 -*-
"""
meaningful_images.py -- auto-generated by debugs/curate_meaningful_images.py

Curated subset of single/*.png, copied into this directory, chosen to cover:
  1. every doll frame that appears anywhere in single/*.png (action_items.txt #22)
  2. every glyph (score/header/pct/val character) that appears anywhere in the corpus
  3. every image whose resolution is a real corpus outlier (e.g. gm_d_20250908.png, known_issues.txt §18)
  4. every image already proven 'difficult' by an xfail test case, a stat_excluded_cells.json entry, or a known_issues.txt structural-outlier writeup

Doll coverage: 28/28 (['Andoris', 'Centaureissi', 'Colphne', 'Daiyan', 'Faye', 'Florence', 'Jiangyu', 'Klukai', 'Leva', 'Lewis', 'Lind', 'Makiatto', 'Mechty', 'Nikketa', 'Papasha', 'Peritya', 'QiongJiu', 'Qiuhua', 'Sabrina', 'Sakura', 'Sharkry', 'Springfield', 'Suomi', 'Tololo', 'Vector', 'Voymastina', 'Yoohee', 'Zhaohui'])
Glyph coverage: 13/13 (['.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K', 'M'])

Regenerate with:
    python debugs/curate_meaningful_images.py --copy
"""

IMAGES = [
    'fb_d_060518.png',
    'fb_d_20251019.png',
    'fb_d_20251112.png',
    'fb_d_20260315.png',
    'gm_d_20250908.png',
    'gm_d_20251019.png',
    'gm_d_20260201.png',
    'gm_d_20260202.png',
    'ib_d_20250928.png',
    'ib_d_20251004.png',
    'ib_d_20251020.png',
    'ib_d_20251021.png',
    'ib_d_20251024.png',
    'ib_d_20251225.png',
    'ib_d_20260112_1.png',
    'fb_d_20250930.png',
    'gm_d_20260111.png',
    'ib_d_20260114.png',
]

# {source: {"resolution": (w, h), "dolls": [...], "reasons": [...]}}
META = {
    'fb_d_060518.png': {
        "resolution": (1140, 997),
        "dolls": ['Klukai', 'Leva', 'Lind', 'Peritya'],
        "reasons": [
            "known_issues.txt §5 -- first-observed case of the single-panel-incorrectly-split bug (RESOLVED, kept as a regression guard); also known_issues.txt §33 -- score '6795' reads as a bizarre doubled '66779955', not yet root-caused; also resolution outlier within single-panel group: 1140x997 vs group mean 1142x718 (w_z=-0.45, h_z=+3.46)",
            "unique doll frame(s): ['Klukai', 'Leva', 'Lind', 'Peritya']",
            "unique glyph(s): ['.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K']",
        ],
    },
    'fb_d_20251019.png': {
        "resolution": (2301, 695),
        "dolls": ['Nikketa', 'QiongJiu', 'Qiuhua', 'Sharkry', 'Springfield', 'Tololo', 'Vector', 'Zhaohui'],
        "reasons": [
            "known_issues.txt §33 -- panel 2's header score '4407' silently drops to '07' (adjacent-digit-merge blob bug); the motivating case for gfl2/score_ocr_dp.py",
            "unique doll frame(s): ['Nikketa', 'QiongJiu', 'Qiuhua', 'Sharkry', 'Springfield', 'Tololo', 'Vector', 'Zhaohui']",
        ],
    },
    'fb_d_20251112.png': {
        "resolution": (1133, 697),
        "dolls": ['Klukai', 'Lind', 'Mechty', 'Peritya'],
        "reasons": [
            "known_issues.txt §10 -- panel 2's header stats row (dealt/taken/turns) fails at blob extraction entirely; structural rendering outlier, not a classification issue",
            "unique doll frame(s): ['Mechty']",
        ],
    },
    'fb_d_20260315.png': {
        "resolution": (2290, 776),
        "dolls": ['Daiyan', 'Faye', 'Voymastina', 'Yoohee'],
        "reasons": [
            'known_issues.txt §23 -- p1_r3 is a mid-animation screenshot capture (ghosted pct text, blank val); excluded via stat_excluded_cells.json; also resolution outlier within double-panel group: 2290x776 vs group mean 2285x694 (w_z=+0.16, h_z=+6.27)',
            "unique doll frame(s): ['Daiyan', 'Faye', 'Voymastina', 'Yoohee']",
        ],
    },
    'gm_d_20250908.png': {
        "resolution": (2047, 652),
        "dolls": ['Andoris', 'Centaureissi', 'Colphne', 'Florence', 'Sabrina', 'Tololo', 'Vector'],
        "reasons": [
            'known_issues.txt §18 -- ~10% smaller capture resolution than the corpus norm; THRESH_BIN=180 merges col3 digit blobs; xfail in test_stat_ocr_hard_cases.py/test_stat_ocr_padded.py; also resolution outlier within double-panel group: 2047x652 vs group mean 2285x694 (w_z=-8.18, h_z=-3.24)',
            "unique doll frame(s): ['Andoris', 'Centaureissi', 'Colphne', 'Florence', 'Sabrina']",
        ],
    },
    'gm_d_20251019.png': {
        "resolution": (2285, 670),
        "dolls": ['Nikketa', 'QiongJiu', 'Qiuhua', 'Sharkry', 'Springfield', 'Tololo', 'Vector', 'Zhaohui'],
        "reasons": [
            'known_issues.txt §18 (2026-07-09 UPDATE) -- p2_r2_col4 blob-count mismatch (extraction failure, not GT)',
        ],
    },
    'gm_d_20260201.png': {
        "resolution": (1144, 690),
        "dolls": ['Jiangyu', 'Leva', 'Springfield', 'Tololo'],
        "reasons": [
            'known_issues.txt §18 (2026-07-09 UPDATE) -- p1_r2_col4 blob-count mismatch',
            "unique doll frame(s): ['Jiangyu']",
        ],
    },
    'gm_d_20260202.png': {
        "resolution": (2286, 693),
        "dolls": ['Jiangyu', 'Leva', 'QiongJiu', 'Qiuhua', 'Sakura', 'Sharkry', 'Springfield', 'Tololo'],
        "reasons": [
            'known_issues.txt §18 (2026-07-09 UPDATE) -- p2_r3_col1 blob-count mismatch',
            "unique doll frame(s): ['Sakura']",
        ],
    },
    'ib_d_20250928.png': {
        "resolution": (2291, 703),
        "dolls": ['Klukai', 'Nikketa', 'QiongJiu', 'Sharkry', 'Springfield', 'Tololo', 'Vector'],
        "reasons": [
            "test_stat_ocr_padded.py _KNOWN_FAILING_GT_IS_LITERAL_QUESTION_MARK -- p1_r2_col4's own ground truth is a literal '?'",
        ],
    },
    'ib_d_20251004.png': {
        "resolution": (2271, 683),
        "dolls": ['Klukai', 'Nikketa', 'QiongJiu', 'Sharkry', 'Springfield', 'Tololo', 'Vector'],
        "reasons": [
            'known_issues.txt §18 (2026-07-09 UPDATE) -- p1_r3_col2 blob-count mismatch',
        ],
    },
    'ib_d_20251020.png': {
        "resolution": (2297, 695),
        "dolls": ['Klukai', 'Nikketa', 'QiongJiu', 'Sharkry', 'Springfield', 'Tololo', 'Vector'],
        "reasons": [
            "known_issues.txt §18 (2026-07-09 UPDATE) -- p1_r4_col4: GT is single digit '0' but 3 blobs are found (width-19 blob, widest measured anywhere in the corpus) -- suspected ghosting artifact, never root-caused",
        ],
    },
    'ib_d_20251021.png': {
        "resolution": (2284, 687),
        "dolls": ['Klukai', 'Nikketa', 'QiongJiu', 'Sharkry', 'Springfield', 'Tololo', 'Vector'],
        "reasons": [
            'known_issues.txt §18 (2026-07-09 UPDATE) -- p1_r3_col4 blob-count mismatch',
        ],
    },
    'ib_d_20251024.png': {
        "resolution": (2295, 702),
        "dolls": ['Klukai', 'Nikketa', 'QiongJiu', 'Sharkry', 'Springfield', 'Tololo', 'Vector'],
        "reasons": [
            'known_issues.txt §18 (2026-07-09 UPDATE) -- p2_r3_col1 blob-count mismatch',
        ],
    },
    'ib_d_20251225.png': {
        "resolution": (2291, 701),
        "dolls": ['Klukai', 'Lind', 'Mechty', 'Peritya', 'QiongJiu', 'Tololo'],
        "reasons": [
            'known_issues.txt §18 (2026-07-09 UPDATE) -- p2_r3_col1 blob-count mismatch',
        ],
    },
    'ib_d_20260112_1.png': {
        "resolution": (2290, 695),
        "dolls": ['Klukai', 'Lind', 'Makiatto', 'Mechty'],
        "reasons": [
            "test_stat_ocr_padded.py _KNOWN_FAILING_GT_IS_LITERAL_QUESTION_MARK -- p1_r2_col4's own ground truth is a literal '?' (full pipeline, including Tesseract, cannot resolve this digit)",
            "unique doll frame(s): ['Makiatto']",
            "unique glyph(s): ['M']",
        ],
    },
    'fb_d_20250930.png': {
        "resolution": (2278, 690),
        "dolls": ['Nikketa', 'QiongJiu', 'Sharkry', 'Springfield', 'Suomi', 'Tololo', 'Vector'],
        "reasons": [
            "unique doll frame(s): ['Suomi']",
        ],
    },
    'gm_d_20260111.png': {
        "resolution": (2286, 682),
        "dolls": ['Klukai', 'Lind', 'Mechty', 'Nikketa', 'Papasha', 'Peritya', 'QiongJiu', 'Tololo'],
        "reasons": [
            "unique doll frame(s): ['Papasha']",
        ],
    },
    'ib_d_20260114.png': {
        "resolution": (2302, 694),
        "dolls": ['Klukai', 'Lewis', 'Lind', 'Mechty', 'Nikketa', 'Peritya', 'QiongJiu', 'Tololo'],
        "reasons": [
            "unique doll frame(s): ['Lewis']",
        ],
    },
}
