# -*- coding: utf-8 -*-
"""
pct_fft_ground_truth.py -- auto-generated by debugs/pct_fft_predict.py

Living document, not a final oracle: FFT+Gabor nearest-centroid
predictions for every pct cell in the held-out image set (the images
listed in tests/inputs/daily/stat_data.py), gated by a distance-margin
confidence threshold.  '?' marks digits the classifier was not
confident enough to call -- honesty over false precision (see
docs/known_issues.txt Sec14, Sec15).  "label" is the existing
full-pipeline (blob + Tesseract fallback) result, used as the working
reference until spot-checked by a human.

Centroids were built from 71 single/*.png training images,
ALL of which exclude the held-out set below -- this is a genuine
generalization estimate, not train==test separability
(docs/action_items.txt #1).

Regenerate: python debugs/pct_fft_predict.py
"""

CONF_MIN = 0.15

DATA = {
    'fb_d_20250928_p1_r0_col1': {
        "label": '42.74',
        "predicted": '42.?4',
        "confidences": [0.38, 0.284, 0.057, 0.38],
    },
    'fb_d_20250928_p1_r0_col2': {
        "label": '22.87',
        "predicted": '22.87',
        "confidences": [0.236, 0.236, 0.307, 0.427],
    },
    'fb_d_20250928_p1_r0_col3': {
        "label": '17.32',
        "predicted": '17.32',
        "confidences": [1.095, 0.239, 0.331, 0.304],
    },
    'fb_d_20250928_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20250928_p1_r1_col1': {
        "label": '23.73',
        "predicted": '2?.7?',
        "confidences": [0.211, 0.049, 0.613, 0.049],
    },
    'fb_d_20250928_p1_r1_col2': {
        "label": '33.93',
        "predicted": '33.?3',
        "confidences": [0.24, 0.404, 0.115, 0.24],
    },
    'fb_d_20250928_p1_r1_col3': {
        "label": '10.88',
        "predicted": '10.??',
        "confidences": [0.768, 0.194, 0.059, 0.059],
    },
    'fb_d_20250928_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20250928_p1_r2_col1': {
        "label": '18.43',
        "predicted": '18.??',
        "confidences": [0.96, 0.266, 0.067, 0.044],
    },
    'fb_d_20250928_p1_r2_col2': {
        "label": '24.22',
        "predicted": '2?.22',
        "confidences": [0.238, 0.021, 0.238, 0.238],
    },
    'fb_d_20250928_p1_r2_col3': {
        "label": '27.83',
        "predicted": '2?.83',
        "confidences": [0.423, 0.126, 0.259, 0.317],
    },
    'fb_d_20250928_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.182],
    },
    'fb_d_20250928_p1_r3_col1': {
        "label": '12.06',
        "predicted": '12.??',
        "confidences": [0.302, 0.404, 0.02, 0.036],
    },
    'fb_d_20250928_p1_r3_col2': {
        "label": '11.81',
        "predicted": '11.?1',
        "confidences": [0.817, 0.817, 0.146, 0.817],
    },
    'fb_d_20250928_p1_r3_col3': {
        "label": '31.05',
        "predicted": '31.05',
        "confidences": [0.54, 1.313, 0.152, 0.237],
    },
    'fb_d_20250928_p1_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.342],
    },
    'fb_d_20250928_p1_r4_col1': {
        "label": '3.04',
        "predicted": '?.04',
        "confidences": [0.073, 0.261, 0.389],
    },
    'fb_d_20250928_p1_r4_col2': {
        "label": '7.17',
        "predicted": '7.17',
        "confidences": [0.385, 0.677, 0.385],
    },
    'fb_d_20250928_p1_r4_col3': {
        "label": '12.92',
        "predicted": '1?.??',
        "confidences": [0.933, 0.139, 0.014, 0.139],
    },
    'fb_d_20250928_p1_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [0.531, 0.178, 0.178],
    },
    'fb_d_20250928_p2_r0_col1': {
        "label": '48.02',
        "predicted": '4?.?2',
        "confidences": [0.38, 0.011, 0.147, 0.284],
    },
    'fb_d_20250928_p2_r0_col2': {
        "label": '33.18',
        "predicted": '33.18',
        "confidences": [0.487, 0.368, 0.204, 0.307],
    },
    'fb_d_20250928_p2_r0_col3': {
        "label": '34.79',
        "predicted": '34.7?',
        "confidences": [0.232, 0.243, 0.239, 0.107],
    },
    'fb_d_20250928_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20250928_p2_r1_col1': {
        "label": '22.67',
        "predicted": '22.?7',
        "confidences": [0.211, 0.211, 0.003, 0.613],
    },
    'fb_d_20250928_p2_r1_col2': {
        "label": '19.09',
        "predicted": '1?.0?',
        "confidences": [0.507, 0.042, 0.296, 0.042],
    },
    'fb_d_20250928_p2_r1_col3': {
        "label": '10.36',
        "predicted": '10.3?',
        "confidences": [0.768, 0.194, 0.36, 0.044],
    },
    'fb_d_20250928_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20250928_p2_r2_col1': {
        "label": '21.9',
        "predicted": '21.?',
        "confidences": [0.265, 0.96, 0.069],
    },
    'fb_d_20250928_p2_r2_col2': {
        "label": '15.84',
        "predicted": '15.84',
        "confidences": [0.173, 0.23, 0.248, 0.222],
    },
    'fb_d_20250928_p2_r2_col3': {
        "label": '12.64',
        "predicted": '12.??',
        "confidences": [0.415, 0.319, 0.013, 0.099],
    },
    'fb_d_20250928_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.161],
    },
    'fb_d_20250928_p2_r3_col1': {
        "label": '5.31',
        "predicted": '5.?1',
        "confidences": [0.218, 0.074, 0.302],
    },
    'fb_d_20250928_p2_r3_col2': {
        "label": '19.74',
        "predicted": '1?.74',
        "confidences": [0.425, 0.033, 0.62, 0.213],
    },
    'fb_d_20250928_p2_r3_col3': {
        "label": '10.27',
        "predicted": '1?.27',
        "confidences": [1.313, 0.094, 0.256, 0.293],
    },
    'fb_d_20250928_p2_r3_col4': {
        "label": '5.23',
        "predicted": '5.23',
        "confidences": [0.249, 0.319, 0.154],
    },
    'fb_d_20250928_p2_r4_col1': {
        "label": '2.1',
        "predicted": '2.1',
        "confidences": [0.343, 0.949],
    },
    'fb_d_20250928_p2_r4_col2': {
        "label": '12.15',
        "predicted": '??.?5',
        "confidences": [0.125, 0.021, 0.125, 0.766],
    },
    'fb_d_20250928_p2_r4_col3': {
        "label": '31.94',
        "predicted": '31.?4',
        "confidences": [0.218, 0.933, 0.049, 0.382],
    },
    'fb_d_20250928_p2_r4_col4': {
        "label": '94.77',
        "predicted": '?4.77',
        "confidences": [0.072, 0.244, 0.743, 0.743],
    },
    'fb_d_20250930_p1_r0_col1': {
        "label": '48.46',
        "predicted": '4?.4?',
        "confidences": [0.38, 0.011, 0.38, 0.142],
    },
    'fb_d_20250930_p1_r0_col2': {
        "label": '20.92',
        "predicted": '20.?2',
        "confidences": [0.236, 0.265, 0.067, 0.236],
    },
    'fb_d_20250930_p1_r0_col3': {
        "label": '21.09',
        "predicted": '21.0?',
        "confidences": [0.304, 1.095, 0.215, 0.107],
    },
    'fb_d_20250930_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20250930_p1_r1_col1': {
        "label": '26.07',
        "predicted": '2?.07',
        "confidences": [0.211, 0.003, 0.169, 0.613],
    },
    'fb_d_20250930_p1_r1_col2': {
        "label": '32.87',
        "predicted": '32.?7',
        "confidences": [0.24, 0.339, 0.061, 0.368],
    },
    'fb_d_20250930_p1_r1_col3': {
        "label": '22.34',
        "predicted": '22.34',
        "confidences": [0.234, 0.234, 0.293, 0.34],
    },
    'fb_d_20250930_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20250930_p1_r2_col1': {
        "label": '14.64',
        "predicted": '1?.??',
        "confidences": [0.96, 0.067, 0.061, 0.067],
    },
    'fb_d_20250930_p1_r2_col2': {
        "label": '25.7',
        "predicted": '25.?',
        "confidences": [0.238, 0.23, 0.142],
    },
    'fb_d_20250930_p1_r2_col3': {
        "label": '22.88',
        "predicted": '22.88',
        "confidences": [0.423, 0.423, 0.259, 0.259],
    },
    'fb_d_20250930_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.182],
    },
    'fb_d_20250930_p1_r3_col1': {
        "label": '6.99',
        "predicted": '?.??',
        "confidences": [0.036, 0.084, 0.084],
    },
    'fb_d_20250930_p1_r3_col2': {
        "label": '11.52',
        "predicted": '11.52',
        "confidences": [0.817, 0.817, 0.391, 0.333],
    },
    'fb_d_20250930_p1_r3_col3': {
        "label": '18.99',
        "predicted": '18.??',
        "confidences": [1.313, 0.309, 0.071, 0.071],
    },
    'fb_d_20250930_p1_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.342],
    },
    'fb_d_20250930_p1_r4_col1': {
        "label": '3.84',
        "predicted": '?.?4',
        "confidences": [0.073, 0.095, 0.389],
    },
    'fb_d_20250930_p1_r4_col2': {
        "label": '8.99',
        "predicted": '?.??',
        "confidences": [0.038, 0.122, 0.122],
    },
    'fb_d_20250930_p1_r4_col3': {
        "label": '14.7',
        "predicted": '14.7',
        "confidences": [0.933, 0.382, 0.373],
    },
    'fb_d_20250930_p1_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [0.531, 0.178, 0.178],
    },
    'fb_d_20250930_p2_r0_col1': {
        "label": '53.51',
        "predicted": '??.?1',
        "confidences": [0.073, 0.022, 0.073, 0.644],
    },
    'fb_d_20250930_p2_r0_col2': {
        "label": '32.73',
        "predicted": '32.73',
        "confidences": [0.487, 0.25, 0.427, 0.368],
    },
    'fb_d_20250930_p2_r0_col3': {
        "label": '23.54',
        "predicted": '23.54',
        "confidences": [0.304, 0.232, 0.4, 0.243],
    },
    'fb_d_20250930_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20250930_p2_r1_col1': {
        "label": '36.82',
        "predicted": '??.?2',
        "confidences": [0.049, 0.003, 0.102, 0.211],
    },
    'fb_d_20250930_p2_r1_col2': {
        "label": '14.83',
        "predicted": '14.?3',
        "confidences": [0.507, 0.151, 0.06, 0.404],
    },
    'fb_d_20250930_p2_r1_col3': {
        "label": '20.36',
        "predicted": '20.3?',
        "confidences": [0.234, 0.194, 0.36, 0.044],
    },
    'fb_d_20250930_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20250930_p2_r2_col1': {
        "label": '5.11',
        "predicted": '?.11',
        "confidences": [0.091, 0.96, 0.96],
    },
    'fb_d_20250930_p2_r2_col2': {
        "label": '9.17',
        "predicted": '?.1?',
        "confidences": [0.065, 0.173, 0.142],
    },
    'fb_d_20250930_p2_r2_col3': {
        "label": '13.29',
        "predicted": '13.2?',
        "confidences": [0.415, 0.209, 0.319, 0.042],
    },
    'fb_d_20250930_p2_r2_col4': {
        "label": '16.25',
        "predicted": '1?.25',
        "confidences": [0.84, 0.014, 0.311, 0.203],
    },
    'fb_d_20250930_p2_r3_col1': {
        "label": '2.63',
        "predicted": '2.??',
        "confidences": [0.404, 0.036, 0.074],
    },
    'fb_d_20250930_p2_r3_col2': {
        "label": '33.18',
        "predicted": '33.1?',
        "confidences": [0.192, 0.192, 0.425, 0.091],
    },
    'fb_d_20250930_p2_r3_col3': {
        "label": '12.41',
        "predicted": '12.?1',
        "confidences": [1.313, 0.256, 0.009, 1.313],
    },
    'fb_d_20250930_p2_r3_col4': {
        "label": '81.44',
        "predicted": '81.??',
        "confidences": [0.333, 1.309, 0.093, 0.093],
    },
    'fb_d_20250930_p2_r4_col1': {
        "label": '1.93',
        "predicted": '1.??',
        "confidences": [0.949, 0.055, 0.073],
    },
    'fb_d_20250930_p2_r4_col2': {
        "label": '10.09',
        "predicted": '?0.0?',
        "confidences": [0.125, 0.297, 0.297, 0.122],
    },
    'fb_d_20250930_p2_r4_col3': {
        "label": '30.4',
        "predicted": '30.4',
        "confidences": [0.218, 0.19, 0.382],
    },
    'fb_d_20250930_p2_r4_col4': {
        "label": '2.3',
        "predicted": '?.3',
        "confidences": [0.104, 0.276],
    },
    'fb_d_20251022_p1_r0_col1': {
        "label": '48.92',
        "predicted": '4?.?2',
        "confidences": [0.38, 0.011, 0.132, 0.284],
    },
    'fb_d_20251022_p1_r0_col2': {
        "label": '23.87',
        "predicted": '23.87',
        "confidences": [0.236, 0.452, 0.307, 0.427],
    },
    'fb_d_20251022_p1_r0_col3': {
        "label": '17.4',
        "predicted": '17.4',
        "confidences": [1.095, 0.239, 0.243],
    },
    'fb_d_20251022_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20251022_p1_r1_col1': {
        "label": '36.44',
        "predicted": '??.44',
        "confidences": [0.049, 0.003, 0.232, 0.232],
    },
    'fb_d_20251022_p1_r1_col2': {
        "label": '41.72',
        "predicted": '41.72',
        "confidences": [0.151, 0.601, 0.368, 0.339],
    },
    'fb_d_20251022_p1_r1_col3': {
        "label": '14.67',
        "predicted": '14.?7',
        "confidences": [0.768, 0.34, 0.044, 0.546],
    },
    'fb_d_20251022_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20251022_p1_r2_col1': {
        "label": '9.9',
        "predicted": '?.?',
        "confidences": [0.069, 0.069],
    },
    'fb_d_20251022_p1_r2_col2': {
        "label": '10.55',
        "predicted": '10.55',
        "confidences": [0.235, 0.315, 0.23, 0.23],
    },
    'fb_d_20251022_p1_r2_col3': {
        "label": '35.92',
        "predicted": '3?.?2',
        "confidences": [0.317, 0.14, 0.022, 0.319],
    },
    'fb_d_20251022_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.176],
    },
    'fb_d_20251022_p1_r3_col1': {
        "label": '3.74',
        "predicted": '?.74',
        "confidences": [0.074, 0.231, 0.398],
    },
    'fb_d_20251022_p1_r3_col2': {
        "label": '13.31',
        "predicted": '13.31',
        "confidences": [0.425, 0.192, 0.192, 0.425],
    },
    'fb_d_20251022_p1_r3_col3': {
        "label": '19.4',
        "predicted": '1?.?',
        "confidences": [1.313, 0.071, 0.009],
    },
    'fb_d_20251022_p1_r3_col4': {
        "label": '73.01',
        "predicted": '73.01',
        "confidences": [0.617, 0.154, 0.231, 1.309],
    },
    'fb_d_20251022_p1_r4_col1': {
        "label": '1',
        "predicted": '1',
        "confidences": [0.949],
    },
    'fb_d_20251022_p1_r4_col2': {
        "label": '10.55',
        "predicted": '?0.55',
        "confidences": [0.125, 0.297, 0.766, 0.766],
    },
    'fb_d_20251022_p1_r4_col3': {
        "label": '12.61',
        "predicted": '1?.?1',
        "confidences": [0.933, 0.139, 0.063, 0.933],
    },
    'fb_d_20251022_p1_r4_col4': {
        "label": '26.99',
        "predicted": '??.??',
        "confidences": [0.104, 0.06, 0.072, 0.072],
    },
    'fb_d_20251022_p2_r0_col1': {
        "label": '39.53',
        "predicted": '??.??',
        "confidences": [0.022, 0.132, 0.073, 0.022],
    },
    'fb_d_20251022_p2_r0_col2': {
        "label": '19.06',
        "predicted": '1?.0?',
        "confidences": [0.204, 0.069, 0.265, 0.027],
    },
    'fb_d_20251022_p2_r0_col3': {
        "label": '29.34',
        "predicted": '2?.34',
        "confidences": [0.304, 0.107, 0.232, 0.243],
    },
    'fb_d_20251022_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20251022_p2_r1_col1': {
        "label": '29.99',
        "predicted": '2?.??',
        "confidences": [0.211, 0.015, 0.015, 0.015],
    },
    'fb_d_20251022_p2_r1_col2': {
        "label": '24.53',
        "predicted": '24.53',
        "confidences": [0.452, 0.151, 0.432, 0.404],
    },
    'fb_d_20251022_p2_r1_col3': {
        "label": '24.11',
        "predicted": '2?.11',
        "confidences": [0.234, 0.131, 0.768, 0.768],
    },
    'fb_d_20251022_p2_r1_col4': {
        "label": '8.34',
        "predicted": '?.?4',
        "confidences": [0.022, 0.098, 0.253],
    },
    'fb_d_20251022_p2_r2_col1': {
        "label": '19.17',
        "predicted": '1?.17',
        "confidences": [0.96, 0.008, 0.96, 0.306],
    },
    'fb_d_20251022_p2_r2_col2': {
        "label": '32.03',
        "predicted": '32.03',
        "confidences": [0.18, 0.343, 0.315, 0.18],
    },
    'fb_d_20251022_p2_r2_col3': {
        "label": '15.52',
        "predicted": '15.52',
        "confidences": [0.415, 0.153, 0.153, 0.319],
    },
    'fb_d_20251022_p2_r2_col4': {
        "label": '6.26',
        "predicted": '?.2?',
        "confidences": [0.077, 0.43, 0.077],
    },
    'fb_d_20251022_p2_r3_col1': {
        "label": '9.48',
        "predicted": '?.48',
        "confidences": [0.084, 0.398, 0.265],
    },
    'fb_d_20251022_p2_r3_col2': {
        "label": '12.55',
        "predicted": '12.55',
        "confidences": [0.425, 0.476, 0.391, 0.391],
    },
    'fb_d_20251022_p2_r3_col3': {
        "label": '11.95',
        "predicted": '11.?5',
        "confidences": [1.313, 1.313, 0.071, 0.237],
    },
    'fb_d_20251022_p2_r3_col4': {
        "label": '5.59',
        "predicted": '5.5?',
        "confidences": [0.249, 0.249, 0.002],
    },
    'fb_d_20251022_p2_r4_col1': {
        "label": '1.83',
        "predicted": '1.??',
        "confidences": [0.949, 0.095, 0.073],
    },
    'fb_d_20251022_p2_r4_col2': {
        "label": '11.83',
        "predicted": '??.?3',
        "confidences": [0.125, 0.125, 0.038, 0.195],
    },
    'fb_d_20251022_p2_r4_col3': {
        "label": '19.08',
        "predicted": '1?.08',
        "confidences": [0.933, 0.049, 0.19, 0.238],
    },
    'fb_d_20251022_p2_r4_col4': {
        "label": '79.81',
        "predicted": '7?.81',
        "confidences": [0.743, 0.072, 0.326, 0.531],
    },
    'fb_d_20251024_p1_r0_col1': {
        "label": '49.29',
        "predicted": '4?.2?',
        "confidences": [0.38, 0.132, 0.284, 0.132],
    },
    'fb_d_20251024_p1_r0_col2': {
        "label": '26.69',
        "predicted": '2?.??',
        "confidences": [0.236, 0.027, 0.027, 0.067],
    },
    'fb_d_20251024_p1_r0_col3': {
        "label": '33.83',
        "predicted": '33.83',
        "confidences": [0.331, 0.331, 0.301, 0.331],
    },
    'fb_d_20251024_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20251024_p1_r1_col1': {
        "label": '37.6',
        "predicted": '?7.?',
        "confidences": [0.049, 0.613, 0.003],
    },
    'fb_d_20251024_p1_r1_col2': {
        "label": '36.49',
        "predicted": '33.4?',
        "confidences": [0.24, 0.18, 0.151, 0.115],
    },
    'fb_d_20251024_p1_r1_col3': {
        "label": '23.71',
        "predicted": '23.71',
        "confidences": [0.234, 0.293, 0.546, 0.768],
    },
    'fb_d_20251024_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20251024_p1_r2_col1': {
        "label": '10.03',
        "predicted": '1?.??',
        "confidences": [0.96, 0.086, 0.086, 0.044],
    },
    'fb_d_20251024_p1_r2_col2': {
        "label": '15.96',
        "predicted": '15.??',
        "confidences": [0.235, 0.23, 0.065, 0.081],
    },
    'fb_d_20251024_p1_r2_col3': {
        "label": '9.9',
        "predicted": '?.?',
        "confidences": [0.022, 0.022],
    },
    'fb_d_20251024_p1_r2_col4': {
        "label": '0.35',
        "predicted": '0.35',
        "confidences": [0.176, 0.194, 0.385],
    },
    'fb_d_20251024_p1_r3_col1': {
        "label": '1.84',
        "predicted": '1.84',
        "confidences": [0.302, 0.265, 0.398],
    },
    'fb_d_20251024_p1_r3_col2': {
        "label": '6.64',
        "predicted": '?.?4',
        "confidences": [0.021, 0.021, 0.213],
    },
    'fb_d_20251024_p1_r3_col3': {
        "label": '8.96',
        "predicted": '8.??',
        "confidences": [0.309, 0.071, 0.051],
    },
    'fb_d_20251024_p1_r3_col4': {
        "label": '94.45',
        "predicted": '??.?5',
        "confidences": [0.002, 0.093, 0.093, 0.249],
    },
    'fb_d_20251024_p1_r4_col1': {
        "label": '1.24',
        "predicted": '1.24',
        "confidences": [0.949, 0.343, 0.389],
    },
    'fb_d_20251024_p1_r4_col2': {
        "label": '14.22',
        "predicted": '??.??',
        "confidences": [0.125, 0.096, 0.021, 0.021],
    },
    'fb_d_20251024_p1_r4_col3': {
        "label": '23.6',
        "predicted": '?3.?',
        "confidences": [0.139, 0.218, 0.063],
    },
    'fb_d_20251024_p1_r4_col4': {
        "label": '5.2',
        "predicted": '5.?',
        "confidences": [0.326, 0.104],
    },
    'fb_d_20251024_p2_r0_col1': {
        "label": '43.84',
        "predicted": '4?.?4',
        "confidences": [0.38, 0.022, 0.011, 0.38],
    },
    'fb_d_20251024_p2_r0_col2': {
        "label": '18.67',
        "predicted": '18.?7',
        "confidences": [0.204, 0.307, 0.022, 0.263],
    },
    'fb_d_20251024_p2_r0_col3': {
        "label": '35.52',
        "predicted": '35.52',
        "confidences": [0.232, 0.4, 0.4, 0.304],
    },
    'fb_d_20251024_p2_r0_col4': {
        "label": '2.55',
        "predicted": '2.55',
        "confidences": [0.395, 0.374, 0.374],
    },
    'fb_d_20251024_p2_r1_col1': {
        "label": '27.72',
        "predicted": '27.72',
        "confidences": [0.211, 0.613, 0.613, 0.211],
    },
    'fb_d_20251024_p2_r1_col2': {
        "label": '24.61',
        "predicted": '24.?1',
        "confidences": [0.452, 0.151, 0.125, 0.507],
    },
    'fb_d_20251024_p2_r1_col3': {
        "label": '24.45',
        "predicted": '2?.?5',
        "confidences": [0.234, 0.131, 0.131, 0.274],
    },
    'fb_d_20251024_p2_r1_col4': {
        "label": '10.26',
        "predicted": '10.2?',
        "confidences": [0.768, 0.302, 0.219, 0.012],
    },
    'fb_d_20251024_p2_r2_col1': {
        "label": '17.93',
        "predicted": '17.??',
        "confidences": [0.96, 0.306, 0.008, 0.044],
    },
    'fb_d_20251024_p2_r2_col2': {
        "label": '31.12',
        "predicted": '31.12',
        "confidences": [0.18, 0.173, 0.173, 0.343],
    },
    'fb_d_20251024_p2_r2_col3': {
        "label": '11.63',
        "predicted": '11.?3',
        "confidences": [0.415, 0.415, 0.013, 0.276],
    },
    'fb_d_20251024_p2_r2_col4': {
        "label": '4.54',
        "predicted": '4.54',
        "confidences": [0.201, 0.203, 0.201],
    },
    'fb_d_20251024_p2_r3_col1': {
        "label": '8.38',
        "predicted": '8.?8',
        "confidences": [0.265, 0.074, 0.265],
    },
    'fb_d_20251024_p2_r3_col2': {
        "label": '10.75',
        "predicted": '10.75',
        "confidences": [0.425, 0.272, 0.62, 0.391],
    },
    'fb_d_20251024_p2_r3_col3': {
        "label": '11.43',
        "predicted": '11.?3',
        "confidences": [1.313, 1.313, 0.009, 0.54],
    },
    'fb_d_20251024_p2_r3_col4': {
        "label": '3.92',
        "predicted": '3.?2',
        "confidences": [0.154, 0.002, 0.319],
    },
    'fb_d_20251024_p2_r4_col1': {
        "label": '2.13',
        "predicted": '2.1?',
        "confidences": [0.343, 0.949, 0.073],
    },
    'fb_d_20251024_p2_r4_col2': {
        "label": '14.85',
        "predicted": '??.?5',
        "confidences": [0.125, 0.096, 0.038, 0.766],
    },
    'fb_d_20251024_p2_r4_col3': {
        "label": '16.97',
        "predicted": '1?.?7',
        "confidences": [0.933, 0.063, 0.049, 0.373],
    },
    'fb_d_20251024_p2_r4_col4': {
        "label": '78.73',
        "predicted": '78.73',
        "confidences": [0.743, 0.326, 0.743, 0.276],
    },
    'fb_d_20251111_p1_r0_col1': {
        "label": '71.47',
        "predicted": '?1.4?',
        "confidences": [0.057, 0.644, 0.38, 0.057],
    },
    'fb_d_20251111_p1_r0_col2': {
        "label": '44.5',
        "predicted": '44.5',
        "confidences": [0.178, 0.178, 0.334],
    },
    'fb_d_20251111_p1_r0_col3': {
        "label": '17.73',
        "predicted": '17.73',
        "confidences": [1.095, 0.239, 0.239, 0.331],
    },
    'fb_d_20251111_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20251111_p1_r1_col1': {
        "label": '10.26',
        "predicted": '1?.??',
        "confidences": [0.719, 0.071, 0.005, 0.015],
    },
    'fb_d_20251111_p1_r1_col2': {
        "label": '14.18',
        "predicted": '14.18',
        "confidences": [0.642, 0.178, 0.642, 0.169],
    },
    'fb_d_20251111_p1_r1_col3': {
        "label": '29.99',
        "predicted": '??.??',
        "confidences": [0.018, 0.124, 0.124, 0.124],
    },
    'fb_d_20251111_p1_r1_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.108],
    },
    'fb_d_20251111_p1_r2_col1': {
        "label": '9.78',
        "predicted": '?.78',
        "confidences": [0.001, 0.398, 0.157],
    },
    'fb_d_20251111_p1_r2_col2': {
        "label": '34.02',
        "predicted": '34.02',
        "confidences": [0.256, 0.172, 0.232, 0.47],
    },
    'fb_d_20251111_p1_r2_col3': {
        "label": '18.91',
        "predicted": '1?.?1',
        "confidences": [0.768, 0.095, 0.006, 0.768],
    },
    'fb_d_20251111_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.213],
    },
    'fb_d_20251111_p1_r3_col1': {
        "label": '8.09',
        "predicted": '8.??',
        "confidences": [0.214, 0.147, 0.067],
    },
    'fb_d_20251111_p1_r3_col2': {
        "label": '4.11',
        "predicted": '4.11',
        "confidences": [0.228, 0.173, 0.173],
    },
    'fb_d_20251111_p1_r3_col3': {
        "label": '9.16',
        "predicted": '?.1?',
        "confidences": [0.062, 0.415, 0.012],
    },
    'fb_d_20251111_p1_r3_col4': {
        "label": '44.38',
        "predicted": '44.?8',
        "confidences": [0.201, 0.201, 0.128, 0.206],
    },
    'fb_d_20251111_p2_r0_col1': {
        "label": '45.39',
        "predicted": '4?.??',
        "confidences": [0.38, 0.073, 0.022, 0.132],
    },
    'fb_d_20251111_p2_r0_col2': {
        "label": '30.25',
        "predicted": '30.25',
        "confidences": [0.487, 0.28, 0.25, 0.334],
    },
    'fb_d_20251111_p2_r0_col3': {
        "label": '24',
        "predicted": '24',
        "confidences": [0.304, 0.243],
    },
    'fb_d_20251111_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20251111_p2_r1_col1': {
        "label": '27.45',
        "predicted": '27.45',
        "confidences": [0.211, 0.613, 0.232, 0.157],
    },
    'fb_d_20251111_p2_r1_col2': {
        "label": '30.24',
        "predicted": '30.24',
        "confidences": [0.404, 0.296, 0.452, 0.151],
    },
    'fb_d_20251111_p2_r1_col3': {
        "label": '18.32',
        "predicted": '1?.32',
        "confidences": [0.768, 0.059, 0.36, 0.234],
    },
    'fb_d_20251111_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20251111_p2_r2_col1': {
        "label": '14.82',
        "predicted": '1?.8?',
        "confidences": [0.96, 0.036, 0.266, 0.074],
    },
    'fb_d_20251111_p2_r2_col2': {
        "label": '12.9',
        "predicted": '12.?',
        "confidences": [0.173, 0.343, 0.065],
    },
    'fb_d_20251111_p2_r2_col3': {
        "label": '18.56',
        "predicted": '18.5?',
        "confidences": [0.415, 0.409, 0.153, 0.013],
    },
    'fb_d_20251111_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.161],
    },
    'fb_d_20251111_p2_r3_col1': {
        "label": '11.36',
        "predicted": '11.??',
        "confidences": [0.302, 0.302, 0.074, 0.036],
    },
    'fb_d_20251111_p2_r3_col2': {
        "label": '25',
        "predicted": '25',
        "confidences": [0.476, 0.391],
    },
    'fb_d_20251111_p2_r3_col3': {
        "label": '19.12',
        "predicted": '1?.12',
        "confidences": [1.313, 0.071, 1.313, 0.256],
    },
    'fb_d_20251111_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.231],
    },
    'fb_d_20251111_p2_r4_col1': {
        "label": '0.98',
        "predicted": '0.??',
        "confidences": [0.261, 0.055, 0.095],
    },
    'fb_d_20251111_p2_r4_col2': {
        "label": '1.61',
        "predicted": '?.??',
        "confidences": [0.125, 0.069, 0.125],
    },
    'fb_d_20251111_p2_r4_col3': {
        "label": '20',
        "predicted": '?0',
        "confidences": [0.139, 0.19],
    },
    'fb_d_20251111_p2_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [0.531, 0.178, 0.178],
    },
    'fb_d_20251112_p1_r0_col1': {
        "label": '72.76',
        "predicted": '?2.??',
        "confidences": [0.057, 0.284, 0.057, 0.142],
    },
    'fb_d_20251112_p1_r0_col2': {
        "label": '44.28',
        "predicted": '44.28',
        "confidences": [0.178, 0.178, 0.236, 0.307],
    },
    'fb_d_20251112_p1_r0_col3': {
        "label": '16.78',
        "predicted": '1?.78',
        "confidences": [1.095, 0.138, 0.239, 0.301],
    },
    'fb_d_20251112_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'fb_d_20251112_p1_r1_col1': {
        "label": '9.73',
        "predicted": '?.7?',
        "confidences": [0.015, 0.613, 0.049],
    },
    'fb_d_20251112_p1_r1_col2': {
        "label": '13.98',
        "predicted": '13.??',
        "confidences": [0.601, 0.404, 0.115, 0.061],
    },
    'fb_d_20251112_p1_r1_col3': {
        "label": '32.15',
        "predicted": '32.15',
        "confidences": [0.293, 0.234, 0.768, 0.247],
    },
    'fb_d_20251112_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'fb_d_20251112_p1_r2_col1': {
        "label": '8.86',
        "predicted": '8.8?',
        "confidences": [0.266, 0.266, 0.061],
    },
    'fb_d_20251112_p1_r2_col2': {
        "label": '33.6',
        "predicted": '33.?',
        "confidences": [0.304, 0.304, 0.035],
    },
    'fb_d_20251112_p1_r2_col3': {
        "label": '21.97',
        "predicted": '21.??',
        "confidences": [0.423, 0.415, 0.022, 0.126],
    },
    'fb_d_20251112_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.182],
    },
    'fb_d_20251112_p1_r3_col1': {
        "label": '8.03',
        "predicted": '8.??',
        "confidences": [0.265, 0.02, 0.074],
    },
    'fb_d_20251112_p1_r3_col2': {
        "label": '4.02',
        "predicted": '4.02',
        "confidences": [0.213, 0.264, 0.333],
    },
    'fb_d_20251112_p1_r3_col3': {
        "label": '9.02',
        "predicted": '?.02',
        "confidences": [0.071, 0.152, 0.256],
    },
    'fb_d_20251112_p1_r3_col4': {
        "label": '32.48',
        "predicted": '32.?8',
        "confidences": [0.502, 0.518, 0.004, 0.299],
    },
    'fb_d_20251112_p1_r4_col1': {
        "label": '0.62',
        "predicted": '0.?2',
        "confidences": [0.261, 0.069, 0.343],
    },
    'fb_d_20251112_p1_r4_col2': {
        "label": '4.12',
        "predicted": '?.1?',
        "confidences": [0.096, 0.677, 0.058],
    },
    'fb_d_20251112_p1_r4_col3': {
        "label": '20.08',
        "predicted": '??.?8',
        "confidences": [0.139, 0.006, 0.006, 0.154],
    },
    'fb_d_20251112_p1_r4_col4': {
        "label": '67.52',
        "predicted": '?7.5?',
        "confidences": [0.06, 0.743, 0.326, 0.032],
    },
    'gm_d_20250908_p1_r0_col1': {
        "label": '39.6',
        "predicted": '??.?',
        "confidences": [0.039, 0.027, 0.018],
    },
    'gm_d_20250908_p1_r0_col2': {
        "label": '34.3',
        "predicted": '??.?',
        "confidences": [0.039, 0.109, 0.039],
    },
    'gm_d_20250908_p1_r0_col3': {
        "label": '3',
        "predicted": '?',
        "confidences": [0.028],
    },
    'gm_d_20250908_p1_r0_col4': {
        "label": '10.4',
        "predicted": '1?.4',
        "confidences": [0.361, 0.043, 0.275],
    },
    'gm_d_20250908_p1_r1_col1': {
        "label": '37.3',
        "predicted": '??.?',
        "confidences": [0.039, 0.022, 0.039],
    },
    'gm_d_20250908_p1_r1_col2': {
        "label": '23.1',
        "predicted": '??.1',
        "confidences": [0.029, 0.039, 0.361],
    },
    'gm_d_20250908_p1_r1_col3': {
        "label": '2',
        "predicted": '?',
        "confidences": [0.035],
    },
    'gm_d_20250908_p1_r1_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.043],
    },
    'gm_d_20250908_p1_r2_col1': {
        "label": '12.1',
        "predicted": '12.1',
        "confidences": [0.953, 0.286, 0.953],
    },
    'gm_d_20250908_p1_r2_col2': {
        "label": '20.0',
        "predicted": '??.?',
        "confidences": [0.065, 0.099, 0.099],
    },
    'gm_d_20250908_p1_r2_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [0.612],
    },
    'gm_d_20250908_p1_r2_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.043],
    },
    'gm_d_20250908_p1_r3_col1': {
        "label": '8.6',
        "predicted": '8.?',
        "confidences": [0.291, 0.018],
    },
    'gm_d_20250908_p1_r3_col2': {
        "label": '11.9',
        "predicted": '11.?',
        "confidences": [0.361, 0.361, 0.03],
    },
    'gm_d_20250908_p1_r3_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [0.612],
    },
    'gm_d_20250908_p1_r3_col4': {
        "label": '1.2',
        "predicted": '1.2',
        "confidences": [0.361, 0.218],
    },
    'gm_d_20250908_p1_r4_col1': {
        "label": '2.2',
        "predicted": '2.2',
        "confidences": [0.286, 0.286],
    },
    'gm_d_20250908_p1_r4_col2': {
        "label": '10.4',
        "predicted": '1?.?',
        "confidences": [0.361, 0.099, 0.109],
    },
    'gm_d_20250908_p1_r4_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [0.612],
    },
    'gm_d_20250908_p1_r4_col4': {
        "label": '88.4',
        "predicted": '88.4',
        "confidences": [0.194, 0.194, 0.275],
    },
    'gm_d_20250908_p2_r0_col1': {
        "label": '43.3',
        "predicted": '??.?',
        "confidences": [0.097, 0.039, 0.039],
    },
    'gm_d_20250908_p2_r0_col2': {
        "label": '30.1',
        "predicted": '??.1',
        "confidences": [0.039, 0.135, 0.361],
    },
    'gm_d_20250908_p2_r0_col3': {
        "label": '18.66',
        "predicted": '1?.??',
        "confidences": [0.612, 0.015, 0.055, 0.055],
    },
    'gm_d_20250908_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.043],
    },
    'gm_d_20250908_p2_r1_col1': {
        "label": '34.7',
        "predicted": '??.?',
        "confidences": [0.039, 0.097, 0.022],
    },
    'gm_d_20250908_p2_r1_col2': {
        "label": '37.2',
        "predicted": '?7.?',
        "confidences": [0.039, 0.182, 0.065],
    },
    'gm_d_20250908_p2_r1_col3': {
        "label": '3',
        "predicted": '?',
        "confidences": [0.028],
    },
    'gm_d_20250908_p2_r1_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.043],
    },
    'gm_d_20250908_p2_r2_col1': {
        "label": '16.4',
        "predicted": '1?.?',
        "confidences": [0.953, 0.018, 0.097],
    },
    'gm_d_20250908_p2_r2_col2': {
        "label": '12.9',
        "predicted": '1?.?',
        "confidences": [0.361, 0.065, 0.03],
    },
    'gm_d_20250908_p2_r2_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [0.612],
    },
    'gm_d_20250908_p2_r2_col4': {
        "label": '12.45',
        "predicted": '12.4?',
        "confidences": [0.361, 0.218, 0.275, 0.015],
    },
    'gm_d_20250908_p2_r3_col1': {
        "label": '3.3',
        "predicted": '?.?',
        "confidences": [0.039, 0.039],
    },
    'gm_d_20250908_p2_r3_col2': {
        "label": '7.1',
        "predicted": '7.1',
        "confidences": [0.182, 0.361],
    },
    'gm_d_20250908_p2_r3_col3': {
        "label": '2',
        "predicted": '?',
        "confidences": [0.035],
    },
    'gm_d_20250908_p2_r3_col4': {
        "label": '76.51',
        "predicted": '??.?1',
        "confidences": [0.133, 0.06, 0.015, 0.361],
    },
    'gm_d_20250908_p2_r4_col1': {
        "label": '2.1',
        "predicted": '2.1',
        "confidences": [0.286, 0.953],
    },
    'gm_d_20250908_p2_r4_col2': {
        "label": '12',
        "predicted": '1?',
        "confidences": [0.361, 0.065],
    },
    'gm_d_20250908_p2_r4_col3': {
        "label": '9.71',
        "predicted": '?.71',
        "confidences": [0.011, 0.194, 0.612],
    },
    'gm_d_20250908_p2_r4_col4': {
        "label": '11.05',
        "predicted": '11.??',
        "confidences": [0.361, 0.361, 0.043, 0.015],
    },
    'gm_d_20250930_p1_r0_col1': {
        "label": '42.3',
        "predicted": '42.?',
        "confidences": [0.38, 0.284, 0.022],
    },
    'gm_d_20250930_p1_r0_col2': {
        "label": '37.98',
        "predicted": '37.?8',
        "confidences": [0.452, 0.427, 0.067, 0.307],
    },
    'gm_d_20250930_p1_r0_col3': {
        "label": '32.37',
        "predicted": '32.37',
        "confidences": [0.331, 0.304, 0.331, 0.239],
    },
    'gm_d_20250930_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'gm_d_20250930_p1_r1_col1': {
        "label": '36.71',
        "predicted": '??.71',
        "confidences": [0.049, 0.003, 0.613, 0.96],
    },
    'gm_d_20250930_p1_r1_col2': {
        "label": '26.13',
        "predicted": '23.13',
        "confidences": [0.339, 0.18, 0.601, 0.24],
    },
    'gm_d_20250930_p1_r1_col3': {
        "label": '11.61',
        "predicted": '11.?1',
        "confidences": [0.768, 0.768, 0.044, 0.768],
    },
    'gm_d_20250930_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'gm_d_20250930_p1_r2_col1': {
        "label": '15.57',
        "predicted": '1?.?7',
        "confidences": [0.96, 0.091, 0.091, 0.306],
    },
    'gm_d_20250930_p1_r2_col2': {
        "label": '13.94',
        "predicted": '13.??',
        "confidences": [0.235, 0.304, 0.065, 0.021],
    },
    'gm_d_20250930_p1_r2_col3': {
        "label": '13.22',
        "predicted": '13.22',
        "confidences": [0.415, 0.317, 0.423, 0.423],
    },
    'gm_d_20250930_p1_r2_col4': {
        "label": '12.99',
        "predicted": '12.??',
        "confidences": [0.84, 0.311, 0.047, 0.047],
    },
    'gm_d_20250930_p1_r3_col1': {
        "label": '2.93',
        "predicted": '2.??',
        "confidences": [0.404, 0.084, 0.074],
    },
    'gm_d_20250930_p1_r3_col2': {
        "label": '9.41',
        "predicted": '?.41',
        "confidences": [0.033, 0.213, 0.817],
    },
    'gm_d_20250930_p1_r3_col3': {
        "label": '13.81',
        "predicted": '13.81',
        "confidences": [1.313, 0.54, 0.309, 1.313],
    },
    'gm_d_20250930_p1_r3_col4': {
        "label": '84.6',
        "predicted": '8?.?',
        "confidences": [0.333, 0.004, 0.13],
    },
    'gm_d_20250930_p1_r4_col1': {
        "label": '2.49',
        "predicted": '2.4?',
        "confidences": [0.343, 0.389, 0.055],
    },
    'gm_d_20250930_p1_r4_col2': {
        "label": '12.54',
        "predicted": '1?.5?',
        "confidences": [0.601, 0.058, 0.486, 0.096],
    },
    'gm_d_20250930_p1_r4_col3': {
        "label": '28.99',
        "predicted": '?8.??',
        "confidences": [0.139, 0.154, 0.014, 0.014],
    },
    'gm_d_20250930_p1_r4_col4': {
        "label": '2.41',
        "predicted": '?.41',
        "confidences": [0.032, 0.258, 0.531],
    },
    'gm_d_20250930_p2_r0_col1': {
        "label": '42.01',
        "predicted": '42.?1',
        "confidences": [0.38, 0.284, 0.147, 0.644],
    },
    'gm_d_20250930_p2_r0_col2': {
        "label": '23.84',
        "predicted": '23.84',
        "confidences": [0.25, 0.368, 0.264, 0.178],
    },
    'gm_d_20250930_p2_r0_col3': {
        "label": '20.56',
        "predicted": '20.5?',
        "confidences": [0.304, 0.215, 0.4, 0.138],
    },
    'gm_d_20250930_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'gm_d_20250930_p2_r1_col1': {
        "label": '25.92',
        "predicted": '25.?2',
        "confidences": [0.211, 0.157, 0.015, 0.211],
    },
    'gm_d_20250930_p2_r1_col2': {
        "label": '33.03',
        "predicted": '33.03',
        "confidences": [0.404, 0.404, 0.296, 0.404],
    },
    'gm_d_20250930_p2_r1_col3': {
        "label": '19.87',
        "predicted": '1?.?7',
        "confidences": [0.768, 0.02, 0.059, 0.279],
    },
    'gm_d_20250930_p2_r1_col4': {
        "label": '9.45',
        "predicted": '?.45',
        "confidences": [0.055, 0.253, 0.237],
    },
    'gm_d_20250930_p2_r2_col1': {
        "label": '15.12',
        "predicted": '1?.12',
        "confidences": [0.96, 0.091, 0.96, 0.265],
    },
    'gm_d_20250930_p2_r2_col2': {
        "label": '11.8',
        "predicted": '11.8',
        "confidences": [0.173, 0.173, 0.248],
    },
    'gm_d_20250930_p2_r2_col3': {
        "label": '36.43',
        "predicted": '3?.?3',
        "confidences": [0.209, 0.013, 0.002, 0.209],
    },
    'gm_d_20250930_p2_r2_col4': {
        "label": '8.81',
        "predicted": '8.81',
        "confidences": [0.267, 0.267, 0.84],
    },
    'gm_d_20250930_p2_r3_col1': {
        "label": '14.82',
        "predicted": '14.82',
        "confidences": [0.302, 0.398, 0.265, 0.404],
    },
    'gm_d_20250930_p2_r3_col2': {
        "label": '20.71',
        "predicted": '20.71',
        "confidences": [0.476, 0.272, 0.62, 0.425],
    },
    'gm_d_20250930_p2_r3_col3': {
        "label": '11.44',
        "predicted": '11.??',
        "confidences": [1.313, 1.313, 0.009, 0.009],
    },
    'gm_d_20250930_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.231],
    },
    'gm_d_20250930_p2_r4_col1': {
        "label": '2.13',
        "predicted": '2.1?',
        "confidences": [0.343, 0.949, 0.073],
    },
    'gm_d_20250930_p2_r4_col2': {
        "label": '10.62',
        "predicted": '?0.??',
        "confidences": [0.125, 0.297, 0.069, 0.021],
    },
    'gm_d_20250930_p2_r4_col3': {
        "label": '11.7',
        "predicted": '11.7',
        "confidences": [0.933, 0.933, 0.373],
    },
    'gm_d_20250930_p2_r4_col4': {
        "label": '81.74',
        "predicted": '81.74',
        "confidences": [0.326, 0.531, 0.743, 0.244],
    },
    'gm_d_20251023_p1_r0_col1': {
        "label": '58.07',
        "predicted": '??.??',
        "confidences": [0.073, 0.011, 0.147, 0.057],
    },
    'gm_d_20251023_p1_r0_col2': {
        "label": '27.29',
        "predicted": '27.2?',
        "confidences": [0.236, 0.427, 0.236, 0.067],
    },
    'gm_d_20251023_p1_r0_col3': {
        "label": '39.22',
        "predicted": '3?.22',
        "confidences": [0.331, 0.107, 0.304, 0.304],
    },
    'gm_d_20251023_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'gm_d_20251023_p1_r1_col1': {
        "label": '27.84',
        "predicted": '27.?4',
        "confidences": [0.211, 0.613, 0.102, 0.232],
    },
    'gm_d_20251023_p1_r1_col2': {
        "label": '37.42',
        "predicted": '37.42',
        "confidences": [0.24, 0.368, 0.151, 0.339],
    },
    'gm_d_20251023_p1_r1_col3': {
        "label": '10.42',
        "predicted": '10.42',
        "confidences": [0.768, 0.194, 0.34, 0.234],
    },
    'gm_d_20251023_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'gm_d_20251023_p1_r2_col1': {
        "label": '9.68',
        "predicted": '?.?8',
        "confidences": [0.008, 0.061, 0.266],
    },
    'gm_d_20251023_p1_r2_col2': {
        "label": '16.01',
        "predicted": '1?.01',
        "confidences": [0.235, 0.024, 0.315, 0.235],
    },
    'gm_d_20251023_p1_r2_col3': {
        "label": '9.96',
        "predicted": '?.??',
        "confidences": [0.022, 0.022, 0.042],
    },
    'gm_d_20251023_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.182],
    },
    'gm_d_20251023_p1_r3_col1': {
        "label": '2.46',
        "predicted": '2.4?',
        "confidences": [0.404, 0.398, 0.036],
    },
    'gm_d_20251023_p1_r3_col2': {
        "label": '6.86',
        "predicted": '?.??',
        "confidences": [0.047, 0.146, 0.047],
    },
    'gm_d_20251023_p1_r3_col3': {
        "label": '12.74',
        "predicted": '12.7?',
        "confidences": [1.313, 0.256, 0.425, 0.01],
    },
    'gm_d_20251023_p1_r3_col4': {
        "label": '91.56',
        "predicted": '?1.5?',
        "confidences": [0.041, 1.309, 0.412, 0.13],
    },
    'gm_d_20251023_p1_r4_col1': {
        "label": '1.95',
        "predicted": '1.??',
        "confidences": [0.949, 0.055, 0.011],
    },
    'gm_d_20251023_p1_r4_col2': {
        "label": '12.42',
        "predicted": '1?.??',
        "confidences": [0.601, 0.058, 0.096, 0.058],
    },
    'gm_d_20251023_p1_r4_col3': {
        "label": '27.66',
        "predicted": '?7.??',
        "confidences": [0.139, 0.373, 0.063, 0.063],
    },
    'gm_d_20251023_p1_r4_col4': {
        "label": '8.44',
        "predicted": '8.44',
        "confidences": [0.35, 0.258, 0.258],
    },
    'gm_d_20251023_p2_r0_col1': {
        "label": '44.53',
        "predicted": '44.??',
        "confidences": [0.38, 0.38, 0.073, 0.022],
    },
    'gm_d_20251023_p2_r0_col2': {
        "label": '19.25',
        "predicted": '1?.25',
        "confidences": [0.204, 0.069, 0.25, 0.334],
    },
    'gm_d_20251023_p2_r0_col3': {
        "label": '33.47',
        "predicted": '33.47',
        "confidences": [0.232, 0.232, 0.243, 0.239],
    },
    'gm_d_20251023_p2_r0_col4': {
        "label": '2.46',
        "predicted": '2.??',
        "confidences": [0.395, 0.136, 0.003],
    },
    'gm_d_20251023_p2_r1_col1': {
        "label": '28.47',
        "predicted": '2?.47',
        "confidences": [0.211, 0.102, 0.232, 0.613],
    },
    'gm_d_20251023_p2_r1_col2': {
        "label": '24.74',
        "predicted": '24.74',
        "confidences": [0.452, 0.151, 0.368, 0.151],
    },
    'gm_d_20251023_p2_r1_col3': {
        "label": '24.42',
        "predicted": '2?.?2',
        "confidences": [0.234, 0.131, 0.131, 0.234],
    },
    'gm_d_20251023_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'gm_d_20251023_p2_r2_col1': {
        "label": '15.41',
        "predicted": '1?.?1',
        "confidences": [0.96, 0.091, 0.036, 0.96],
    },
    'gm_d_20251023_p2_r2_col2': {
        "label": '33.02',
        "predicted": '33.02',
        "confidences": [0.18, 0.18, 0.317, 0.343],
    },
    'gm_d_20251023_p2_r2_col3': {
        "label": '15.91',
        "predicted": '15.?1',
        "confidences": [0.415, 0.185, 0.042, 0.415],
    },
    'gm_d_20251023_p2_r2_col4': {
        "label": '6.67',
        "predicted": '?.??',
        "confidences": [0.077, 0.077, 0.102],
    },
    'gm_d_20251023_p2_r3_col1': {
        "label": '10.02',
        "predicted": '1?.?2',
        "confidences": [0.302, 0.02, 0.02, 0.404],
    },
    'gm_d_20251023_p2_r3_col2': {
        "label": '12.14',
        "predicted": '12.14',
        "confidences": [0.425, 0.476, 0.425, 0.213],
    },
    'gm_d_20251023_p2_r3_col3': {
        "label": '12.41',
        "predicted": '12.?1',
        "confidences": [1.313, 0.256, 0.009, 1.313],
    },
    'gm_d_20251023_p2_r3_col4': {
        "label": '1.73',
        "predicted": '1.73',
        "confidences": [1.309, 0.617, 0.154],
    },
    'gm_d_20251023_p2_r4_col1': {
        "label": '1.57',
        "predicted": '1.?7',
        "confidences": [0.949, 0.011, 0.279],
    },
    'gm_d_20251023_p2_r4_col2': {
        "label": '10.85',
        "predicted": '?0.?5',
        "confidences": [0.125, 0.297, 0.038, 0.766],
    },
    'gm_d_20251023_p2_r4_col3': {
        "label": '13.79',
        "predicted": '13.7?',
        "confidences": [0.933, 0.218, 0.373, 0.049],
    },
    'gm_d_20251023_p2_r4_col4': {
        "label": '89.14',
        "predicted": '8?.14',
        "confidences": [0.326, 0.072, 0.531, 0.244],
    },
    'gm_d_20260111_p1_r0_col1': {
        "label": '41.83',
        "predicted": '41.??',
        "confidences": [0.38, 0.644, 0.011, 0.022],
    },
    'gm_d_20260111_p1_r0_col2': {
        "label": '17.84',
        "predicted": '17.84',
        "confidences": [0.732, 0.427, 0.307, 0.178],
    },
    'gm_d_20260111_p1_r0_col3': {
        "label": '19.89',
        "predicted": '1?.8?',
        "confidences": [1.095, 0.107, 0.301, 0.107],
    },
    'gm_d_20260111_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'gm_d_20260111_p1_r1_col1': {
        "label": '25.85',
        "predicted": '25.?5',
        "confidences": [0.211, 0.157, 0.102, 0.157],
    },
    'gm_d_20260111_p1_r1_col2': {
        "label": '26.02',
        "predicted": '23.02',
        "confidences": [0.339, 0.18, 0.296, 0.339],
    },
    'gm_d_20260111_p1_r1_col3': {
        "label": '20.76',
        "predicted": '20.7?',
        "confidences": [0.234, 0.194, 0.546, 0.044],
    },
    'gm_d_20260111_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'gm_d_20260111_p1_r2_col1': {
        "label": '23.4',
        "predicted": '2?.?',
        "confidences": [0.265, 0.044, 0.067],
    },
    'gm_d_20260111_p1_r2_col2': {
        "label": '30.99',
        "predicted": '30.??',
        "confidences": [0.304, 0.317, 0.065, 0.028],
    },
    'gm_d_20260111_p1_r2_col3': {
        "label": '16.22',
        "predicted": '1?.22',
        "confidences": [0.415, 0.013, 0.423, 0.423],
    },
    'gm_d_20260111_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.182],
    },
    'gm_d_20260111_p1_r3_col1': {
        "label": '6.94',
        "predicted": '?.?4',
        "confidences": [0.036, 0.084, 0.398],
    },
    'gm_d_20260111_p1_r3_col2': {
        "label": '17.08',
        "predicted": '17.0?',
        "confidences": [0.817, 0.62, 0.264, 0.146],
    },
    'gm_d_20260111_p1_r3_col3': {
        "label": '23.55',
        "predicted": '23.55',
        "confidences": [0.256, 0.54, 0.237, 0.237],
    },
    'gm_d_20260111_p1_r3_col4': {
        "label": '18.13',
        "predicted": '18.13',
        "confidences": [1.309, 0.333, 1.309, 0.502],
    },
    'gm_d_20260111_p1_r4_col1': {
        "label": '1.98',
        "predicted": '1.??',
        "confidences": [0.949, 0.055, 0.095],
    },
    'gm_d_20260111_p1_r4_col2': {
        "label": '8.07',
        "predicted": '?.07',
        "confidences": [0.038, 0.297, 0.385],
    },
    'gm_d_20260111_p1_r4_col3': {
        "label": '19.58',
        "predicted": '1?.58',
        "confidences": [0.933, 0.014, 0.445, 0.154],
    },
    'gm_d_20260111_p1_r4_col4': {
        "label": '81.87',
        "predicted": '81.?7',
        "confidences": [0.35, 0.531, 0.124, 0.532],
    },
    'gm_d_20260111_p2_r0_col1': {
        "label": '37.21',
        "predicted": '??.21',
        "confidences": [0.022, 0.057, 0.284, 0.644],
    },
    'gm_d_20260111_p2_r0_col2': {
        "label": '51.71',
        "predicted": '51.71',
        "confidences": [0.334, 0.204, 0.427, 0.204],
    },
    'gm_d_20260111_p2_r0_col3': {
        "label": '17.94',
        "predicted": '17.?4',
        "confidences": [1.095, 0.239, 0.107, 0.243],
    },
    'gm_d_20260111_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'gm_d_20260111_p2_r1_col1': {
        "label": '36.83',
        "predicted": '??.??',
        "confidences": [0.049, 0.003, 0.102, 0.049],
    },
    'gm_d_20260111_p2_r1_col2': {
        "label": '32.15',
        "predicted": '32.15',
        "confidences": [0.404, 0.47, 0.507, 0.432],
    },
    'gm_d_20260111_p2_r1_col3': {
        "label": '16.5',
        "predicted": '1?.5',
        "confidences": [0.768, 0.044, 0.274],
    },
    'gm_d_20260111_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'gm_d_20260111_p2_r2_col1': {
        "label": '13',
        "predicted": '1?',
        "confidences": [0.96, 0.044],
    },
    'gm_d_20260111_p2_r2_col2': {
        "label": '6.44',
        "predicted": '?.44',
        "confidences": [0.05, 0.222, 0.222],
    },
    'gm_d_20260111_p2_r2_col3': {
        "label": '38.56',
        "predicted": '38.5?',
        "confidences": [0.209, 0.285, 0.251, 0.013],
    },
    'gm_d_20260111_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.161],
    },
    'gm_d_20260111_p2_r3_col1': {
        "label": '11.41',
        "predicted": '11.41',
        "confidences": [0.302, 0.302, 0.398, 0.302],
    },
    'gm_d_20260111_p2_r3_col2': {
        "label": '6.53',
        "predicted": '?.53',
        "confidences": [0.021, 0.391, 0.192],
    },
    'gm_d_20260111_p2_r3_col3': {
        "label": '8.56',
        "predicted": '8.5?',
        "confidences": [0.309, 0.237, 0.051],
    },
    'gm_d_20260111_p2_r3_col4': {
        "label": '67.95',
        "predicted": '?7.?5',
        "confidences": [0.018, 0.617, 0.002, 0.249],
    },
    'gm_d_20260111_p2_r4_col1': {
        "label": '1.55',
        "predicted": '1.??',
        "confidences": [0.949, 0.011, 0.011],
    },
    'gm_d_20260111_p2_r4_col2': {
        "label": '3.17',
        "predicted": '3.?7',
        "confidences": [0.195, 0.125, 0.385],
    },
    'gm_d_20260111_p2_r4_col3': {
        "label": '18.44',
        "predicted": '18.44',
        "confidences": [0.933, 0.238, 0.382, 0.382],
    },
    'gm_d_20260111_p2_r4_col4': {
        "label": '32.05',
        "predicted": '3?.05',
        "confidences": [0.276, 0.104, 0.178, 0.326],
    },
    'gm_d_20260202_p1_r0_col1': {
        "label": '32.23',
        "predicted": '?2.2?',
        "confidences": [0.022, 0.284, 0.284, 0.022],
    },
    'gm_d_20260202_p1_r0_col2': {
        "label": '23.03',
        "predicted": '23.03',
        "confidences": [0.236, 0.452, 0.265, 0.452],
    },
    'gm_d_20260202_p1_r0_col3': {
        "label": '20.49',
        "predicted": '20.4?',
        "confidences": [0.304, 0.215, 0.243, 0.107],
    },
    'gm_d_20260202_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'gm_d_20260202_p1_r1_col1': {
        "label": '31.62',
        "predicted": '?1.?2',
        "confidences": [0.049, 0.96, 0.003, 0.211],
    },
    'gm_d_20260202_p1_r1_col2': {
        "label": '19.04',
        "predicted": '1?.04',
        "confidences": [0.601, 0.115, 0.296, 0.151],
    },
    'gm_d_20260202_p1_r1_col3': {
        "label": '18.72',
        "predicted": '1?.72',
        "confidences": [0.768, 0.059, 0.546, 0.234],
    },
    'gm_d_20260202_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'gm_d_20260202_p1_r2_col1': {
        "label": '15.79',
        "predicted": '1?.7?',
        "confidences": [0.96, 0.091, 0.306, 0.069],
    },
    'gm_d_20260202_p1_r2_col2': {
        "label": '25.94',
        "predicted": '25.??',
        "confidences": [0.238, 0.23, 0.065, 0.021],
    },
    'gm_d_20260202_p1_r2_col3': {
        "label": '20.91',
        "predicted": '2?.?1',
        "confidences": [0.423, 0.007, 0.022, 0.415],
    },
    'gm_d_20260202_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.182],
    },
    'gm_d_20260202_p1_r3_col1': {
        "label": '10.66',
        "predicted": '1?.??',
        "confidences": [0.302, 0.02, 0.036, 0.036],
    },
    'gm_d_20260202_p1_r3_col2': {
        "label": '17.64',
        "predicted": '17.?4',
        "confidences": [0.817, 0.62, 0.047, 0.213],
    },
    'gm_d_20260202_p1_r3_col3': {
        "label": '19.83',
        "predicted": '1?.83',
        "confidences": [1.313, 0.071, 0.309, 0.54],
    },
    'gm_d_20260202_p1_r3_col4': {
        "label": '1.41',
        "predicted": '1.?1',
        "confidences": [1.309, 0.004, 1.309],
    },
    'gm_d_20260202_p1_r4_col1': {
        "label": '9.7',
        "predicted": '?.7',
        "confidences": [0.055, 0.279],
    },
    'gm_d_20260202_p1_r4_col2': {
        "label": '14.35',
        "predicted": '1?.35',
        "confidences": [0.601, 0.096, 0.195, 0.486],
    },
    'gm_d_20260202_p1_r4_col3': {
        "label": '20.05',
        "predicted": '??.?5',
        "confidences": [0.139, 0.006, 0.006, 0.445],
    },
    'gm_d_20260202_p1_r4_col4': {
        "label": '98.59',
        "predicted": '??.5?',
        "confidences": [0.025, 0.124, 0.326, 0.025],
    },
    'gm_d_20260202_p2_r0_col1': {
        "label": '46.17',
        "predicted": '4?.1?',
        "confidences": [0.38, 0.142, 0.644, 0.057],
    },
    'gm_d_20260202_p2_r0_col2': {
        "label": '11.81',
        "predicted": '11.81',
        "confidences": [0.204, 0.204, 0.264, 0.204],
    },
    'gm_d_20260202_p2_r0_col3': {
        "label": '26.45',
        "predicted": '2?.45',
        "confidences": [0.304, 0.138, 0.243, 0.4],
    },
    'gm_d_20260202_p2_r0_col4': {
        "label": '1.89',
        "predicted": '1.8?',
        "confidences": [0.823, 0.287, 0.022],
    },
    'gm_d_20260202_p2_r1_col1': {
        "label": '34.99',
        "predicted": '?4.??',
        "confidences": [0.049, 0.232, 0.015, 0.015],
    },
    'gm_d_20260202_p2_r1_col2': {
        "label": '33.92',
        "predicted": '33.?2',
        "confidences": [0.404, 0.404, 0.042, 0.452],
    },
    'gm_d_20260202_p2_r1_col3': {
        "label": '11.94',
        "predicted": '11.??',
        "confidences": [0.768, 0.768, 0.02, 0.131],
    },
    'gm_d_20260202_p2_r1_col4': {
        "label": '1.53',
        "predicted": '1.5?',
        "confidences": [0.768, 0.237, 0.098],
    },
    'gm_d_20260202_p2_r2_col1': {
        "label": '14.98',
        "predicted": '1?.?8',
        "confidences": [0.96, 0.036, 0.008, 0.266],
    },
    'gm_d_20260202_p2_r2_col2': {
        "label": '43.95',
        "predicted": '?3.?5',
        "confidences": [0.092, 0.18, 0.065, 0.23],
    },
    'gm_d_20260202_p2_r2_col3': {
        "label": '22.69',
        "predicted": '22.??',
        "confidences": [0.319, 0.319, 0.013, 0.042],
    },
    'gm_d_20260202_p2_r2_col4': {
        "label": '6.36',
        "predicted": '?.3?',
        "confidences": [0.077, 0.23, 0.077],
    },
    'gm_d_20260202_p2_r3_col1': {
        "label": '2.47',
        "predicted": '2.47',
        "confidences": [0.404, 0.398, 0.231],
    },
    'gm_d_20260202_p2_r3_col2': {
        "label": '5.57',
        "predicted": '5.57',
        "confidences": [0.391, 0.391, 0.62],
    },
    'gm_d_20260202_p2_r3_col3': {
        "label": '15.99',
        "predicted": '15.??',
        "confidences": [1.313, 0.237, 0.071, 0.071],
    },
    'gm_d_20260202_p2_r3_col4': {
        "label": '76.66',
        "predicted": '7?.??',
        "confidences": [0.617, 0.018, 0.018, 0.018],
    },
    'gm_d_20260202_p2_r4_col1': {
        "label": '1.39',
        "predicted": '1.??',
        "confidences": [0.949, 0.073, 0.055],
    },
    'gm_d_20260202_p2_r4_col2': {
        "label": '4.75',
        "predicted": '?.75',
        "confidences": [0.096, 0.385, 0.766],
    },
    'gm_d_20260202_p2_r4_col3': {
        "label": '22.93',
        "predicted": '??.?3',
        "confidences": [0.139, 0.139, 0.049, 0.218],
    },
    'gm_d_20260202_p2_r4_col4': {
        "label": '13.56',
        "predicted": '13.5?',
        "confidences": [0.531, 0.276, 0.326, 0.06],
    },
    'gm_d_20260316_p1_r0_col1': {
        "label": '83.19',
        "predicted": '??.1?',
        "confidences": [0.011, 0.022, 0.644, 0.132],
    },
    'gm_d_20260316_p1_r0_col2': {
        "label": '47.02',
        "predicted": '47.02',
        "confidences": [0.178, 0.427, 0.265, 0.236],
    },
    'gm_d_20260316_p1_r0_col3': {
        "label": '13.75',
        "predicted": '13.75',
        "confidences": [1.095, 0.331, 0.239, 0.4],
    },
    'gm_d_20260316_p1_r0_col4': {
        "label": '13.14',
        "predicted": '13.1?',
        "confidences": [0.823, 0.209, 0.823, 0.141],
    },
    'gm_d_20260316_p1_r1_col1': {
        "label": '5.92',
        "predicted": '5.?2',
        "confidences": [0.157, 0.015, 0.211],
    },
    'gm_d_20260316_p1_r1_col2': {
        "label": '19.21',
        "predicted": '1?.21',
        "confidences": [0.601, 0.115, 0.339, 0.601],
    },
    'gm_d_20260316_p1_r1_col3': {
        "label": '20.97',
        "predicted": '20.?7',
        "confidences": [0.234, 0.194, 0.02, 0.546],
    },
    'gm_d_20260316_p1_r1_col4': {
        "label": '19.97',
        "predicted": '1?.?7',
        "confidences": [0.768, 0.055, 0.055, 0.378],
    },
    'gm_d_20260316_p1_r2_col1': {
        "label": '4.3',
        "predicted": '?.?',
        "confidences": [0.036, 0.044],
    },
    'gm_d_20260316_p1_r2_col2': {
        "label": '15.89',
        "predicted": '15.8?',
        "confidences": [0.235, 0.23, 0.248, 0.028],
    },
    'gm_d_20260316_p1_r2_col3': {
        "label": '25.88',
        "predicted": '2?.88',
        "confidences": [0.423, 0.01, 0.259, 0.259],
    },
    'gm_d_20260316_p1_r2_col4': {
        "label": '4.99',
        "predicted": '4.??',
        "confidences": [0.201, 0.047, 0.047],
    },
    'gm_d_20260316_p1_r3_col1': {
        "label": '3.65',
        "predicted": '?.?5',
        "confidences": [0.074, 0.036, 0.218],
    },
    'gm_d_20260316_p1_r3_col2': {
        "label": '6.4',
        "predicted": '?.4',
        "confidences": [0.047, 0.213],
    },
    'gm_d_20260316_p1_r3_col3': {
        "label": '18.68',
        "predicted": '18.?8',
        "confidences": [1.313, 0.309, 0.072, 0.309],
    },
    'gm_d_20260316_p1_r3_col4': {
        "label": '49.19',
        "predicted": '??.1?',
        "confidences": [0.004, 0.041, 1.309, 0.041],
    },
    'gm_d_20260316_p1_r4_col1': {
        "label": '2.94',
        "predicted": '2.?4',
        "confidences": [0.343, 0.055, 0.389],
    },
    'gm_d_20260316_p1_r4_col2': {
        "label": '11.48',
        "predicted": '11.??',
        "confidences": [0.601, 0.677, 0.096, 0.147],
    },
    'gm_d_20260316_p1_r4_col3': {
        "label": '20.72',
        "predicted": '??.7?',
        "confidences": [0.139, 0.006, 0.373, 0.139],
    },
    'gm_d_20260316_p1_r4_col4': {
        "label": '12.71',
        "predicted": '1?.71',
        "confidences": [0.531, 0.032, 0.532, 0.531],
    },
    'gm_d_20260316_p2_r0_col1': {
        "label": '35.21',
        "predicted": '??.21',
        "confidences": [0.022, 0.073, 0.284, 0.644],
    },
    'gm_d_20260316_p2_r0_col2': {
        "label": '26.53',
        "predicted": '2?.53',
        "confidences": [0.25, 0.063, 0.334, 0.368],
    },
    'gm_d_20260316_p2_r0_col3': {
        "label": '21.79',
        "predicted": '21.7?',
        "confidences": [0.304, 1.095, 0.239, 0.107],
    },
    'gm_d_20260316_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'gm_d_20260316_p2_r1_col1': {
        "label": '33.28',
        "predicted": '??.2?',
        "confidences": [0.049, 0.049, 0.211, 0.102],
    },
    'gm_d_20260316_p2_r1_col2': {
        "label": '18.14',
        "predicted": '1?.14',
        "confidences": [0.507, 0.06, 0.507, 0.151],
    },
    'gm_d_20260316_p2_r1_col3': {
        "label": '20.52',
        "predicted": '20.52',
        "confidences": [0.234, 0.194, 0.274, 0.234],
    },
    'gm_d_20260316_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'gm_d_20260316_p2_r2_col1': {
        "label": '13.88',
        "predicted": '1?.88',
        "confidences": [0.96, 0.044, 0.266, 0.266],
    },
    'gm_d_20260316_p2_r2_col2': {
        "label": '25.06',
        "predicted": '25.0?',
        "confidences": [0.343, 0.23, 0.317, 0.114],
    },
    'gm_d_20260316_p2_r2_col3': {
        "label": '23.1',
        "predicted": '23.1',
        "confidences": [0.319, 0.209, 0.415],
    },
    'gm_d_20260316_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.161],
    },
    'gm_d_20260316_p2_r3_col1': {
        "label": '9.54',
        "predicted": '?.54',
        "confidences": [0.084, 0.218, 0.398],
    },
    'gm_d_20260316_p2_r3_col2': {
        "label": '17.23',
        "predicted": '17.23',
        "confidences": [0.425, 0.62, 0.476, 0.192],
    },
    'gm_d_20260316_p2_r3_col3': {
        "label": '16.99',
        "predicted": '1?.??',
        "confidences": [1.313, 0.051, 0.071, 0.071],
    },
    'gm_d_20260316_p2_r3_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [1.309, 0.231, 0.231],
    },
    'gm_d_20260316_p2_r4_col1': {
        "label": '8.09',
        "predicted": '?.0?',
        "confidences": [0.095, 0.261, 0.055],
    },
    'gm_d_20260316_p2_r4_col2': {
        "label": '13.04',
        "predicted": '?3.0?',
        "confidences": [0.125, 0.195, 0.297, 0.096],
    },
    'gm_d_20260316_p2_r4_col3': {
        "label": '17.6',
        "predicted": '17.?',
        "confidences": [0.933, 0.373, 0.063],
    },
    'gm_d_20260316_p2_r4_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.178],
    },
    'ib_d_20250928_p1_r0_col1': {
        "label": '58.52',
        "predicted": '??.?2',
        "confidences": [0.073, 0.011, 0.073, 0.284],
    },
    'ib_d_20250928_p1_r0_col2': {
        "label": '23.39',
        "predicted": '23.3?',
        "confidences": [0.236, 0.452, 0.452, 0.067],
    },
    'ib_d_20250928_p1_r0_col3': {
        "label": '11.84',
        "predicted": '11.84',
        "confidences": [1.095, 1.095, 0.301, 0.243],
    },
    'ib_d_20250928_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'ib_d_20250928_p1_r1_col1': {
        "label": '15.09',
        "predicted": '15.0?',
        "confidences": [0.96, 0.157, 0.169, 0.015],
    },
    'ib_d_20250928_p1_r1_col2': {
        "label": '24.13',
        "predicted": '24.13',
        "confidences": [0.339, 0.151, 0.601, 0.24],
    },
    'ib_d_20250928_p1_r1_col3': {
        "label": '33.6',
        "predicted": '33.?',
        "confidences": [0.293, 0.293, 0.044],
    },
    'ib_d_20250928_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20250928_p1_r2_col1': {
        "label": '14.97',
        "predicted": '1?.?7',
        "confidences": [0.96, 0.067, 0.069, 0.306],
    },
    'ib_d_20250928_p1_r2_col2': {
        "label": '33.87',
        "predicted": '33.8?',
        "confidences": [0.304, 0.304, 0.248, 0.142],
    },
    'ib_d_20250928_p1_r2_col3': {
        "label": '12.61',
        "predicted": '12.?1',
        "confidences": [0.415, 0.423, 0.013, 0.415],
    },
    'ib_d_20250928_p1_r2_col4': {
        "label": '1.32',
        "predicted": '1.?2',
        "confidences": [0.84, 0.1, 0.311],
    },
    'ib_d_20250928_p1_r3_col1': {
        "label": '9.22',
        "predicted": '?.22',
        "confidences": [0.084, 0.404, 0.404],
    },
    'ib_d_20250928_p1_r3_col2': {
        "label": '12.21',
        "predicted": '12.21',
        "confidences": [0.817, 0.333, 0.333, 0.817],
    },
    'ib_d_20250928_p1_r3_col3': {
        "label": '28.79',
        "predicted": '28.7?',
        "confidences": [0.256, 0.309, 0.425, 0.071],
    },
    'ib_d_20250928_p1_r3_col4': {
        "label": '3.5',
        "predicted": '3.5',
        "confidences": [0.502, 0.412],
    },
    'ib_d_20250928_p1_r4_col1': {
        "label": '2.2',
        "predicted": '2.2',
        "confidences": [0.343, 0.343],
    },
    'ib_d_20250928_p1_r4_col2': {
        "label": '6.4',
        "predicted": '?.?',
        "confidences": [0.069, 0.096],
    },
    'ib_d_20250928_p1_r4_col3': {
        "label": '13.16',
        "predicted": '13.1?',
        "confidences": [0.933, 0.256, 0.933, 0.063],
    },
    'ib_d_20250928_p1_r4_col4': {
        "label": '95.18',
        "predicted": '?5.1?',
        "confidences": [0.025, 0.326, 0.531, 0.124],
    },
    'ib_d_20250928_p2_r0_col1': {
        "label": '36.26',
        "predicted": '??.2?',
        "confidences": [0.022, 0.142, 0.284, 0.142],
    },
    'ib_d_20250928_p2_r0_col2': {
        "label": '34.58',
        "predicted": '34.58',
        "confidences": [0.487, 0.178, 0.334, 0.307],
    },
    'ib_d_20250928_p2_r0_col3': {
        "label": '19.7',
        "predicted": '1?.7',
        "confidences": [1.095, 0.107, 0.239],
    },
    'ib_d_20250928_p2_r0_col4': {
        "label": '100',
        "predicted": '1??',
        "confidences": [0.823, 0.133, 0.133],
    },
    'ib_d_20250928_p2_r1_col1': {
        "label": '29.6',
        "predicted": '2?.?',
        "confidences": [0.211, 0.015, 0.003],
    },
    'ib_d_20250928_p2_r1_col2': {
        "label": '18.74',
        "predicted": '1?.74',
        "confidences": [0.507, 0.06, 0.368, 0.151],
    },
    'ib_d_20250928_p2_r1_col3': {
        "label": '9.97',
        "predicted": '?.?7',
        "confidences": [0.02, 0.02, 0.279],
    },
    'ib_d_20250928_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20250928_p2_r2_col1': {
        "label": '21',
        "predicted": '21',
        "confidences": [0.265, 0.96],
    },
    'ib_d_20250928_p2_r2_col2': {
        "label": '25.59',
        "predicted": '25.5?',
        "confidences": [0.338, 0.215, 0.215, 0.065],
    },
    'ib_d_20250928_p2_r2_col3': {
        "label": '33.72',
        "predicted": '??.?2',
        "confidences": [0.134, 0.134, 0.126, 0.319],
    },
    'ib_d_20250928_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.161],
    },
    'ib_d_20250928_p2_r3_col1': {
        "label": '7.92',
        "predicted": '7.?2',
        "confidences": [0.231, 0.084, 0.404],
    },
    'ib_d_20250928_p2_r3_col2': {
        "label": '4.28',
        "predicted": '4.2?',
        "confidences": [0.213, 0.476, 0.091],
    },
    'ib_d_20250928_p2_r3_col3': {
        "label": '10.28',
        "predicted": '1?.28',
        "confidences": [1.313, 0.094, 0.256, 0.309],
    },
    'ib_d_20250928_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.231],
    },
    'ib_d_20250928_p2_r4_col1': {
        "label": '5.22',
        "predicted": '?.22',
        "confidences": [0.011, 0.343, 0.343],
    },
    'ib_d_20250928_p2_r4_col2': {
        "label": '16.81',
        "predicted": '??.??',
        "confidences": [0.125, 0.069, 0.038, 0.125],
    },
    'ib_d_20250928_p2_r4_col3': {
        "label": '26.33',
        "predicted": '??.33',
        "confidences": [0.139, 0.063, 0.218, 0.218],
    },
    'ib_d_20250928_p2_r4_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.178],
    },
    'ib_d_20251206_p1_r0_col1': {
        "label": '47.88',
        "predicted": '4?.??',
        "confidences": [0.38, 0.057, 0.011, 0.011],
    },
    'ib_d_20251206_p1_r0_col2': {
        "label": '38.94',
        "predicted": '38.?4',
        "confidences": [0.452, 0.307, 0.067, 0.178],
    },
    'ib_d_20251206_p1_r0_col3': {
        "label": '22',
        "predicted": '22',
        "confidences": [0.304, 0.304],
    },
    'ib_d_20251206_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'ib_d_20251206_p1_r1_col1': {
        "label": '40.95',
        "predicted": '40.?5',
        "confidences": [0.232, 0.169, 0.015, 0.157],
    },
    'ib_d_20251206_p1_r1_col2': {
        "label": '14.48',
        "predicted": '14.4?',
        "confidences": [0.601, 0.151, 0.151, 0.098],
    },
    'ib_d_20251206_p1_r1_col3': {
        "label": '30.87',
        "predicted": '30.?7',
        "confidences": [0.293, 0.194, 0.059, 0.546],
    },
    'ib_d_20251206_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20251206_p1_r2_col1': {
        "label": '7.31',
        "predicted": '7.?1',
        "confidences": [0.306, 0.044, 0.96],
    },
    'ib_d_20251206_p1_r2_col2': {
        "label": '36.61',
        "predicted": '3?.?1',
        "confidences": [0.304, 0.035, 0.035, 0.235],
    },
    'ib_d_20251206_p1_r2_col3': {
        "label": '21.76',
        "predicted": '21.??',
        "confidences": [0.319, 0.415, 0.126, 0.013],
    },
    'ib_d_20251206_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.176],
    },
    'ib_d_20251206_p1_r3_col1': {
        "label": '3.39',
        "predicted": '?.??',
        "confidences": [0.074, 0.074, 0.084],
    },
    'ib_d_20251206_p1_r3_col2': {
        "label": '5.74',
        "predicted": '5.74',
        "confidences": [0.391, 0.62, 0.213],
    },
    'ib_d_20251206_p1_r3_col3': {
        "label": '13.42',
        "predicted": '13.?2',
        "confidences": [1.313, 0.54, 0.009, 0.256],
    },
    'ib_d_20251206_p1_r3_col4': {
        "label": '44.58',
        "predicted": '??.58',
        "confidences": [0.093, 0.093, 0.249, 0.333],
    },
    'ib_d_20251206_p1_r4_col1': {
        "label": '0.47',
        "predicted": '0.47',
        "confidences": [0.261, 0.389, 0.279],
    },
    'ib_d_20251206_p1_r4_col2': {
        "label": '4.23',
        "predicted": '?.?3',
        "confidences": [0.096, 0.021, 0.195],
    },
    'ib_d_20251206_p1_r4_col3': {
        "label": '11.95',
        "predicted": '11.?5',
        "confidences": [0.933, 0.933, 0.049, 0.459],
    },
    'ib_d_20251206_p1_r4_col4': {
        "label": '55.42',
        "predicted": '55.4?',
        "confidences": [0.326, 0.326, 0.244, 0.104],
    },
    'ib_d_20251206_p2_r0_col1': {
        "label": '68.58',
        "predicted": '??.??',
        "confidences": [0.142, 0.011, 0.073, 0.011],
    },
    'ib_d_20251206_p2_r0_col2': {
        "label": '44.55',
        "predicted": '44.55',
        "confidences": [0.178, 0.178, 0.334, 0.334],
    },
    'ib_d_20251206_p2_r0_col3': {
        "label": '30.02',
        "predicted": '30.02',
        "confidences": [0.232, 0.215, 0.215, 0.304],
    },
    'ib_d_20251206_p2_r0_col4': {
        "label": '0.91',
        "predicted": '?.?1',
        "confidences": [0.133, 0.022, 0.823],
    },
    'ib_d_20251206_p2_r1_col1': {
        "label": '20.92',
        "predicted": '20.?2',
        "confidences": [0.211, 0.169, 0.015, 0.211],
    },
    'ib_d_20251206_p2_r1_col2': {
        "label": '16.29',
        "predicted": '1?.2?',
        "confidences": [0.507, 0.039, 0.452, 0.042],
    },
    'ib_d_20251206_p2_r1_col3': {
        "label": '15.07',
        "predicted": '15.07',
        "confidences": [0.768, 0.274, 0.194, 0.279],
    },
    'ib_d_20251206_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20251206_p2_r2_col1': {
        "label": '5.65',
        "predicted": '?.??',
        "confidences": [0.091, 0.061, 0.091],
    },
    'ib_d_20251206_p2_r2_col2': {
        "label": '15.7',
        "predicted": '15.?',
        "confidences": [0.173, 0.23, 0.142],
    },
    'ib_d_20251206_p2_r2_col3': {
        "label": '33.65',
        "predicted": '33.?5',
        "confidences": [0.209, 0.209, 0.013, 0.251],
    },
    'ib_d_20251206_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.161],
    },
    'ib_d_20251206_p2_r3_col1': {
        "label": '3.61',
        "predicted": '?.?1',
        "confidences": [0.074, 0.036, 0.302],
    },
    'ib_d_20251206_p2_r3_col2': {
        "label": '16.14',
        "predicted": '1?.14',
        "confidences": [0.425, 0.021, 0.425, 0.213],
    },
    'ib_d_20251206_p2_r3_col3': {
        "label": '8.56',
        "predicted": '8.5?',
        "confidences": [0.309, 0.237, 0.051],
    },
    'ib_d_20251206_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.231],
    },
    'ib_d_20251206_p2_r4_col1': {
        "label": '1.24',
        "predicted": '1.24',
        "confidences": [0.949, 0.343, 0.389],
    },
    'ib_d_20251206_p2_r4_col2': {
        "label": '7.32',
        "predicted": '7.3?',
        "confidences": [0.385, 0.195, 0.021],
    },
    'ib_d_20251206_p2_r4_col3': {
        "label": '12.7',
        "predicted": '1?.7',
        "confidences": [0.933, 0.139, 0.373],
    },
    'ib_d_20251206_p2_r4_col4': {
        "label": '99.09',
        "predicted": '??.0?',
        "confidences": [0.072, 0.072, 0.178, 0.072],
    },
    'ib_d_20260112_1_p1_r0_col1': {
        "label": '45.89',
        "predicted": '4?.??',
        "confidences": [0.38, 0.073, 0.011, 0.132],
    },
    'ib_d_20260112_1_p1_r0_col2': {
        "label": '51.81',
        "predicted": '51.81',
        "confidences": [0.334, 0.732, 0.307, 0.732],
    },
    'ib_d_20260112_1_p1_r0_col3': {
        "label": '19.71',
        "predicted": '1?.71',
        "confidences": [1.095, 0.107, 0.239, 1.095],
    },
    'ib_d_20260112_1_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'ib_d_20260112_1_p1_r1_col1': {
        "label": '35.18',
        "predicted": '?5.1?',
        "confidences": [0.049, 0.157, 0.96, 0.102],
    },
    'ib_d_20260112_1_p1_r1_col2': {
        "label": '12.22',
        "predicted": '12.22',
        "confidences": [0.601, 0.339, 0.339, 0.339],
    },
    'ib_d_20260112_1_p1_r1_col3': {
        "label": '33.67',
        "predicted": '33.?7',
        "confidences": [0.293, 0.293, 0.044, 0.546],
    },
    'ib_d_20260112_1_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20260112_1_p1_r2_col1': {
        "label": '9.77',
        "predicted": '?.77',
        "confidences": [0.008, 0.306, 0.306],
    },
    'ib_d_20260112_1_p1_r2_col2': {
        "label": '8.81',
        "predicted": '8.81',
        "confidences": [0.248, 0.248, 0.235],
    },
    'ib_d_20260112_1_p1_r2_col3': {
        "label": '22.18',
        "predicted": '22.18',
        "confidences": [0.423, 0.423, 0.415, 0.259],
    },
    'ib_d_20260112_1_p1_r2_col4': {
        "label": '5.31',
        "predicted": '5.?1',
        "confidences": [0.385, 0.1, 0.84],
    },
    'ib_d_20260112_1_p1_r3_col1': {
        "label": '6.34',
        "predicted": '?.?4',
        "confidences": [0.036, 0.074, 0.398],
    },
    'ib_d_20260112_1_p1_r3_col2': {
        "label": '8.98',
        "predicted": '?.??',
        "confidences": [0.061, 0.033, 0.061],
    },
    'ib_d_20260112_1_p1_r3_col3': {
        "label": '5.2',
        "predicted": '5.2',
        "confidences": [0.237, 0.256],
    },
    'ib_d_20260112_1_p1_r3_col4': {
        "label": '1.74',
        "predicted": '1.??',
        "confidences": [1.309, 0.144, 0.004],
    },
    'ib_d_20260112_1_p1_r4_col1': {
        "label": '2.82',
        "predicted": '2.?2',
        "confidences": [0.343, 0.095, 0.343],
    },
    'ib_d_20260112_1_p1_r4_col2': {
        "label": '18.18',
        "predicted": '1?.1?',
        "confidences": [0.601, 0.038, 0.677, 0.147],
    },
    'ib_d_20260112_1_p1_r4_col3': {
        "label": '19.24',
        "predicted": '1?.?4',
        "confidences": [0.933, 0.014, 0.139, 0.382],
    },
    'ib_d_20260112_1_p1_r4_col4': {
        "label": '92.95',
        "predicted": '??.?5',
        "confidences": [0.025, 0.032, 0.025, 0.172],
    },
    'ib_d_20260112_1_p2_r0_col1': {
        "label": '45.56',
        "predicted": '4?.??',
        "confidences": [0.38, 0.073, 0.073, 0.142],
    },
    'ib_d_20260112_1_p2_r0_col2': {
        "label": '51.78',
        "predicted": '51.78',
        "confidences": [0.334, 0.204, 0.427, 0.307],
    },
    'ib_d_20260112_1_p2_r0_col3': {
        "label": '18.41',
        "predicted": '18.41',
        "confidences": [1.095, 0.248, 0.243, 1.095],
    },
    'ib_d_20260112_1_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'ib_d_20260112_1_p2_r1_col1': {
        "label": '36.2',
        "predicted": '??.2',
        "confidences": [0.049, 0.003, 0.211],
    },
    'ib_d_20260112_1_p2_r1_col2': {
        "label": '12.38',
        "predicted": '12.3?',
        "confidences": [0.507, 0.47, 0.404, 0.06],
    },
    'ib_d_20260112_1_p2_r1_col3': {
        "label": '40.56',
        "predicted": '?0.5?',
        "confidences": [0.131, 0.194, 0.274, 0.044],
    },
    'ib_d_20260112_1_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20260112_1_p2_r2_col1': {
        "label": '9.3',
        "predicted": '?.?',
        "confidences": [0.069, 0.044],
    },
    'ib_d_20260112_1_p2_r2_col2': {
        "label": '8.97',
        "predicted": '8.?7',
        "confidences": [0.248, 0.065, 0.154],
    },
    'ib_d_20260112_1_p2_r2_col3': {
        "label": '20.77',
        "predicted": '20.??',
        "confidences": [0.319, 0.15, 0.096, 0.096],
    },
    'ib_d_20260112_1_p2_r2_col4': {
        "label": '5.06',
        "predicted": '5.0?',
        "confidences": [0.203, 0.161, 0.077],
    },
    'ib_d_20260112_1_p2_r3_col1': {
        "label": '6.2',
        "predicted": '?.2',
        "confidences": [0.036, 0.404],
    },
    'ib_d_20260112_1_p2_r3_col2': {
        "label": '8.89',
        "predicted": '?.??',
        "confidences": [0.091, 0.091, 0.033],
    },
    'ib_d_20260112_1_p2_r3_col3': {
        "label": '4.61',
        "predicted": '?.?1',
        "confidences": [0.009, 0.051, 1.313],
    },
    'ib_d_20260112_1_p2_r3_col4': {
        "label": '1.43',
        "predicted": '1.?3',
        "confidences": [1.309, 0.093, 0.154],
    },
    'ib_d_20260112_1_p2_r4_col1': {
        "label": '2.74',
        "predicted": '2.74',
        "confidences": [0.343, 0.279, 0.389],
    },
    'ib_d_20260112_1_p2_r4_col2': {
        "label": '17.98',
        "predicted": '?7.??',
        "confidences": [0.125, 0.385, 0.122, 0.038],
    },
    'ib_d_20260112_1_p2_r4_col3': {
        "label": '15.65',
        "predicted": '15.?5',
        "confidences": [0.933, 0.459, 0.063, 0.459],
    },
    'ib_d_20260112_1_p2_r4_col4': {
        "label": '93.51',
        "predicted": '?3.51',
        "confidences": [0.072, 0.276, 0.326, 0.531],
    },
    'ib_d_20260114_p1_r0_col1': {
        "label": '40.83',
        "predicted": '4?.??',
        "confidences": [0.38, 0.147, 0.011, 0.022],
    },
    'ib_d_20260114_p1_r0_col2': {
        "label": '34.28',
        "predicted": '34.28',
        "confidences": [0.452, 0.178, 0.236, 0.307],
    },
    'ib_d_20260114_p1_r0_col3': {
        "label": '17.47',
        "predicted": '17.47',
        "confidences": [1.095, 0.239, 0.243, 0.239],
    },
    'ib_d_20260114_p1_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'ib_d_20260114_p1_r1_col1': {
        "label": '36.11',
        "predicted": '??.11',
        "confidences": [0.049, 0.003, 0.96, 0.96],
    },
    'ib_d_20260114_p1_r1_col2': {
        "label": '8.18',
        "predicted": '?.1?',
        "confidences": [0.06, 0.601, 0.061],
    },
    'ib_d_20260114_p1_r1_col3': {
        "label": '25.64',
        "predicted": '25.?4',
        "confidences": [0.234, 0.247, 0.044, 0.34],
    },
    'ib_d_20260114_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20260114_p1_r2_col1': {
        "label": '16.69',
        "predicted": '1?.??',
        "confidences": [0.96, 0.061, 0.061, 0.008],
    },
    'ib_d_20260114_p1_r2_col2': {
        "label": '46.19',
        "predicted": '??.1?',
        "confidences": [0.092, 0.024, 0.235, 0.028],
    },
    'ib_d_20260114_p1_r2_col3': {
        "label": '32.7',
        "predicted": '32.?',
        "confidences": [0.318, 0.423, 0.096],
    },
    'ib_d_20260114_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.182],
    },
    'ib_d_20260114_p1_r3_col1': {
        "label": '5.3',
        "predicted": '5.?',
        "confidences": [0.218, 0.074],
    },
    'ib_d_20260114_p1_r3_col2': {
        "label": '5.79',
        "predicted": '5.7?',
        "confidences": [0.249, 0.62, 0.033],
    },
    'ib_d_20260114_p1_r3_col3': {
        "label": '4.28',
        "predicted": '?.28',
        "confidences": [0.009, 0.256, 0.276],
    },
    'ib_d_20260114_p1_r3_col4': {
        "label": '2.31',
        "predicted": '2.31',
        "confidences": [0.518, 0.502, 1.309],
    },
    'ib_d_20260114_p1_r4_col1': {
        "label": '1.07',
        "predicted": '1.07',
        "confidences": [0.949, 0.261, 0.279],
    },
    'ib_d_20260114_p1_r4_col2': {
        "label": '5.56',
        "predicted": '5.5?',
        "confidences": [0.486, 0.486, 0.069],
    },
    'ib_d_20260114_p1_r4_col3': {
        "label": '19.91',
        "predicted": '1?.?1',
        "confidences": [0.933, 0.014, 0.014, 0.933],
    },
    'ib_d_20260114_p1_r4_col4': {
        "label": '97.69',
        "predicted": '?7.??',
        "confidences": [0.025, 0.532, 0.06, 0.025],
    },
    'ib_d_20260114_p2_r0_col1': {
        "label": '63.99',
        "predicted": '??.??',
        "confidences": [0.142, 0.022, 0.132, 0.132],
    },
    'ib_d_20260114_p2_r0_col2': {
        "label": '44.15',
        "predicted": '44.15',
        "confidences": [0.178, 0.178, 0.204, 0.334],
    },
    'ib_d_20260114_p2_r0_col3': {
        "label": '15.46',
        "predicted": '15.4?',
        "confidences": [1.095, 0.4, 0.243, 0.138],
    },
    'ib_d_20260114_p2_r0_col4': {
        "label": '0',
        "predicted": '?',
        "confidences": [0.133],
    },
    'ib_d_20260114_p2_r1_col1': {
        "label": '18.68',
        "predicted": '1?.??',
        "confidences": [0.96, 0.102, 0.003, 0.102],
    },
    'ib_d_20260114_p2_r1_col2': {
        "label": '12.89',
        "predicted": '12.??',
        "confidences": [0.507, 0.47, 0.06, 0.042],
    },
    'ib_d_20260114_p2_r1_col3': {
        "label": '17.81',
        "predicted": '17.?1',
        "confidences": [0.768, 0.279, 0.059, 0.768],
    },
    'ib_d_20260114_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.302],
    },
    'ib_d_20260114_p2_r2_col1': {
        "label": '9.27',
        "predicted": '?.27',
        "confidences": [0.069, 0.265, 0.306],
    },
    'ib_d_20260114_p2_r2_col2': {
        "label": '21.97',
        "predicted": '21.?7',
        "confidences": [0.343, 0.173, 0.065, 0.154],
    },
    'ib_d_20260114_p2_r2_col3': {
        "label": '17.66',
        "predicted": '1?.??',
        "confidences": [0.415, 0.096, 0.013, 0.013],
    },
    'ib_d_20260114_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.161],
    },
    'ib_d_20260114_p2_r3_col1': {
        "label": '7.31',
        "predicted": '7.?1',
        "confidences": [0.231, 0.074, 0.302],
    },
    'ib_d_20260114_p2_r3_col2': {
        "label": '16.54',
        "predicted": '1?.54',
        "confidences": [0.425, 0.021, 0.391, 0.213],
    },
    'ib_d_20260114_p2_r3_col3': {
        "label": '33.91',
        "predicted": '33.?1',
        "confidences": [0.54, 0.54, 0.071, 1.313],
    },
    'ib_d_20260114_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.231],
    },
    'ib_d_20260114_p2_r4_col1': {
        "label": '0.75',
        "predicted": '0.7?',
        "confidences": [0.261, 0.279, 0.011],
    },
    'ib_d_20260114_p2_r4_col2': {
        "label": '4.45',
        "predicted": '?.?5',
        "confidences": [0.096, 0.096, 0.766],
    },
    'ib_d_20260114_p2_r4_col3': {
        "label": '15.16',
        "predicted": '15.1?',
        "confidences": [0.933, 0.459, 0.933, 0.063],
    },
    'ib_d_20260114_p2_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [0.531, 0.178, 0.178],
    },
}
