# -*- coding: utf-8 -*-
"""
pct_fft_ground_truth.py -- auto-generated by debugs/pct_fft_predict.py

Generated: 2026-07-04T12:49:04  (run start)

Living document, not a final oracle: FFT+Gabor nearest-centroid
predictions for every pct cell in the held-out image set (the images
listed in tests/inputs/daily/stat_data.py), gated by a distance-margin
confidence threshold.  '?' marks digits the classifier was not
confident enough to call -- honesty over false precision (see
docs/known_issues.txt Sec14, Sec15).  "label" is the existing
full-pipeline (blob + Tesseract fallback) result, used as the working
reference until spot-checked by a human.

Centroids were built from 71 single/*.png training images,
ALL of which exclude the held-out set below -- this is a genuine
generalization estimate, not train==test separability
(docs/action_items.txt #1).

Regenerate: python debugs/pct_fft_predict.py
"""

CONF_MIN = 0.15

DATA = {
    'fb_d_20250928_p1_r0_col1': {
        "label": '42.74',
        "predicted": '42.?4',
        "confidences": [0.645, 0.57, 0.064, 0.645],
    },
    'fb_d_20250928_p1_r0_col2': {
        "label": '22.87',
        "predicted": '22.87',
        "confidences": [0.506, 0.506, 0.462, 0.556],
    },
    'fb_d_20250928_p1_r0_col3': {
        "label": '17.32',
        "predicted": '17.32',
        "confidences": [1.721, 0.394, 0.329, 0.553],
    },
    'fb_d_20250928_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20250928_p1_r1_col1': {
        "label": '23.73',
        "predicted": '2?.7?',
        "confidences": [0.576, 0.042, 0.654, 0.042],
    },
    'fb_d_20250928_p1_r1_col2': {
        "label": '33.93',
        "predicted": '33.?3',
        "confidences": [0.29, 0.439, 0.041, 0.29],
    },
    'fb_d_20250928_p1_r1_col3': {
        "label": '10.88',
        "predicted": '10.??',
        "confidences": [2.185, 0.287, 0.007, 0.007],
    },
    'fb_d_20250928_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20250928_p1_r2_col1': {
        "label": '18.43',
        "predicted": '18.4?',
        "confidences": [2.821, 0.372, 0.251, 0.031],
    },
    'fb_d_20250928_p1_r2_col2': {
        "label": '24.22',
        "predicted": '24.22',
        "confidences": [0.437, 0.268, 0.437, 0.437],
    },
    'fb_d_20250928_p1_r2_col3': {
        "label": '27.83',
        "predicted": '2?.83',
        "confidences": [0.717, 0.148, 0.34, 0.368],
    },
    'fb_d_20250928_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.5],
    },
    'fb_d_20250928_p1_r3_col1': {
        "label": '12.06',
        "predicted": '12.??',
        "confidences": [1.004, 0.695, 0.028, 0.056],
    },
    'fb_d_20250928_p1_r3_col2': {
        "label": '11.81',
        "predicted": '11.81',
        "confidences": [1.749, 1.749, 0.471, 1.749],
    },
    'fb_d_20250928_p1_r3_col3': {
        "label": '31.05',
        "predicted": '31.05',
        "confidences": [0.605, 1.721, 0.396, 0.32],
    },
    'fb_d_20250928_p1_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.644],
    },
    'fb_d_20250928_p1_r4_col1': {
        "label": '3.04',
        "predicted": '?.04',
        "confidences": [0.049, 0.274, 0.559],
    },
    'fb_d_20250928_p1_r4_col2': {
        "label": '7.17',
        "predicted": '7.17',
        "confidences": [0.471, 1.893, 0.471],
    },
    'fb_d_20250928_p1_r4_col3': {
        "label": '12.92',
        "predicted": '12.?2',
        "confidences": [2.597, 0.385, 0.083, 0.385],
    },
    'fb_d_20250928_p1_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [2.189, 0.541, 0.541],
    },
    'fb_d_20250928_p2_r0_col1': {
        "label": '48.02',
        "predicted": '4?.?2',
        "confidences": [0.645, 0.135, 0.053, 0.57],
    },
    'fb_d_20250928_p2_r0_col2': {
        "label": '33.18',
        "predicted": '33.18',
        "confidences": [0.536, 0.416, 0.815, 0.462],
    },
    'fb_d_20250928_p2_r0_col3': {
        "label": '34.79',
        "predicted": '34.79',
        "confidences": [0.266, 0.463, 0.394, 0.156],
    },
    'fb_d_20250928_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20250928_p2_r1_col1': {
        "label": '22.67',
        "predicted": '22.?7',
        "confidences": [0.576, 0.576, 0.016, 0.654],
    },
    'fb_d_20250928_p2_r1_col2': {
        "label": '19.09',
        "predicted": '1?.0?',
        "confidences": [1.173, 0.091, 0.391, 0.091],
    },
    'fb_d_20250928_p2_r1_col3': {
        "label": '10.36',
        "predicted": '10.3?',
        "confidences": [2.185, 0.287, 0.312, 0.101],
    },
    'fb_d_20250928_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20250928_p2_r2_col1': {
        "label": '21.9',
        "predicted": '21.?',
        "confidences": [0.544, 2.821, 0.02],
    },
    'fb_d_20250928_p2_r2_col2': {
        "label": '15.84',
        "predicted": '15.84',
        "confidences": [0.412, 0.306, 0.551, 0.245],
    },
    'fb_d_20250928_p2_r2_col3': {
        "label": '12.64',
        "predicted": '12.?4',
        "confidences": [1.258, 0.543, 0.06, 0.207],
    },
    'fb_d_20250928_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.595],
    },
    'fb_d_20250928_p2_r3_col1': {
        "label": '5.31',
        "predicted": '5.?1',
        "confidences": [0.198, 0.142, 1.004],
    },
    'fb_d_20250928_p2_r3_col2': {
        "label": '19.74',
        "predicted": '1?.74',
        "confidences": [1.172, 0.051, 0.738, 0.353],
    },
    'fb_d_20250928_p2_r3_col3': {
        "label": '10.27',
        "predicted": '10.27',
        "confidences": [1.721, 0.497, 0.54, 0.439],
    },
    'fb_d_20250928_p2_r3_col4': {
        "label": '5.23',
        "predicted": '5.23',
        "confidences": [0.329, 0.39, 0.21],
    },
    'fb_d_20250928_p2_r4_col1': {
        "label": '2.1',
        "predicted": '2.1',
        "confidences": [0.703, 2.67],
    },
    'fb_d_20250928_p2_r4_col2': {
        "label": '12.15',
        "predicted": '1?.15',
        "confidences": [1.045, 0.105, 1.045, 0.758],
    },
    'fb_d_20250928_p2_r4_col3': {
        "label": '31.94',
        "predicted": '31.?4',
        "confidences": [0.25, 2.597, 0.125, 0.532],
    },
    'fb_d_20250928_p2_r4_col4': {
        "label": '94.77',
        "predicted": '?4.77',
        "confidences": [0.106, 0.356, 0.834, 0.834],
    },
    'fb_d_20250930_p1_r0_col1': {
        "label": '48.46',
        "predicted": '4?.46',
        "confidences": [0.645, 0.135, 0.645, 0.151],
    },
    'fb_d_20250930_p1_r0_col2': {
        "label": '20.92',
        "predicted": '20.?2',
        "confidences": [0.506, 0.465, 0.062, 0.506],
    },
    'fb_d_20250930_p1_r0_col3': {
        "label": '21.09',
        "predicted": '21.09',
        "confidences": [0.553, 1.721, 0.761, 0.156],
    },
    'fb_d_20250930_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20250930_p1_r1_col1': {
        "label": '26.07',
        "predicted": '2?.07',
        "confidences": [0.576, 0.016, 0.237, 0.654],
    },
    'fb_d_20250930_p1_r1_col2': {
        "label": '32.87',
        "predicted": '32.?7',
        "confidences": [0.29, 0.624, 0.116, 0.413],
    },
    'fb_d_20250930_p1_r1_col3': {
        "label": '22.34',
        "predicted": '22.34',
        "confidences": [0.486, 0.486, 0.218, 0.508],
    },
    'fb_d_20250930_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20250930_p1_r2_col1': {
        "label": '14.64',
        "predicted": '14.?4',
        "confidences": [2.821, 0.251, 0.027, 0.251],
    },
    'fb_d_20250930_p1_r2_col2': {
        "label": '25.7',
        "predicted": '25.7',
        "confidences": [0.437, 0.306, 0.159],
    },
    'fb_d_20250930_p1_r2_col3': {
        "label": '22.88',
        "predicted": '22.88',
        "confidences": [0.717, 0.717, 0.34, 0.34],
    },
    'fb_d_20250930_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.5],
    },
    'fb_d_20250930_p1_r3_col1': {
        "label": '6.99',
        "predicted": '?.??',
        "confidences": [0.056, 0.062, 0.062],
    },
    'fb_d_20250930_p1_r3_col2': {
        "label": '11.52',
        "predicted": '11.52',
        "confidences": [1.749, 1.749, 0.363, 0.655],
    },
    'fb_d_20250930_p1_r3_col3': {
        "label": '18.99',
        "predicted": '18.??',
        "confidences": [1.721, 0.535, 0.146, 0.146],
    },
    'fb_d_20250930_p1_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.644],
    },
    'fb_d_20250930_p1_r4_col1': {
        "label": '3.84',
        "predicted": '?.84',
        "confidences": [0.049, 0.285, 0.559],
    },
    'fb_d_20250930_p1_r4_col2': {
        "label": '8.99',
        "predicted": '8.??',
        "confidences": [0.325, 0.137, 0.137],
    },
    'fb_d_20250930_p1_r4_col3': {
        "label": '14.7',
        "predicted": '14.7',
        "confidences": [2.597, 0.532, 0.44],
    },
    'fb_d_20250930_p1_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [2.189, 0.541, 0.541],
    },
    'fb_d_20250930_p2_r0_col1': {
        "label": '53.51',
        "predicted": '??.?1',
        "confidences": [0.027, 0.012, 0.027, 1.448],
    },
    'fb_d_20250930_p2_r0_col2': {
        "label": '32.73',
        "predicted": '32.73',
        "confidences": [0.536, 0.436, 0.556, 0.416],
    },
    'fb_d_20250930_p2_r0_col3': {
        "label": '23.54',
        "predicted": '23.54',
        "confidences": [0.553, 0.266, 0.454, 0.463],
    },
    'fb_d_20250930_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20250930_p2_r1_col1': {
        "label": '36.82',
        "predicted": '??.82',
        "confidences": [0.042, 0.016, 0.277, 0.576],
    },
    'fb_d_20250930_p2_r1_col2': {
        "label": '14.83',
        "predicted": '14.?3',
        "confidences": [1.173, 0.286, 0.116, 0.439],
    },
    'fb_d_20250930_p2_r1_col3': {
        "label": '20.36',
        "predicted": '20.3?',
        "confidences": [0.486, 0.287, 0.312, 0.101],
    },
    'fb_d_20250930_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20250930_p2_r2_col1': {
        "label": '5.11',
        "predicted": '?.11',
        "confidences": [0.065, 2.821, 2.821],
    },
    'fb_d_20250930_p2_r2_col2': {
        "label": '9.17',
        "predicted": '?.17',
        "confidences": [0.036, 0.412, 0.159],
    },
    'fb_d_20250930_p2_r2_col3': {
        "label": '13.29',
        "predicted": '13.2?',
        "confidences": [1.258, 0.241, 0.543, 0.014],
    },
    'fb_d_20250930_p2_r2_col4': {
        "label": '16.25',
        "predicted": '1?.25',
        "confidences": [1.755, 0.03, 0.604, 0.27],
    },
    'fb_d_20250930_p2_r3_col1': {
        "label": '2.63',
        "predicted": '2.??',
        "confidences": [0.695, 0.056, 0.142],
    },
    'fb_d_20250930_p2_r3_col2': {
        "label": '33.18',
        "predicted": '33.18',
        "confidences": [0.299, 0.299, 1.172, 0.311],
    },
    'fb_d_20250930_p2_r3_col3': {
        "label": '12.41',
        "predicted": '12.41',
        "confidences": [1.721, 0.54, 0.331, 1.721],
    },
    'fb_d_20250930_p2_r3_col4': {
        "label": '81.44',
        "predicted": '81.44',
        "confidences": [0.579, 2.749, 0.468, 0.468],
    },
    'fb_d_20250930_p2_r4_col1': {
        "label": '1.93',
        "predicted": '1.??',
        "confidences": [2.67, 0.02, 0.049],
    },
    'fb_d_20250930_p2_r4_col2': {
        "label": '10.09',
        "predicted": '10.0?',
        "confidences": [1.045, 0.569, 0.569, 0.137],
    },
    'fb_d_20250930_p2_r4_col3': {
        "label": '30.4',
        "predicted": '30.4',
        "confidences": [0.25, 0.383, 0.532],
    },
    'fb_d_20250930_p2_r4_col4': {
        "label": '2.3',
        "predicted": '2.3',
        "confidences": [0.346, 0.257],
    },
    'fb_d_20251022_p1_r0_col1': {
        "label": '48.92',
        "predicted": '4?.?2',
        "confidences": [0.645, 0.135, 0.1, 0.57],
    },
    'fb_d_20251022_p1_r0_col2': {
        "label": '23.87',
        "predicted": '23.87',
        "confidences": [0.506, 0.493, 0.462, 0.556],
    },
    'fb_d_20251022_p1_r0_col3': {
        "label": '17.4',
        "predicted": '17.4',
        "confidences": [1.721, 0.394, 0.463],
    },
    'fb_d_20251022_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20251022_p1_r1_col1': {
        "label": '36.44',
        "predicted": '??.44',
        "confidences": [0.042, 0.016, 0.363, 0.363],
    },
    'fb_d_20251022_p1_r1_col2': {
        "label": '41.72',
        "predicted": '41.72',
        "confidences": [0.286, 1.243, 0.413, 0.624],
    },
    'fb_d_20251022_p1_r1_col3': {
        "label": '14.67',
        "predicted": '14.?7',
        "confidences": [2.185, 0.508, 0.101, 0.614],
    },
    'fb_d_20251022_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20251022_p1_r2_col1': {
        "label": '9.9',
        "predicted": '?.?',
        "confidences": [0.02, 0.02],
    },
    'fb_d_20251022_p1_r2_col2': {
        "label": '10.55',
        "predicted": '10.55',
        "confidences": [0.901, 0.545, 0.306, 0.306],
    },
    'fb_d_20251022_p1_r2_col3': {
        "label": '35.92',
        "predicted": '35.?2',
        "confidences": [0.368, 0.2, 0.05, 0.543],
    },
    'fb_d_20251022_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.553],
    },
    'fb_d_20251022_p1_r3_col1': {
        "label": '3.74',
        "predicted": '?.74',
        "confidences": [0.142, 0.327, 0.543],
    },
    'fb_d_20251022_p1_r3_col2': {
        "label": '13.31',
        "predicted": '13.31',
        "confidences": [1.172, 0.299, 0.299, 1.172],
    },
    'fb_d_20251022_p1_r3_col3': {
        "label": '19.4',
        "predicted": '1?.4',
        "confidences": [1.721, 0.146, 0.331],
    },
    'fb_d_20251022_p1_r3_col4': {
        "label": '73.01',
        "predicted": '73.01',
        "confidences": [0.805, 0.21, 0.489, 2.749],
    },
    'fb_d_20251022_p1_r4_col1': {
        "label": '1',
        "predicted": '1',
        "confidences": [2.67],
    },
    'fb_d_20251022_p1_r4_col2': {
        "label": '10.55',
        "predicted": '10.55',
        "confidences": [1.045, 0.569, 0.758, 0.758],
    },
    'fb_d_20251022_p1_r4_col3': {
        "label": '12.61',
        "predicted": '12.?1',
        "confidences": [2.597, 0.385, 0.069, 2.597],
    },
    'fb_d_20251022_p1_r4_col4': {
        "label": '26.99',
        "predicted": '2?.??',
        "confidences": [0.346, 0.066, 0.106, 0.106],
    },
    'fb_d_20251022_p2_r0_col1': {
        "label": '39.53',
        "predicted": '??.??',
        "confidences": [0.012, 0.1, 0.027, 0.012],
    },
    'fb_d_20251022_p2_r0_col2': {
        "label": '19.06',
        "predicted": '1?.0?',
        "confidences": [0.815, 0.101, 0.471, 0.036],
    },
    'fb_d_20251022_p2_r0_col3': {
        "label": '29.34',
        "predicted": '29.34',
        "confidences": [0.553, 0.156, 0.266, 0.463],
    },
    'fb_d_20251022_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20251022_p2_r1_col1': {
        "label": '29.99',
        "predicted": '2?.??',
        "confidences": [0.576, 0.009, 0.009, 0.009],
    },
    'fb_d_20251022_p2_r1_col2': {
        "label": '24.53',
        "predicted": '24.53',
        "confidences": [0.737, 0.286, 0.505, 0.439],
    },
    'fb_d_20251022_p2_r1_col3': {
        "label": '24.11',
        "predicted": '24.11',
        "confidences": [0.486, 0.312, 2.185, 2.185],
    },
    'fb_d_20251022_p2_r1_col4': {
        "label": '8.34',
        "predicted": '?.?4',
        "confidences": [0.004, 0.101, 0.43],
    },
    'fb_d_20251022_p2_r2_col1': {
        "label": '19.17',
        "predicted": '1?.17',
        "confidences": [2.821, 0.039, 2.821, 0.402],
    },
    'fb_d_20251022_p2_r2_col2': {
        "label": '32.03',
        "predicted": '32.03',
        "confidences": [0.211, 0.559, 0.545, 0.211],
    },
    'fb_d_20251022_p2_r2_col3': {
        "label": '15.52',
        "predicted": '15.52',
        "confidences": [1.258, 0.2, 0.2, 0.543],
    },
    'fb_d_20251022_p2_r2_col4': {
        "label": '6.26',
        "predicted": '?.2?',
        "confidences": [0.017, 0.875, 0.017],
    },
    'fb_d_20251022_p2_r3_col1': {
        "label": '9.48',
        "predicted": '?.48',
        "confidences": [0.062, 0.543, 0.246],
    },
    'fb_d_20251022_p2_r3_col2': {
        "label": '12.55',
        "predicted": '12.55',
        "confidences": [1.172, 0.725, 0.363, 0.363],
    },
    'fb_d_20251022_p2_r3_col3': {
        "label": '11.95',
        "predicted": '11.?5',
        "confidences": [1.721, 1.721, 0.146, 0.32],
    },
    'fb_d_20251022_p2_r3_col4': {
        "label": '5.59',
        "predicted": '5.5?',
        "confidences": [0.329, 0.329, 0.005],
    },
    'fb_d_20251022_p2_r4_col1': {
        "label": '1.83',
        "predicted": '1.8?',
        "confidences": [2.67, 0.285, 0.049],
    },
    'fb_d_20251022_p2_r4_col2': {
        "label": '11.83',
        "predicted": '11.83',
        "confidences": [1.045, 1.045, 0.325, 0.153],
    },
    'fb_d_20251022_p2_r4_col3': {
        "label": '19.08',
        "predicted": '1?.08',
        "confidences": [2.597, 0.125, 0.383, 0.277],
    },
    'fb_d_20251022_p2_r4_col4': {
        "label": '79.81',
        "predicted": '7?.81',
        "confidences": [0.834, 0.106, 0.406, 2.189],
    },
    'fb_d_20251024_p1_r0_col1': {
        "label": '49.29',
        "predicted": '4?.2?',
        "confidences": [0.645, 0.1, 0.57, 0.1],
    },
    'fb_d_20251024_p1_r0_col2': {
        "label": '26.69',
        "predicted": '2?.??',
        "confidences": [0.506, 0.036, 0.036, 0.062],
    },
    'fb_d_20251024_p1_r0_col3': {
        "label": '33.83',
        "predicted": '33.83',
        "confidences": [0.329, 0.329, 0.434, 0.329],
    },
    'fb_d_20251024_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20251024_p1_r1_col1': {
        "label": '37.6',
        "predicted": '?7.?',
        "confidences": [0.042, 0.654, 0.016],
    },
    'fb_d_20251024_p1_r1_col2': {
        "label": '36.49',
        "predicted": '3?.4?',
        "confidences": [0.29, 0.073, 0.286, 0.041],
    },
    'fb_d_20251024_p1_r1_col3': {
        "label": '23.71',
        "predicted": '23.71',
        "confidences": [0.486, 0.218, 0.614, 2.185],
    },
    'fb_d_20251024_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20251024_p1_r2_col1': {
        "label": '10.03',
        "predicted": '1?.??',
        "confidences": [2.821, 0.126, 0.126, 0.031],
    },
    'fb_d_20251024_p1_r2_col2': {
        "label": '15.96',
        "predicted": '15.??',
        "confidences": [0.901, 0.306, 0.036, 0.014],
    },
    'fb_d_20251024_p1_r2_col3': {
        "label": '9.9',
        "predicted": '?.?',
        "confidences": [0.05, 0.05],
    },
    'fb_d_20251024_p1_r2_col4': {
        "label": '0.35',
        "predicted": '0.35',
        "confidences": [0.553, 0.253, 0.43],
    },
    'fb_d_20251024_p1_r3_col1': {
        "label": '1.84',
        "predicted": '1.84',
        "confidences": [1.004, 0.246, 0.543],
    },
    'fb_d_20251024_p1_r3_col2': {
        "label": '6.64',
        "predicted": '?.?4',
        "confidences": [0.04, 0.04, 0.353],
    },
    'fb_d_20251024_p1_r3_col3': {
        "label": '8.96',
        "predicted": '8.??',
        "confidences": [0.535, 0.146, 0.049],
    },
    'fb_d_20251024_p1_r3_col4': {
        "label": '94.45',
        "predicted": '?4.45',
        "confidences": [0.005, 0.468, 0.468, 0.329],
    },
    'fb_d_20251024_p1_r4_col1': {
        "label": '1.24',
        "predicted": '1.24',
        "confidences": [2.67, 0.703, 0.559],
    },
    'fb_d_20251024_p1_r4_col2': {
        "label": '14.22',
        "predicted": '14.??',
        "confidences": [1.045, 0.292, 0.105, 0.105],
    },
    'fb_d_20251024_p1_r4_col3': {
        "label": '23.6',
        "predicted": '23.?',
        "confidences": [0.385, 0.25, 0.069],
    },
    'fb_d_20251024_p1_r4_col4': {
        "label": '5.2',
        "predicted": '5.2',
        "confidences": [0.399, 0.346],
    },
    'fb_d_20251024_p2_r0_col1': {
        "label": '43.84',
        "predicted": '4?.?4',
        "confidences": [0.645, 0.012, 0.135, 0.645],
    },
    'fb_d_20251024_p2_r0_col2': {
        "label": '18.67',
        "predicted": '18.?7',
        "confidences": [0.815, 0.462, 0.02, 0.383],
    },
    'fb_d_20251024_p2_r0_col3': {
        "label": '35.52',
        "predicted": '35.52',
        "confidences": [0.266, 0.454, 0.454, 0.553],
    },
    'fb_d_20251024_p2_r0_col4': {
        "label": '2.55',
        "predicted": '2.55',
        "confidences": [0.7, 0.449, 0.449],
    },
    'fb_d_20251024_p2_r1_col1': {
        "label": '27.72',
        "predicted": '27.72',
        "confidences": [0.576, 0.654, 0.654, 0.576],
    },
    'fb_d_20251024_p2_r1_col2': {
        "label": '24.61',
        "predicted": '24.?1',
        "confidences": [0.737, 0.286, 0.011, 1.173],
    },
    'fb_d_20251024_p2_r1_col3': {
        "label": '24.45',
        "predicted": '24.45',
        "confidences": [0.486, 0.312, 0.312, 0.322],
    },
    'fb_d_20251024_p2_r1_col4': {
        "label": '10.26',
        "predicted": '10.2?',
        "confidences": [2.185, 0.493, 0.44, 0.009],
    },
    'fb_d_20251024_p2_r2_col1': {
        "label": '17.93',
        "predicted": '17.??',
        "confidences": [2.821, 0.402, 0.039, 0.031],
    },
    'fb_d_20251024_p2_r2_col2': {
        "label": '31.12',
        "predicted": '31.12',
        "confidences": [0.211, 0.412, 0.412, 0.559],
    },
    'fb_d_20251024_p2_r2_col3': {
        "label": '11.63',
        "predicted": '11.?3',
        "confidences": [1.258, 1.258, 0.06, 0.322],
    },
    'fb_d_20251024_p2_r2_col4': {
        "label": '4.54',
        "predicted": '4.54',
        "confidences": [0.423, 0.27, 0.423],
    },
    'fb_d_20251024_p2_r3_col1': {
        "label": '8.38',
        "predicted": '8.?8',
        "confidences": [0.246, 0.142, 0.246],
    },
    'fb_d_20251024_p2_r3_col2': {
        "label": '10.75',
        "predicted": '10.75',
        "confidences": [1.172, 0.429, 0.738, 0.363],
    },
    'fb_d_20251024_p2_r3_col3': {
        "label": '11.43',
        "predicted": '11.43',
        "confidences": [1.721, 1.721, 0.331, 0.605],
    },
    'fb_d_20251024_p2_r3_col4': {
        "label": '3.92',
        "predicted": '3.?2',
        "confidences": [0.21, 0.005, 0.39],
    },
    'fb_d_20251024_p2_r4_col1': {
        "label": '2.13',
        "predicted": '2.1?',
        "confidences": [0.703, 2.67, 0.049],
    },
    'fb_d_20251024_p2_r4_col2': {
        "label": '14.85',
        "predicted": '14.85',
        "confidences": [1.045, 0.292, 0.325, 0.758],
    },
    'fb_d_20251024_p2_r4_col3': {
        "label": '16.97',
        "predicted": '1?.?7',
        "confidences": [2.597, 0.069, 0.125, 0.44],
    },
    'fb_d_20251024_p2_r4_col4': {
        "label": '78.73',
        "predicted": '78.73',
        "confidences": [0.834, 0.406, 0.834, 0.257],
    },
    'fb_d_20251111_p1_r0_col1': {
        "label": '71.47',
        "predicted": '?1.4?',
        "confidences": [0.064, 1.448, 0.645, 0.064],
    },
    'fb_d_20251111_p1_r0_col2': {
        "label": '44.5',
        "predicted": '44.5',
        "confidences": [0.484, 0.484, 0.347],
    },
    'fb_d_20251111_p1_r0_col3': {
        "label": '17.73',
        "predicted": '17.73',
        "confidences": [1.721, 0.394, 0.394, 0.329],
    },
    'fb_d_20251111_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20251111_p1_r1_col1': {
        "label": '10.26',
        "predicted": '10.2?',
        "confidences": [1.22, 0.241, 0.321, 0.003],
    },
    'fb_d_20251111_p1_r1_col2': {
        "label": '14.18',
        "predicted": '14.18',
        "confidences": [1.604, 0.323, 1.604, 0.169],
    },
    'fb_d_20251111_p1_r1_col3': {
        "label": '29.99',
        "predicted": '2?.??',
        "confidences": [0.291, 0.126, 0.126, 0.126],
    },
    'fb_d_20251111_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.174],
    },
    'fb_d_20251111_p1_r2_col1': {
        "label": '9.78',
        "predicted": '?.78',
        "confidences": [0.017, 0.422, 0.3],
    },
    'fb_d_20251111_p1_r2_col2': {
        "label": '34.02',
        "predicted": '34.02',
        "confidences": [0.265, 0.327, 0.357, 0.75],
    },
    'fb_d_20251111_p1_r2_col3': {
        "label": '18.91',
        "predicted": '1?.?1',
        "confidences": [2.185, 0.005, 0.001, 2.185],
    },
    'fb_d_20251111_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.495],
    },
    'fb_d_20251111_p1_r3_col1': {
        "label": '8.09',
        "predicted": '?.??',
        "confidences": [0.1, 0.053, 0.023],
    },
    'fb_d_20251111_p1_r3_col2': {
        "label": '4.11',
        "predicted": '4.11',
        "confidences": [0.241, 0.412, 0.412],
    },
    'fb_d_20251111_p1_r3_col3': {
        "label": '9.16',
        "predicted": '?.1?',
        "confidences": [0.117, 1.258, 0.016],
    },
    'fb_d_20251111_p1_r3_col4': {
        "label": '44.38',
        "predicted": '44.?8',
        "confidences": [0.423, 0.423, 0.144, 0.292],
    },
    'fb_d_20251111_p2_r0_col1': {
        "label": '45.39',
        "predicted": '4?.??',
        "confidences": [0.645, 0.027, 0.012, 0.1],
    },
    'fb_d_20251111_p2_r0_col2': {
        "label": '30.25',
        "predicted": '30.25',
        "confidences": [0.536, 0.532, 0.436, 0.347],
    },
    'fb_d_20251111_p2_r0_col3': {
        "label": '24',
        "predicted": '24',
        "confidences": [0.553, 0.463],
    },
    'fb_d_20251111_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20251111_p2_r1_col1': {
        "label": '27.45',
        "predicted": '27.4?',
        "confidences": [0.576, 0.654, 0.363, 0.124],
    },
    'fb_d_20251111_p2_r1_col2': {
        "label": '30.24',
        "predicted": '30.24',
        "confidences": [0.439, 0.391, 0.737, 0.286],
    },
    'fb_d_20251111_p2_r1_col3': {
        "label": '18.32',
        "predicted": '1?.32',
        "confidences": [2.185, 0.007, 0.312, 0.486],
    },
    'fb_d_20251111_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20251111_p2_r2_col1': {
        "label": '14.82',
        "predicted": '14.82',
        "confidences": [2.821, 0.229, 0.372, 0.318],
    },
    'fb_d_20251111_p2_r2_col2': {
        "label": '12.9',
        "predicted": '12.?',
        "confidences": [0.412, 0.559, 0.036],
    },
    'fb_d_20251111_p2_r2_col3': {
        "label": '18.56',
        "predicted": '18.5?',
        "confidences": [1.258, 0.5, 0.224, 0.06],
    },
    'fb_d_20251111_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.595],
    },
    'fb_d_20251111_p2_r3_col1': {
        "label": '11.36',
        "predicted": '11.??',
        "confidences": [1.004, 1.004, 0.142, 0.056],
    },
    'fb_d_20251111_p2_r3_col2': {
        "label": '25',
        "predicted": '25',
        "confidences": [0.725, 0.363],
    },
    'fb_d_20251111_p2_r3_col3': {
        "label": '19.12',
        "predicted": '1?.12',
        "confidences": [1.721, 0.146, 1.721, 0.54],
    },
    'fb_d_20251111_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.489],
    },
    'fb_d_20251111_p2_r4_col1': {
        "label": '0.98',
        "predicted": '0.?8',
        "confidences": [0.274, 0.02, 0.285],
    },
    'fb_d_20251111_p2_r4_col2': {
        "label": '1.61',
        "predicted": '1.?1',
        "confidences": [1.045, 0.069, 1.045],
    },
    'fb_d_20251111_p2_r4_col3': {
        "label": '20',
        "predicted": '20',
        "confidences": [0.385, 0.383],
    },
    'fb_d_20251111_p2_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [2.189, 0.541, 0.541],
    },
    'fb_d_20251112_p1_r0_col1': {
        "label": '72.76',
        "predicted": '?2.?6',
        "confidences": [0.064, 0.57, 0.064, 0.151],
    },
    'fb_d_20251112_p1_r0_col2': {
        "label": '44.28',
        "predicted": '44.28',
        "confidences": [0.484, 0.484, 0.506, 0.462],
    },
    'fb_d_20251112_p1_r0_col3': {
        "label": '16.78',
        "predicted": '16.78',
        "confidences": [1.721, 0.168, 0.394, 0.434],
    },
    'fb_d_20251112_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'fb_d_20251112_p1_r1_col1': {
        "label": '9.73',
        "predicted": '?.7?',
        "confidences": [0.009, 0.654, 0.042],
    },
    'fb_d_20251112_p1_r1_col2': {
        "label": '13.98',
        "predicted": '13.??',
        "confidences": [1.243, 0.439, 0.041, 0.116],
    },
    'fb_d_20251112_p1_r1_col3': {
        "label": '32.15',
        "predicted": '32.15',
        "confidences": [0.218, 0.486, 2.185, 0.308],
    },
    'fb_d_20251112_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'fb_d_20251112_p1_r2_col1': {
        "label": '8.86',
        "predicted": '8.8?',
        "confidences": [0.372, 0.372, 0.027],
    },
    'fb_d_20251112_p1_r2_col2': {
        "label": '33.6',
        "predicted": '33.?',
        "confidences": [0.333, 0.333, 0.044],
    },
    'fb_d_20251112_p1_r2_col3': {
        "label": '21.97',
        "predicted": '21.??',
        "confidences": [0.717, 1.258, 0.05, 0.148],
    },
    'fb_d_20251112_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.5],
    },
    'fb_d_20251112_p1_r3_col1': {
        "label": '8.03',
        "predicted": '8.??',
        "confidences": [0.246, 0.028, 0.142],
    },
    'fb_d_20251112_p1_r3_col2': {
        "label": '4.02',
        "predicted": '4.02',
        "confidences": [0.353, 0.491, 0.655],
    },
    'fb_d_20251112_p1_r3_col3': {
        "label": '9.02',
        "predicted": '?.02',
        "confidences": [0.146, 0.396, 0.54],
    },
    'fb_d_20251112_p1_r3_col4': {
        "label": '32.48',
        "predicted": '32.48',
        "confidences": [0.501, 0.556, 0.258, 0.682],
    },
    'fb_d_20251112_p1_r4_col1': {
        "label": '0.62',
        "predicted": '0.?2',
        "confidences": [0.274, 0.058, 0.703],
    },
    'fb_d_20251112_p1_r4_col2': {
        "label": '4.12',
        "predicted": '4.12',
        "confidences": [0.292, 1.893, 0.401],
    },
    'fb_d_20251112_p1_r4_col3': {
        "label": '20.08',
        "predicted": '20.08',
        "confidences": [0.385, 0.259, 0.259, 0.227],
    },
    'fb_d_20251112_p1_r4_col4': {
        "label": '67.52',
        "predicted": '?7.52',
        "confidences": [0.066, 0.834, 0.399, 0.295],
    },
    'gm_d_20250908_p1_r0_col1': {
        "label": '39.6',
        "predicted": '??.?',
        "confidences": [0.019, 0.037, 0.019],
    },
    'gm_d_20250908_p1_r0_col2': {
        "label": '34.3',
        "predicted": '?4.?',
        "confidences": [0.034, 0.182, 0.034],
    },
    'gm_d_20250908_p1_r0_col3': {
        "label": '3',
        "predicted": '?',
        "confidences": [0.016],
    },
    'gm_d_20250908_p1_r0_col4': {
        "label": '10.4',
        "predicted": '10.4',
        "confidences": [1.74, 0.173, 0.433],
    },
    'gm_d_20250908_p1_r1_col1': {
        "label": '37.3',
        "predicted": '??.?',
        "confidences": [0.019, 0.126, 0.019],
    },
    'gm_d_20250908_p1_r1_col2': {
        "label": '23.1',
        "predicted": '2?.1',
        "confidences": [0.19, 0.034, 1.74],
    },
    'gm_d_20250908_p1_r1_col3': {
        "label": '2',
        "predicted": '2',
        "confidences": [0.185],
    },
    'gm_d_20250908_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.173],
    },
    'gm_d_20250908_p1_r2_col1': {
        "label": '12.1',
        "predicted": '12.1',
        "confidences": [2.099, 0.488, 2.099],
    },
    'gm_d_20250908_p1_r2_col2': {
        "label": '20.0',
        "predicted": '20.0',
        "confidences": [0.334, 0.384, 0.384],
    },
    'gm_d_20250908_p1_r2_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [1.203],
    },
    'gm_d_20250908_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.173],
    },
    'gm_d_20250908_p1_r3_col1': {
        "label": '8.6',
        "predicted": '8.?',
        "confidences": [0.366, 0.019],
    },
    'gm_d_20250908_p1_r3_col2': {
        "label": '11.9',
        "predicted": '11.?',
        "confidences": [1.74, 1.74, 0.054],
    },
    'gm_d_20250908_p1_r3_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [1.203],
    },
    'gm_d_20250908_p1_r3_col4': {
        "label": '1.2',
        "predicted": '1.2',
        "confidences": [1.74, 0.34],
    },
    'gm_d_20250908_p1_r4_col1': {
        "label": '2.2',
        "predicted": '2.2',
        "confidences": [0.488, 0.488],
    },
    'gm_d_20250908_p1_r4_col2': {
        "label": '10.4',
        "predicted": '10.4',
        "confidences": [1.74, 0.384, 0.182],
    },
    'gm_d_20250908_p1_r4_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [1.203],
    },
    'gm_d_20250908_p1_r4_col4': {
        "label": '88.4',
        "predicted": '88.4',
        "confidences": [0.317, 0.317, 0.433],
    },
    'gm_d_20250908_p2_r0_col1': {
        "label": '43.3',
        "predicted": '4?.?',
        "confidences": [0.21, 0.019, 0.019],
    },
    'gm_d_20250908_p2_r0_col2': {
        "label": '30.1',
        "predicted": '?0.1',
        "confidences": [0.034, 0.445, 1.74],
    },
    'gm_d_20250908_p2_r0_col3': {
        "label": '18.66',
        "predicted": '18.??',
        "confidences": [1.203, 0.194, 0.049, 0.049],
    },
    'gm_d_20250908_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.173],
    },
    'gm_d_20250908_p2_r1_col1': {
        "label": '34.7',
        "predicted": '?4.?',
        "confidences": [0.019, 0.21, 0.126],
    },
    'gm_d_20250908_p2_r1_col2': {
        "label": '37.2',
        "predicted": '?7.2',
        "confidences": [0.034, 0.214, 0.334],
    },
    'gm_d_20250908_p2_r1_col3': {
        "label": '3',
        "predicted": '?',
        "confidences": [0.016],
    },
    'gm_d_20250908_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.173],
    },
    'gm_d_20250908_p2_r2_col1': {
        "label": '16.4',
        "predicted": '1?.4',
        "confidences": [2.099, 0.019, 0.21],
    },
    'gm_d_20250908_p2_r2_col2': {
        "label": '12.9',
        "predicted": '12.?',
        "confidences": [1.74, 0.334, 0.054],
    },
    'gm_d_20250908_p2_r2_col3': {
        "label": '1',
        "predicted": '1',
        "confidences": [1.203],
    },
    'gm_d_20250908_p2_r2_col4': {
        "label": '12.45',
        "predicted": '12.48',
        "confidences": [1.74, 0.34, 0.433, 0.265],
    },
    'gm_d_20250908_p2_r3_col1': {
        "label": '3.3',
        "predicted": '?.?',
        "confidences": [0.019, 0.019],
    },
    'gm_d_20250908_p2_r3_col2': {
        "label": '7.1',
        "predicted": '7.1',
        "confidences": [0.214, 1.74],
    },
    'gm_d_20250908_p2_r3_col3': {
        "label": '2',
        "predicted": '2',
        "confidences": [0.185],
    },
    'gm_d_20250908_p2_r3_col4': {
        "label": '76.51',
        "predicted": '??.81',
        "confidences": [0.106, 0.145, 0.265, 1.74],
    },
    'gm_d_20250908_p2_r4_col1': {
        "label": '2.1',
        "predicted": '2.1',
        "confidences": [0.488, 2.099],
    },
    'gm_d_20250908_p2_r4_col2': {
        "label": '12',
        "predicted": '12',
        "confidences": [1.74, 0.334],
    },
    'gm_d_20250908_p2_r4_col3': {
        "label": '9.71',
        "predicted": '?.71',
        "confidences": [0.049, 0.155, 1.203],
    },
    'gm_d_20250908_p2_r4_col4': {
        "label": '11.05',
        "predicted": '11.08',
        "confidences": [1.74, 1.74, 0.173, 0.265],
    },
    'gm_d_20250930_p1_r0_col1': {
        "label": '42.3',
        "predicted": '42.?',
        "confidences": [0.645, 0.57, 0.012],
    },
    'gm_d_20250930_p1_r0_col2': {
        "label": '37.98',
        "predicted": '37.?8',
        "confidences": [0.493, 0.556, 0.062, 0.462],
    },
    'gm_d_20250930_p1_r0_col3': {
        "label": '32.37',
        "predicted": '32.37',
        "confidences": [0.329, 0.553, 0.329, 0.394],
    },
    'gm_d_20250930_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'gm_d_20250930_p1_r1_col1': {
        "label": '36.71',
        "predicted": '??.71',
        "confidences": [0.042, 0.016, 0.654, 2.821],
    },
    'gm_d_20250930_p1_r1_col2': {
        "label": '26.13',
        "predicted": '2?.13',
        "confidences": [0.624, 0.073, 1.243, 0.29],
    },
    'gm_d_20250930_p1_r1_col3': {
        "label": '11.61',
        "predicted": '11.?1',
        "confidences": [2.185, 2.185, 0.101, 2.185],
    },
    'gm_d_20250930_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'gm_d_20250930_p1_r2_col1': {
        "label": '15.57',
        "predicted": '1?.?7',
        "confidences": [2.821, 0.065, 0.065, 0.402],
    },
    'gm_d_20250930_p1_r2_col2': {
        "label": '13.94',
        "predicted": '13.?4',
        "confidences": [0.901, 0.333, 0.036, 0.268],
    },
    'gm_d_20250930_p1_r2_col3': {
        "label": '13.22',
        "predicted": '13.22',
        "confidences": [1.258, 0.368, 0.717, 0.717],
    },
    'gm_d_20250930_p1_r2_col4': {
        "label": '12.99',
        "predicted": '12.??',
        "confidences": [1.755, 0.604, 0.024, 0.024],
    },
    'gm_d_20250930_p1_r3_col1': {
        "label": '2.93',
        "predicted": '2.??',
        "confidences": [0.695, 0.062, 0.142],
    },
    'gm_d_20250930_p1_r3_col2': {
        "label": '9.41',
        "predicted": '?.41',
        "confidences": [0.051, 0.353, 1.749],
    },
    'gm_d_20250930_p1_r3_col3': {
        "label": '13.81',
        "predicted": '13.81',
        "confidences": [1.721, 0.605, 0.535, 1.721],
    },
    'gm_d_20250930_p1_r3_col4': {
        "label": '84.6',
        "predicted": '84.6',
        "confidences": [0.579, 0.258, 0.177],
    },
    'gm_d_20250930_p1_r4_col1': {
        "label": '2.49',
        "predicted": '2.4?',
        "confidences": [0.703, 0.559, 0.02],
    },
    'gm_d_20250930_p1_r4_col2': {
        "label": '12.54',
        "predicted": '12.54',
        "confidences": [1.243, 0.401, 0.505, 0.292],
    },
    'gm_d_20250930_p1_r4_col3': {
        "label": '28.99',
        "predicted": '28.??',
        "confidences": [0.385, 0.227, 0.083, 0.083],
    },
    'gm_d_20250930_p1_r4_col4': {
        "label": '2.41',
        "predicted": '2.41',
        "confidences": [0.295, 0.368, 2.189],
    },
    'gm_d_20250930_p2_r0_col1': {
        "label": '42.01',
        "predicted": '42.?1',
        "confidences": [0.645, 0.57, 0.053, 1.448],
    },
    'gm_d_20250930_p2_r0_col2': {
        "label": '23.84',
        "predicted": '23.84',
        "confidences": [0.436, 0.416, 0.425, 0.484],
    },
    'gm_d_20250930_p2_r0_col3': {
        "label": '20.56',
        "predicted": '20.56',
        "confidences": [0.553, 0.761, 0.454, 0.168],
    },
    'gm_d_20250930_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'gm_d_20250930_p2_r1_col1': {
        "label": '25.92',
        "predicted": '2?.?2',
        "confidences": [0.576, 0.124, 0.009, 0.576],
    },
    'gm_d_20250930_p2_r1_col2': {
        "label": '33.03',
        "predicted": '33.03',
        "confidences": [0.439, 0.439, 0.391, 0.439],
    },
    'gm_d_20250930_p2_r1_col3': {
        "label": '19.87',
        "predicted": '1?.?7',
        "confidences": [2.185, 0.018, 0.007, 0.331],
    },
    'gm_d_20250930_p2_r1_col4': {
        "label": '9.45',
        "predicted": '?.45',
        "confidences": [0.082, 0.43, 0.298],
    },
    'gm_d_20250930_p2_r2_col1': {
        "label": '15.12',
        "predicted": '1?.12',
        "confidences": [2.821, 0.065, 2.821, 0.544],
    },
    'gm_d_20250930_p2_r2_col2': {
        "label": '11.8',
        "predicted": '11.8',
        "confidences": [0.412, 0.412, 0.551],
    },
    'gm_d_20250930_p2_r2_col3': {
        "label": '36.43',
        "predicted": '3?.?3',
        "confidences": [0.241, 0.06, 0.13, 0.241],
    },
    'gm_d_20250930_p2_r2_col4': {
        "label": '8.81',
        "predicted": '8.81',
        "confidences": [0.387, 0.387, 1.755],
    },
    'gm_d_20250930_p2_r3_col1': {
        "label": '14.82',
        "predicted": '14.82',
        "confidences": [1.004, 0.543, 0.246, 0.695],
    },
    'gm_d_20250930_p2_r3_col2': {
        "label": '20.71',
        "predicted": '20.71',
        "confidences": [0.725, 0.429, 0.738, 1.172],
    },
    'gm_d_20250930_p2_r3_col3': {
        "label": '11.44',
        "predicted": '11.44',
        "confidences": [1.721, 1.721, 0.331, 0.331],
    },
    'gm_d_20250930_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.489],
    },
    'gm_d_20250930_p2_r4_col1': {
        "label": '2.13',
        "predicted": '2.1?',
        "confidences": [0.703, 2.67, 0.049],
    },
    'gm_d_20250930_p2_r4_col2': {
        "label": '10.62',
        "predicted": '10.??',
        "confidences": [1.045, 0.569, 0.069, 0.105],
    },
    'gm_d_20250930_p2_r4_col3': {
        "label": '11.7',
        "predicted": '11.7',
        "confidences": [2.597, 2.597, 0.44],
    },
    'gm_d_20250930_p2_r4_col4': {
        "label": '81.74',
        "predicted": '81.74',
        "confidences": [0.406, 2.189, 0.834, 0.356],
    },
    'gm_d_20251023_p1_r0_col1': {
        "label": '58.07',
        "predicted": '??.??',
        "confidences": [0.027, 0.135, 0.053, 0.064],
    },
    'gm_d_20251023_p1_r0_col2': {
        "label": '27.29',
        "predicted": '27.2?',
        "confidences": [0.506, 0.556, 0.506, 0.062],
    },
    'gm_d_20251023_p1_r0_col3': {
        "label": '39.22',
        "predicted": '39.22',
        "confidences": [0.329, 0.156, 0.553, 0.553],
    },
    'gm_d_20251023_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'gm_d_20251023_p1_r1_col1': {
        "label": '27.84',
        "predicted": '27.84',
        "confidences": [0.576, 0.654, 0.277, 0.363],
    },
    'gm_d_20251023_p1_r1_col2': {
        "label": '37.42',
        "predicted": '37.42',
        "confidences": [0.29, 0.413, 0.286, 0.624],
    },
    'gm_d_20251023_p1_r1_col3': {
        "label": '10.42',
        "predicted": '10.42',
        "confidences": [2.185, 0.287, 0.508, 0.486],
    },
    'gm_d_20251023_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'gm_d_20251023_p1_r2_col1': {
        "label": '9.68',
        "predicted": '?.?8',
        "confidences": [0.039, 0.027, 0.372],
    },
    'gm_d_20251023_p1_r2_col2': {
        "label": '16.01',
        "predicted": '1?.01',
        "confidences": [0.901, 0.009, 0.545, 0.901],
    },
    'gm_d_20251023_p1_r2_col3': {
        "label": '9.96',
        "predicted": '?.??',
        "confidences": [0.05, 0.05, 0.107],
    },
    'gm_d_20251023_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.5],
    },
    'gm_d_20251023_p1_r3_col1': {
        "label": '2.46',
        "predicted": '2.4?',
        "confidences": [0.695, 0.543, 0.056],
    },
    'gm_d_20251023_p1_r3_col2': {
        "label": '6.86',
        "predicted": '?.8?',
        "confidences": [0.08, 0.471, 0.08],
    },
    'gm_d_20251023_p1_r3_col3': {
        "label": '12.74',
        "predicted": '12.74',
        "confidences": [1.721, 0.54, 0.603, 0.218],
    },
    'gm_d_20251023_p1_r3_col4': {
        "label": '91.56',
        "predicted": '?1.56',
        "confidences": [0.04, 2.749, 0.491, 0.177],
    },
    'gm_d_20251023_p1_r4_col1': {
        "label": '1.95',
        "predicted": '1.??',
        "confidences": [2.67, 0.02, 0.021],
    },
    'gm_d_20251023_p1_r4_col2': {
        "label": '12.42',
        "predicted": '12.42',
        "confidences": [1.243, 0.401, 0.292, 0.401],
    },
    'gm_d_20251023_p1_r4_col3': {
        "label": '27.66',
        "predicted": '27.??',
        "confidences": [0.385, 0.44, 0.069, 0.069],
    },
    'gm_d_20251023_p1_r4_col4': {
        "label": '8.44',
        "predicted": '8.44',
        "confidences": [0.451, 0.368, 0.368],
    },
    'gm_d_20251023_p2_r0_col1': {
        "label": '44.53',
        "predicted": '44.??',
        "confidences": [0.645, 0.645, 0.027, 0.012],
    },
    'gm_d_20251023_p2_r0_col2': {
        "label": '19.25',
        "predicted": '1?.25',
        "confidences": [0.815, 0.101, 0.436, 0.347],
    },
    'gm_d_20251023_p2_r0_col3': {
        "label": '33.47',
        "predicted": '33.47',
        "confidences": [0.266, 0.266, 0.463, 0.394],
    },
    'gm_d_20251023_p2_r0_col4': {
        "label": '2.46',
        "predicted": '2.4?',
        "confidences": [0.7, 0.553, 0.007],
    },
    'gm_d_20251023_p2_r1_col1': {
        "label": '28.47',
        "predicted": '28.47',
        "confidences": [0.576, 0.277, 0.363, 0.654],
    },
    'gm_d_20251023_p2_r1_col2': {
        "label": '24.74',
        "predicted": '24.74',
        "confidences": [0.737, 0.286, 0.413, 0.286],
    },
    'gm_d_20251023_p2_r1_col3': {
        "label": '24.42',
        "predicted": '24.42',
        "confidences": [0.486, 0.312, 0.312, 0.486],
    },
    'gm_d_20251023_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'gm_d_20251023_p2_r2_col1': {
        "label": '15.41',
        "predicted": '1?.41',
        "confidences": [2.821, 0.065, 0.229, 2.821],
    },
    'gm_d_20251023_p2_r2_col2': {
        "label": '33.02',
        "predicted": '33.02',
        "confidences": [0.211, 0.211, 0.535, 0.559],
    },
    'gm_d_20251023_p2_r2_col3': {
        "label": '15.91',
        "predicted": '15.?1',
        "confidences": [1.258, 0.237, 0.014, 1.258],
    },
    'gm_d_20251023_p2_r2_col4': {
        "label": '6.67',
        "predicted": '?.?7',
        "confidences": [0.017, 0.017, 0.178],
    },
    'gm_d_20251023_p2_r3_col1': {
        "label": '10.02',
        "predicted": '1?.?2',
        "confidences": [1.004, 0.028, 0.028, 0.695],
    },
    'gm_d_20251023_p2_r3_col2': {
        "label": '12.14',
        "predicted": '12.14',
        "confidences": [1.172, 0.725, 1.172, 0.353],
    },
    'gm_d_20251023_p2_r3_col3': {
        "label": '12.41',
        "predicted": '12.41',
        "confidences": [1.721, 0.54, 0.331, 1.721],
    },
    'gm_d_20251023_p2_r3_col4': {
        "label": '1.73',
        "predicted": '1.73',
        "confidences": [2.749, 0.805, 0.21],
    },
    'gm_d_20251023_p2_r4_col1': {
        "label": '1.57',
        "predicted": '1.?7',
        "confidences": [2.67, 0.021, 0.316],
    },
    'gm_d_20251023_p2_r4_col2': {
        "label": '10.85',
        "predicted": '10.85',
        "confidences": [1.045, 0.569, 0.325, 0.758],
    },
    'gm_d_20251023_p2_r4_col3': {
        "label": '13.79',
        "predicted": '13.7?',
        "confidences": [2.597, 0.25, 0.44, 0.125],
    },
    'gm_d_20251023_p2_r4_col4': {
        "label": '89.14',
        "predicted": '8?.14',
        "confidences": [0.406, 0.106, 2.189, 0.356],
    },
    'gm_d_20260111_p1_r0_col1': {
        "label": '41.83',
        "predicted": '41.??',
        "confidences": [0.645, 1.448, 0.135, 0.012],
    },
    'gm_d_20260111_p1_r0_col2': {
        "label": '17.84',
        "predicted": '17.84',
        "confidences": [1.487, 0.556, 0.462, 0.484],
    },
    'gm_d_20260111_p1_r0_col3': {
        "label": '19.89',
        "predicted": '19.89',
        "confidences": [1.721, 0.156, 0.434, 0.156],
    },
    'gm_d_20260111_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'gm_d_20260111_p1_r1_col1': {
        "label": '25.85',
        "predicted": '2?.8?',
        "confidences": [0.576, 0.124, 0.277, 0.124],
    },
    'gm_d_20260111_p1_r1_col2': {
        "label": '26.02',
        "predicted": '2?.02',
        "confidences": [0.624, 0.073, 0.391, 0.624],
    },
    'gm_d_20260111_p1_r1_col3': {
        "label": '20.76',
        "predicted": '20.7?',
        "confidences": [0.486, 0.287, 0.614, 0.101],
    },
    'gm_d_20260111_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'gm_d_20260111_p1_r2_col1': {
        "label": '23.4',
        "predicted": '2?.4',
        "confidences": [0.544, 0.031, 0.251],
    },
    'gm_d_20260111_p1_r2_col2': {
        "label": '30.99',
        "predicted": '30.??',
        "confidences": [0.333, 0.535, 0.036, 0.046],
    },
    'gm_d_20260111_p1_r2_col3': {
        "label": '16.22',
        "predicted": '1?.22',
        "confidences": [1.258, 0.06, 0.717, 0.717],
    },
    'gm_d_20260111_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.5],
    },
    'gm_d_20260111_p1_r3_col1': {
        "label": '6.94',
        "predicted": '?.?4',
        "confidences": [0.056, 0.062, 0.543],
    },
    'gm_d_20260111_p1_r3_col2': {
        "label": '17.08',
        "predicted": '17.08',
        "confidences": [1.749, 0.738, 0.491, 0.471],
    },
    'gm_d_20260111_p1_r3_col3': {
        "label": '23.55',
        "predicted": '23.55',
        "confidences": [0.54, 0.605, 0.32, 0.32],
    },
    'gm_d_20260111_p1_r3_col4': {
        "label": '18.13',
        "predicted": '18.13',
        "confidences": [2.749, 0.579, 2.749, 0.501],
    },
    'gm_d_20260111_p1_r4_col1': {
        "label": '1.98',
        "predicted": '1.?8',
        "confidences": [2.67, 0.02, 0.285],
    },
    'gm_d_20260111_p1_r4_col2': {
        "label": '8.07',
        "predicted": '8.07',
        "confidences": [0.325, 0.569, 0.471],
    },
    'gm_d_20260111_p1_r4_col3': {
        "label": '19.58',
        "predicted": '1?.58',
        "confidences": [2.597, 0.083, 0.477, 0.227],
    },
    'gm_d_20260111_p1_r4_col4': {
        "label": '81.87',
        "predicted": '81.87',
        "confidences": [0.451, 2.189, 0.358, 0.587],
    },
    'gm_d_20260111_p2_r0_col1': {
        "label": '37.21',
        "predicted": '??.21',
        "confidences": [0.012, 0.064, 0.57, 1.448],
    },
    'gm_d_20260111_p2_r0_col2': {
        "label": '51.71',
        "predicted": '51.71',
        "confidences": [0.347, 0.815, 0.556, 0.815],
    },
    'gm_d_20260111_p2_r0_col3': {
        "label": '17.94',
        "predicted": '17.94',
        "confidences": [1.721, 0.394, 0.156, 0.463],
    },
    'gm_d_20260111_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'gm_d_20260111_p2_r1_col1': {
        "label": '36.83',
        "predicted": '??.8?',
        "confidences": [0.042, 0.016, 0.277, 0.042],
    },
    'gm_d_20260111_p2_r1_col2': {
        "label": '32.15',
        "predicted": '32.15',
        "confidences": [0.439, 0.75, 1.173, 0.505],
    },
    'gm_d_20260111_p2_r1_col3': {
        "label": '16.5',
        "predicted": '1?.5',
        "confidences": [2.185, 0.101, 0.322],
    },
    'gm_d_20260111_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'gm_d_20260111_p2_r2_col1': {
        "label": '13',
        "predicted": '1?',
        "confidences": [2.821, 0.031],
    },
    'gm_d_20260111_p2_r2_col2': {
        "label": '6.44',
        "predicted": '?.44',
        "confidences": [0.069, 0.245, 0.245],
    },
    'gm_d_20260111_p2_r2_col3': {
        "label": '38.56',
        "predicted": '38.5?',
        "confidences": [0.241, 0.378, 0.302, 0.06],
    },
    'gm_d_20260111_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.595],
    },
    'gm_d_20260111_p2_r3_col1': {
        "label": '11.41',
        "predicted": '11.41',
        "confidences": [1.004, 1.004, 0.543, 1.004],
    },
    'gm_d_20260111_p2_r3_col2': {
        "label": '6.53',
        "predicted": '?.53',
        "confidences": [0.04, 0.363, 0.299],
    },
    'gm_d_20260111_p2_r3_col3': {
        "label": '8.56',
        "predicted": '8.5?',
        "confidences": [0.535, 0.32, 0.049],
    },
    'gm_d_20260111_p2_r3_col4': {
        "label": '67.95',
        "predicted": '?7.?5',
        "confidences": [0.02, 0.805, 0.005, 0.329],
    },
    'gm_d_20260111_p2_r4_col1': {
        "label": '1.55',
        "predicted": '1.??',
        "confidences": [2.67, 0.021, 0.021],
    },
    'gm_d_20260111_p2_r4_col2': {
        "label": '3.17',
        "predicted": '3.17',
        "confidences": [0.153, 1.045, 0.471],
    },
    'gm_d_20260111_p2_r4_col3': {
        "label": '18.44',
        "predicted": '18.44',
        "confidences": [2.597, 0.277, 0.532, 0.532],
    },
    'gm_d_20260111_p2_r4_col4': {
        "label": '32.05',
        "predicted": '32.05',
        "confidences": [0.257, 0.346, 0.541, 0.399],
    },
    'gm_d_20260202_p1_r0_col1': {
        "label": '32.23',
        "predicted": '?2.2?',
        "confidences": [0.012, 0.57, 0.57, 0.012],
    },
    'gm_d_20260202_p1_r0_col2': {
        "label": '23.03',
        "predicted": '23.03',
        "confidences": [0.506, 0.493, 0.465, 0.493],
    },
    'gm_d_20260202_p1_r0_col3': {
        "label": '20.49',
        "predicted": '20.49',
        "confidences": [0.553, 0.761, 0.463, 0.156],
    },
    'gm_d_20260202_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'gm_d_20260202_p1_r1_col1': {
        "label": '31.62',
        "predicted": '?1.?2',
        "confidences": [0.042, 2.821, 0.016, 0.576],
    },
    'gm_d_20260202_p1_r1_col2': {
        "label": '19.04',
        "predicted": '1?.04',
        "confidences": [1.243, 0.041, 0.391, 0.286],
    },
    'gm_d_20260202_p1_r1_col3': {
        "label": '18.72',
        "predicted": '1?.72',
        "confidences": [2.185, 0.007, 0.614, 0.486],
    },
    'gm_d_20260202_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'gm_d_20260202_p1_r2_col1': {
        "label": '15.79',
        "predicted": '1?.7?',
        "confidences": [2.821, 0.065, 0.402, 0.02],
    },
    'gm_d_20260202_p1_r2_col2': {
        "label": '25.94',
        "predicted": '25.?4',
        "confidences": [0.437, 0.306, 0.036, 0.268],
    },
    'gm_d_20260202_p1_r2_col3': {
        "label": '20.91',
        "predicted": '20.?1',
        "confidences": [0.717, 0.26, 0.05, 1.258],
    },
    'gm_d_20260202_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.5],
    },
    'gm_d_20260202_p1_r3_col1': {
        "label": '10.66',
        "predicted": '1?.??',
        "confidences": [1.004, 0.028, 0.056, 0.056],
    },
    'gm_d_20260202_p1_r3_col2': {
        "label": '17.64',
        "predicted": '17.?4',
        "confidences": [1.749, 0.738, 0.08, 0.353],
    },
    'gm_d_20260202_p1_r3_col3': {
        "label": '19.83',
        "predicted": '1?.83',
        "confidences": [1.721, 0.146, 0.535, 0.605],
    },
    'gm_d_20260202_p1_r3_col4': {
        "label": '1.41',
        "predicted": '1.41',
        "confidences": [2.749, 0.258, 2.749],
    },
    'gm_d_20260202_p1_r4_col1': {
        "label": '9.7',
        "predicted": '?.7',
        "confidences": [0.02, 0.316],
    },
    'gm_d_20260202_p1_r4_col2': {
        "label": '14.35',
        "predicted": '14.35',
        "confidences": [1.243, 0.292, 0.153, 0.505],
    },
    'gm_d_20260202_p1_r4_col3': {
        "label": '20.05',
        "predicted": '20.05',
        "confidences": [0.385, 0.259, 0.259, 0.477],
    },
    'gm_d_20260202_p1_r4_col4': {
        "label": '98.59',
        "predicted": '?8.5?',
        "confidences": [0.026, 0.358, 0.399, 0.026],
    },
    'gm_d_20260202_p2_r0_col1': {
        "label": '46.17',
        "predicted": '46.1?',
        "confidences": [0.645, 0.151, 1.448, 0.064],
    },
    'gm_d_20260202_p2_r0_col2': {
        "label": '11.81',
        "predicted": '11.81',
        "confidences": [0.815, 0.815, 0.425, 0.815],
    },
    'gm_d_20260202_p2_r0_col3': {
        "label": '26.45',
        "predicted": '26.45',
        "confidences": [0.553, 0.168, 0.463, 0.454],
    },
    'gm_d_20260202_p2_r0_col4': {
        "label": '1.89',
        "predicted": '1.8?',
        "confidences": [1.6, 0.53, 0.017],
    },
    'gm_d_20260202_p2_r1_col1': {
        "label": '34.99',
        "predicted": '?4.??',
        "confidences": [0.042, 0.363, 0.009, 0.009],
    },
    'gm_d_20260202_p2_r1_col2': {
        "label": '33.92',
        "predicted": '33.?2',
        "confidences": [0.439, 0.439, 0.091, 0.737],
    },
    'gm_d_20260202_p2_r1_col3': {
        "label": '11.94',
        "predicted": '11.?4',
        "confidences": [2.185, 2.185, 0.018, 0.312],
    },
    'gm_d_20260202_p2_r1_col4': {
        "label": '1.53',
        "predicted": '1.5?',
        "confidences": [2.185, 0.298, 0.101],
    },
    'gm_d_20260202_p2_r2_col1': {
        "label": '14.98',
        "predicted": '14.?8',
        "confidences": [2.821, 0.229, 0.039, 0.372],
    },
    'gm_d_20260202_p2_r2_col2': {
        "label": '43.95',
        "predicted": '43.?5',
        "confidences": [0.276, 0.211, 0.036, 0.306],
    },
    'gm_d_20260202_p2_r2_col3': {
        "label": '22.69',
        "predicted": '22.??',
        "confidences": [0.543, 0.543, 0.06, 0.014],
    },
    'gm_d_20260202_p2_r2_col4': {
        "label": '6.36',
        "predicted": '?.3?',
        "confidences": [0.017, 0.332, 0.017],
    },
    'gm_d_20260202_p2_r3_col1': {
        "label": '2.47',
        "predicted": '2.47',
        "confidences": [0.695, 0.543, 0.327],
    },
    'gm_d_20260202_p2_r3_col2': {
        "label": '5.57',
        "predicted": '5.57',
        "confidences": [0.363, 0.363, 0.738],
    },
    'gm_d_20260202_p2_r3_col3': {
        "label": '15.99',
        "predicted": '15.??',
        "confidences": [1.721, 0.32, 0.146, 0.146],
    },
    'gm_d_20260202_p2_r3_col4': {
        "label": '76.66',
        "predicted": '7?.??',
        "confidences": [0.805, 0.02, 0.02, 0.02],
    },
    'gm_d_20260202_p2_r4_col1': {
        "label": '1.39',
        "predicted": '1.??',
        "confidences": [2.67, 0.049, 0.02],
    },
    'gm_d_20260202_p2_r4_col2': {
        "label": '4.75',
        "predicted": '4.75',
        "confidences": [0.292, 0.471, 0.758],
    },
    'gm_d_20260202_p2_r4_col3': {
        "label": '22.93',
        "predicted": '22.?3',
        "confidences": [0.385, 0.385, 0.125, 0.25],
    },
    'gm_d_20260202_p2_r4_col4': {
        "label": '13.56',
        "predicted": '13.5?',
        "confidences": [2.189, 0.257, 0.399, 0.066],
    },
    'gm_d_20260316_p1_r0_col1': {
        "label": '83.19',
        "predicted": '??.1?',
        "confidences": [0.135, 0.012, 1.448, 0.1],
    },
    'gm_d_20260316_p1_r0_col2': {
        "label": '47.02',
        "predicted": '47.02',
        "confidences": [0.484, 0.556, 0.465, 0.506],
    },
    'gm_d_20260316_p1_r0_col3': {
        "label": '13.75',
        "predicted": '13.75',
        "confidences": [1.721, 0.329, 0.394, 0.454],
    },
    'gm_d_20260316_p1_r0_col4': {
        "label": '13.14',
        "predicted": '13.14',
        "confidences": [1.6, 0.228, 1.6, 0.509],
    },
    'gm_d_20260316_p1_r1_col1': {
        "label": '5.92',
        "predicted": '?.?2',
        "confidences": [0.124, 0.009, 0.576],
    },
    'gm_d_20260316_p1_r1_col2': {
        "label": '19.21',
        "predicted": '1?.21',
        "confidences": [1.243, 0.041, 0.624, 1.243],
    },
    'gm_d_20260316_p1_r1_col3': {
        "label": '20.97',
        "predicted": '20.?7',
        "confidences": [0.486, 0.287, 0.018, 0.614],
    },
    'gm_d_20260316_p1_r1_col4': {
        "label": '19.97',
        "predicted": '1?.?7',
        "confidences": [2.185, 0.082, 0.082, 0.503],
    },
    'gm_d_20260316_p1_r2_col1': {
        "label": '4.3',
        "predicted": '4.?',
        "confidences": [0.229, 0.031],
    },
    'gm_d_20260316_p1_r2_col2': {
        "label": '15.89',
        "predicted": '15.8?',
        "confidences": [0.901, 0.306, 0.551, 0.046],
    },
    'gm_d_20260316_p1_r2_col3': {
        "label": '25.88',
        "predicted": '2?.88',
        "confidences": [0.717, 0.086, 0.34, 0.34],
    },
    'gm_d_20260316_p1_r2_col4': {
        "label": '4.99',
        "predicted": '4.??',
        "confidences": [0.423, 0.024, 0.024],
    },
    'gm_d_20260316_p1_r3_col1': {
        "label": '3.65',
        "predicted": '?.?5',
        "confidences": [0.142, 0.056, 0.198],
    },
    'gm_d_20260316_p1_r3_col2': {
        "label": '6.4',
        "predicted": '?.4',
        "confidences": [0.08, 0.353],
    },
    'gm_d_20260316_p1_r3_col3': {
        "label": '18.68',
        "predicted": '18.?8',
        "confidences": [1.721, 0.535, 0.066, 0.535],
    },
    'gm_d_20260316_p1_r3_col4': {
        "label": '49.19',
        "predicted": '4?.1?',
        "confidences": [0.258, 0.04, 2.749, 0.04],
    },
    'gm_d_20260316_p1_r4_col1': {
        "label": '2.94',
        "predicted": '2.?4',
        "confidences": [0.703, 0.02, 0.559],
    },
    'gm_d_20260316_p1_r4_col2': {
        "label": '11.48',
        "predicted": '11.48',
        "confidences": [1.243, 1.893, 0.292, 0.366],
    },
    'gm_d_20260316_p1_r4_col3': {
        "label": '20.72',
        "predicted": '20.72',
        "confidences": [0.385, 0.259, 0.44, 0.385],
    },
    'gm_d_20260316_p1_r4_col4': {
        "label": '12.71',
        "predicted": '12.71',
        "confidences": [2.189, 0.295, 0.587, 2.189],
    },
    'gm_d_20260316_p2_r0_col1': {
        "label": '35.21',
        "predicted": '??.21',
        "confidences": [0.012, 0.027, 0.57, 1.448],
    },
    'gm_d_20260316_p2_r0_col2': {
        "label": '26.53',
        "predicted": '2?.53',
        "confidences": [0.436, 0.033, 0.347, 0.416],
    },
    'gm_d_20260316_p2_r0_col3': {
        "label": '21.79',
        "predicted": '21.79',
        "confidences": [0.553, 1.721, 0.394, 0.156],
    },
    'gm_d_20260316_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'gm_d_20260316_p2_r1_col1': {
        "label": '33.28',
        "predicted": '??.28',
        "confidences": [0.042, 0.042, 0.576, 0.277],
    },
    'gm_d_20260316_p2_r1_col2': {
        "label": '18.14',
        "predicted": '1?.14',
        "confidences": [1.173, 0.116, 1.173, 0.286],
    },
    'gm_d_20260316_p2_r1_col3': {
        "label": '20.52',
        "predicted": '20.52',
        "confidences": [0.486, 0.287, 0.322, 0.486],
    },
    'gm_d_20260316_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'gm_d_20260316_p2_r2_col1': {
        "label": '13.88',
        "predicted": '1?.88',
        "confidences": [2.821, 0.031, 0.372, 0.372],
    },
    'gm_d_20260316_p2_r2_col2': {
        "label": '25.06',
        "predicted": '25.0?',
        "confidences": [0.559, 0.306, 0.535, 0.026],
    },
    'gm_d_20260316_p2_r2_col3': {
        "label": '23.1',
        "predicted": '23.1',
        "confidences": [0.543, 0.241, 1.258],
    },
    'gm_d_20260316_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.595],
    },
    'gm_d_20260316_p2_r3_col1': {
        "label": '9.54',
        "predicted": '?.54',
        "confidences": [0.062, 0.198, 0.543],
    },
    'gm_d_20260316_p2_r3_col2': {
        "label": '17.23',
        "predicted": '17.23',
        "confidences": [1.172, 0.738, 0.725, 0.299],
    },
    'gm_d_20260316_p2_r3_col3': {
        "label": '16.99',
        "predicted": '1?.??',
        "confidences": [1.721, 0.049, 0.146, 0.146],
    },
    'gm_d_20260316_p2_r3_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [2.749, 0.489, 0.489],
    },
    'gm_d_20260316_p2_r4_col1': {
        "label": '8.09',
        "predicted": '8.0?',
        "confidences": [0.285, 0.274, 0.02],
    },
    'gm_d_20260316_p2_r4_col2': {
        "label": '13.04',
        "predicted": '13.04',
        "confidences": [1.045, 0.153, 0.569, 0.292],
    },
    'gm_d_20260316_p2_r4_col3': {
        "label": '17.6',
        "predicted": '17.?',
        "confidences": [2.597, 0.44, 0.069],
    },
    'gm_d_20260316_p2_r4_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.541],
    },
    'ib_d_20250928_p1_r0_col1': {
        "label": '58.52',
        "predicted": '??.?2',
        "confidences": [0.027, 0.135, 0.027, 0.57],
    },
    'ib_d_20250928_p1_r0_col2': {
        "label": '23.39',
        "predicted": '23.3?',
        "confidences": [0.506, 0.493, 0.493, 0.062],
    },
    'ib_d_20250928_p1_r0_col3': {
        "label": '11.84',
        "predicted": '11.84',
        "confidences": [1.721, 1.721, 0.434, 0.463],
    },
    'ib_d_20250928_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'ib_d_20250928_p1_r1_col1': {
        "label": '15.09',
        "predicted": '1?.0?',
        "confidences": [2.821, 0.124, 0.237, 0.009],
    },
    'ib_d_20250928_p1_r1_col2': {
        "label": '24.13',
        "predicted": '24.13',
        "confidences": [0.624, 0.286, 1.243, 0.29],
    },
    'ib_d_20250928_p1_r1_col3': {
        "label": '33.6',
        "predicted": '33.?',
        "confidences": [0.218, 0.218, 0.101],
    },
    'ib_d_20250928_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20250928_p1_r2_col1': {
        "label": '14.97',
        "predicted": '14.?7',
        "confidences": [2.821, 0.251, 0.02, 0.402],
    },
    'ib_d_20250928_p1_r2_col2': {
        "label": '33.87',
        "predicted": '33.87',
        "confidences": [0.333, 0.333, 0.551, 0.159],
    },
    'ib_d_20250928_p1_r2_col3': {
        "label": '12.61',
        "predicted": '12.?1',
        "confidences": [1.258, 0.717, 0.06, 1.258],
    },
    'ib_d_20250928_p1_r2_col4': {
        "label": '1.32',
        "predicted": '1.?2',
        "confidences": [1.755, 0.131, 0.604],
    },
    'ib_d_20250928_p1_r3_col1': {
        "label": '9.22',
        "predicted": '?.22',
        "confidences": [0.062, 0.695, 0.695],
    },
    'ib_d_20250928_p1_r3_col2': {
        "label": '12.21',
        "predicted": '12.21',
        "confidences": [1.749, 0.655, 0.655, 1.749],
    },
    'ib_d_20250928_p1_r3_col3': {
        "label": '28.79',
        "predicted": '28.7?',
        "confidences": [0.54, 0.535, 0.603, 0.146],
    },
    'ib_d_20250928_p1_r3_col4': {
        "label": '3.5',
        "predicted": '3.5',
        "confidences": [0.501, 0.491],
    },
    'ib_d_20250928_p1_r4_col1': {
        "label": '2.2',
        "predicted": '2.2',
        "confidences": [0.703, 0.703],
    },
    'ib_d_20250928_p1_r4_col2': {
        "label": '6.4',
        "predicted": '?.4',
        "confidences": [0.069, 0.292],
    },
    'ib_d_20250928_p1_r4_col3': {
        "label": '13.16',
        "predicted": '13.1?',
        "confidences": [2.597, 0.234, 2.597, 0.069],
    },
    'ib_d_20250928_p1_r4_col4': {
        "label": '95.18',
        "predicted": '?5.18',
        "confidences": [0.026, 0.399, 2.189, 0.358],
    },
    'ib_d_20250928_p2_r0_col1': {
        "label": '36.26',
        "predicted": '?6.26',
        "confidences": [0.012, 0.151, 0.57, 0.151],
    },
    'ib_d_20250928_p2_r0_col2': {
        "label": '34.58',
        "predicted": '34.58',
        "confidences": [0.536, 0.484, 0.347, 0.462],
    },
    'ib_d_20250928_p2_r0_col3': {
        "label": '19.7',
        "predicted": '19.7',
        "confidences": [1.721, 0.156, 0.394],
    },
    'ib_d_20250928_p2_r0_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [1.6, 0.497, 0.497],
    },
    'ib_d_20250928_p2_r1_col1': {
        "label": '29.6',
        "predicted": '2?.?',
        "confidences": [0.576, 0.009, 0.016],
    },
    'ib_d_20250928_p2_r1_col2': {
        "label": '18.74',
        "predicted": '1?.74',
        "confidences": [1.173, 0.116, 0.413, 0.286],
    },
    'ib_d_20250928_p2_r1_col3': {
        "label": '9.97',
        "predicted": '?.?7',
        "confidences": [0.018, 0.018, 0.331],
    },
    'ib_d_20250928_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20250928_p2_r2_col1': {
        "label": '21',
        "predicted": '21',
        "confidences": [0.544, 2.821],
    },
    'ib_d_20250928_p2_r2_col2': {
        "label": '25.59',
        "predicted": '25.5?',
        "confidences": [0.516, 0.268, 0.268, 0.036],
    },
    'ib_d_20250928_p2_r2_col3': {
        "label": '33.72',
        "predicted": '33.?2',
        "confidences": [0.169, 0.169, 0.148, 0.543],
    },
    'ib_d_20250928_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.595],
    },
    'ib_d_20250928_p2_r3_col1': {
        "label": '7.92',
        "predicted": '7.?2',
        "confidences": [0.327, 0.062, 0.695],
    },
    'ib_d_20250928_p2_r3_col2': {
        "label": '4.28',
        "predicted": '4.28',
        "confidences": [0.353, 0.725, 0.311],
    },
    'ib_d_20250928_p2_r3_col3': {
        "label": '10.28',
        "predicted": '10.28',
        "confidences": [1.721, 0.497, 0.54, 0.535],
    },
    'ib_d_20250928_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.489],
    },
    'ib_d_20250928_p2_r4_col1': {
        "label": '5.22',
        "predicted": '?.22',
        "confidences": [0.021, 0.703, 0.703],
    },
    'ib_d_20250928_p2_r4_col2': {
        "label": '16.81',
        "predicted": '1?.81',
        "confidences": [1.045, 0.069, 0.325, 1.045],
    },
    'ib_d_20250928_p2_r4_col3': {
        "label": '26.33',
        "predicted": '2?.33',
        "confidences": [0.385, 0.069, 0.25, 0.25],
    },
    'ib_d_20250928_p2_r4_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.541],
    },
    'ib_d_20251206_p1_r0_col1': {
        "label": '47.88',
        "predicted": '4?.??',
        "confidences": [0.645, 0.064, 0.135, 0.135],
    },
    'ib_d_20251206_p1_r0_col2': {
        "label": '38.94',
        "predicted": '38.?4',
        "confidences": [0.493, 0.462, 0.062, 0.484],
    },
    'ib_d_20251206_p1_r0_col3': {
        "label": '22',
        "predicted": '22',
        "confidences": [0.553, 0.553],
    },
    'ib_d_20251206_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'ib_d_20251206_p1_r1_col1': {
        "label": '40.95',
        "predicted": '40.??',
        "confidences": [0.363, 0.237, 0.009, 0.124],
    },
    'ib_d_20251206_p1_r1_col2': {
        "label": '14.48',
        "predicted": '14.4?',
        "confidences": [1.243, 0.286, 0.286, 0.141],
    },
    'ib_d_20251206_p1_r1_col3': {
        "label": '30.87',
        "predicted": '30.?7',
        "confidences": [0.218, 0.287, 0.007, 0.614],
    },
    'ib_d_20251206_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20251206_p1_r2_col1': {
        "label": '7.31',
        "predicted": '7.?1',
        "confidences": [0.402, 0.031, 2.821],
    },
    'ib_d_20251206_p1_r2_col2': {
        "label": '36.61',
        "predicted": '3?.?1',
        "confidences": [0.333, 0.044, 0.044, 0.901],
    },
    'ib_d_20251206_p1_r2_col3': {
        "label": '21.76',
        "predicted": '21.??',
        "confidences": [0.543, 1.258, 0.148, 0.06],
    },
    'ib_d_20251206_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.553],
    },
    'ib_d_20251206_p1_r3_col1': {
        "label": '3.39',
        "predicted": '?.??',
        "confidences": [0.142, 0.142, 0.062],
    },
    'ib_d_20251206_p1_r3_col2': {
        "label": '5.74',
        "predicted": '5.74',
        "confidences": [0.363, 0.738, 0.353],
    },
    'ib_d_20251206_p1_r3_col3': {
        "label": '13.42',
        "predicted": '13.42',
        "confidences": [1.721, 0.605, 0.331, 0.54],
    },
    'ib_d_20251206_p1_r3_col4': {
        "label": '44.58',
        "predicted": '44.58',
        "confidences": [0.468, 0.468, 0.329, 0.579],
    },
    'ib_d_20251206_p1_r4_col1': {
        "label": '0.47',
        "predicted": '0.47',
        "confidences": [0.274, 0.559, 0.316],
    },
    'ib_d_20251206_p1_r4_col2': {
        "label": '4.23',
        "predicted": '4.?3',
        "confidences": [0.292, 0.105, 0.153],
    },
    'ib_d_20251206_p1_r4_col3': {
        "label": '11.95',
        "predicted": '11.?5',
        "confidences": [2.597, 2.597, 0.125, 0.478],
    },
    'ib_d_20251206_p1_r4_col4': {
        "label": '55.42',
        "predicted": '55.42',
        "confidences": [0.399, 0.399, 0.356, 0.346],
    },
    'ib_d_20251206_p2_r0_col1': {
        "label": '68.58',
        "predicted": '6?.??',
        "confidences": [0.151, 0.135, 0.027, 0.135],
    },
    'ib_d_20251206_p2_r0_col2': {
        "label": '44.55',
        "predicted": '44.55',
        "confidences": [0.484, 0.484, 0.347, 0.347],
    },
    'ib_d_20251206_p2_r0_col3': {
        "label": '30.02',
        "predicted": '30.02',
        "confidences": [0.266, 0.761, 0.761, 0.553],
    },
    'ib_d_20251206_p2_r0_col4': {
        "label": '0.91',
        "predicted": '0.?1',
        "confidences": [0.497, 0.017, 1.6],
    },
    'ib_d_20251206_p2_r1_col1': {
        "label": '20.92',
        "predicted": '20.?2',
        "confidences": [0.576, 0.237, 0.009, 0.576],
    },
    'ib_d_20251206_p2_r1_col2': {
        "label": '16.29',
        "predicted": '1?.2?',
        "confidences": [1.173, 0.029, 0.737, 0.091],
    },
    'ib_d_20251206_p2_r1_col3': {
        "label": '15.07',
        "predicted": '15.07',
        "confidences": [2.185, 0.322, 0.287, 0.331],
    },
    'ib_d_20251206_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20251206_p2_r2_col1': {
        "label": '5.65',
        "predicted": '?.??',
        "confidences": [0.065, 0.027, 0.065],
    },
    'ib_d_20251206_p2_r2_col2': {
        "label": '15.7',
        "predicted": '15.7',
        "confidences": [0.412, 0.306, 0.159],
    },
    'ib_d_20251206_p2_r2_col3': {
        "label": '33.65',
        "predicted": '33.?5',
        "confidences": [0.241, 0.241, 0.06, 0.302],
    },
    'ib_d_20251206_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.595],
    },
    'ib_d_20251206_p2_r3_col1': {
        "label": '3.61',
        "predicted": '?.?1',
        "confidences": [0.142, 0.056, 1.004],
    },
    'ib_d_20251206_p2_r3_col2': {
        "label": '16.14',
        "predicted": '1?.14',
        "confidences": [1.172, 0.04, 1.172, 0.353],
    },
    'ib_d_20251206_p2_r3_col3': {
        "label": '8.56',
        "predicted": '8.5?',
        "confidences": [0.535, 0.32, 0.049],
    },
    'ib_d_20251206_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.489],
    },
    'ib_d_20251206_p2_r4_col1': {
        "label": '1.24',
        "predicted": '1.24',
        "confidences": [2.67, 0.703, 0.559],
    },
    'ib_d_20251206_p2_r4_col2': {
        "label": '7.32',
        "predicted": '7.3?',
        "confidences": [0.471, 0.153, 0.105],
    },
    'ib_d_20251206_p2_r4_col3': {
        "label": '12.7',
        "predicted": '12.7',
        "confidences": [2.597, 0.385, 0.44],
    },
    'ib_d_20251206_p2_r4_col4': {
        "label": '99.09',
        "predicted": '??.0?',
        "confidences": [0.106, 0.106, 0.541, 0.106],
    },
    'ib_d_20260112_1_p1_r0_col1': {
        "label": '45.89',
        "predicted": '4?.??',
        "confidences": [0.645, 0.027, 0.135, 0.1],
    },
    'ib_d_20260112_1_p1_r0_col2': {
        "label": '51.81',
        "predicted": '51.81',
        "confidences": [0.347, 1.487, 0.462, 1.487],
    },
    'ib_d_20260112_1_p1_r0_col3': {
        "label": '19.71',
        "predicted": '19.71',
        "confidences": [1.721, 0.156, 0.394, 1.721],
    },
    'ib_d_20260112_1_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'ib_d_20260112_1_p1_r1_col1': {
        "label": '35.18',
        "predicted": '??.18',
        "confidences": [0.042, 0.124, 2.821, 0.277],
    },
    'ib_d_20260112_1_p1_r1_col2': {
        "label": '12.22',
        "predicted": '12.22',
        "confidences": [1.243, 0.624, 0.624, 0.624],
    },
    'ib_d_20260112_1_p1_r1_col3': {
        "label": '33.67',
        "predicted": '33.?7',
        "confidences": [0.218, 0.218, 0.101, 0.614],
    },
    'ib_d_20260112_1_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20260112_1_p1_r2_col1': {
        "label": '9.77',
        "predicted": '?.77',
        "confidences": [0.039, 0.402, 0.402],
    },
    'ib_d_20260112_1_p1_r2_col2': {
        "label": '8.81',
        "predicted": '8.81',
        "confidences": [0.551, 0.551, 0.901],
    },
    'ib_d_20260112_1_p1_r2_col3': {
        "label": '22.18',
        "predicted": '22.18',
        "confidences": [0.717, 0.717, 1.258, 0.34],
    },
    'ib_d_20260112_1_p1_r2_col4': {
        "label": '5.31',
        "predicted": '5.?1',
        "confidences": [0.43, 0.131, 1.755],
    },
    'ib_d_20260112_1_p1_r3_col1': {
        "label": '6.34',
        "predicted": '?.?4',
        "confidences": [0.056, 0.142, 0.543],
    },
    'ib_d_20260112_1_p1_r3_col2': {
        "label": '8.98',
        "predicted": '8.?8',
        "confidences": [0.327, 0.051, 0.327],
    },
    'ib_d_20260112_1_p1_r3_col3': {
        "label": '5.2',
        "predicted": '5.2',
        "confidences": [0.32, 0.54],
    },
    'ib_d_20260112_1_p1_r3_col4': {
        "label": '1.74',
        "predicted": '1.74',
        "confidences": [2.749, 0.221, 0.258],
    },
    'ib_d_20260112_1_p1_r4_col1': {
        "label": '2.82',
        "predicted": '2.82',
        "confidences": [0.703, 0.285, 0.703],
    },
    'ib_d_20260112_1_p1_r4_col2': {
        "label": '18.18',
        "predicted": '18.18',
        "confidences": [1.243, 0.325, 1.893, 0.366],
    },
    'ib_d_20260112_1_p1_r4_col3': {
        "label": '19.24',
        "predicted": '1?.24',
        "confidences": [2.597, 0.083, 0.385, 0.532],
    },
    'ib_d_20260112_1_p1_r4_col4': {
        "label": '92.95',
        "predicted": '?2.?5',
        "confidences": [0.026, 0.295, 0.026, 0.252],
    },
    'ib_d_20260112_1_p2_r0_col1': {
        "label": '45.56',
        "predicted": '4?.?6',
        "confidences": [0.645, 0.027, 0.027, 0.151],
    },
    'ib_d_20260112_1_p2_r0_col2': {
        "label": '51.78',
        "predicted": '51.78',
        "confidences": [0.347, 0.815, 0.556, 0.462],
    },
    'ib_d_20260112_1_p2_r0_col3': {
        "label": '18.41',
        "predicted": '18.41',
        "confidences": [1.721, 0.346, 0.463, 1.721],
    },
    'ib_d_20260112_1_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'ib_d_20260112_1_p2_r1_col1': {
        "label": '36.2',
        "predicted": '??.2',
        "confidences": [0.042, 0.016, 0.576],
    },
    'ib_d_20260112_1_p2_r1_col2': {
        "label": '12.38',
        "predicted": '12.3?',
        "confidences": [1.173, 0.75, 0.439, 0.116],
    },
    'ib_d_20260112_1_p2_r1_col3': {
        "label": '40.56',
        "predicted": '40.5?',
        "confidences": [0.312, 0.287, 0.322, 0.101],
    },
    'ib_d_20260112_1_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20260112_1_p2_r2_col1': {
        "label": '9.3',
        "predicted": '?.?',
        "confidences": [0.02, 0.031],
    },
    'ib_d_20260112_1_p2_r2_col2': {
        "label": '8.97',
        "predicted": '8.?7',
        "confidences": [0.551, 0.036, 0.172],
    },
    'ib_d_20260112_1_p2_r2_col3': {
        "label": '20.77',
        "predicted": '20.??',
        "confidences": [0.543, 0.339, 0.111, 0.111],
    },
    'ib_d_20260112_1_p2_r2_col4': {
        "label": '5.06',
        "predicted": '5.0?',
        "confidences": [0.27, 0.595, 0.017],
    },
    'ib_d_20260112_1_p2_r3_col1': {
        "label": '6.2',
        "predicted": '?.2',
        "confidences": [0.056, 0.695],
    },
    'ib_d_20260112_1_p2_r3_col2': {
        "label": '8.89',
        "predicted": '8.8?',
        "confidences": [0.311, 0.311, 0.051],
    },
    'ib_d_20260112_1_p2_r3_col3': {
        "label": '4.61',
        "predicted": '4.?1',
        "confidences": [0.331, 0.049, 1.721],
    },
    'ib_d_20260112_1_p2_r3_col4': {
        "label": '1.43',
        "predicted": '1.43',
        "confidences": [2.749, 0.468, 0.21],
    },
    'ib_d_20260112_1_p2_r4_col1': {
        "label": '2.74',
        "predicted": '2.74',
        "confidences": [0.703, 0.316, 0.559],
    },
    'ib_d_20260112_1_p2_r4_col2': {
        "label": '17.98',
        "predicted": '17.?8',
        "confidences": [1.045, 0.471, 0.137, 0.325],
    },
    'ib_d_20260112_1_p2_r4_col3': {
        "label": '15.65',
        "predicted": '15.?5',
        "confidences": [2.597, 0.478, 0.069, 0.478],
    },
    'ib_d_20260112_1_p2_r4_col4': {
        "label": '93.51',
        "predicted": '?3.51',
        "confidences": [0.106, 0.257, 0.399, 2.189],
    },
    'ib_d_20260114_p1_r0_col1': {
        "label": '40.83',
        "predicted": '4?.??',
        "confidences": [0.645, 0.053, 0.135, 0.012],
    },
    'ib_d_20260114_p1_r0_col2': {
        "label": '34.28',
        "predicted": '34.28',
        "confidences": [0.493, 0.484, 0.506, 0.462],
    },
    'ib_d_20260114_p1_r0_col3': {
        "label": '17.47',
        "predicted": '17.47',
        "confidences": [1.721, 0.394, 0.463, 0.394],
    },
    'ib_d_20260114_p1_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'ib_d_20260114_p1_r1_col1': {
        "label": '36.11',
        "predicted": '??.11',
        "confidences": [0.042, 0.016, 2.821, 2.821],
    },
    'ib_d_20260114_p1_r1_col2': {
        "label": '8.18',
        "predicted": '?.1?',
        "confidences": [0.116, 1.243, 0.116],
    },
    'ib_d_20260114_p1_r1_col3': {
        "label": '25.64',
        "predicted": '25.?4',
        "confidences": [0.486, 0.308, 0.101, 0.508],
    },
    'ib_d_20260114_p1_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20260114_p1_r2_col1': {
        "label": '16.69',
        "predicted": '1?.??',
        "confidences": [2.821, 0.027, 0.027, 0.039],
    },
    'ib_d_20260114_p1_r2_col2': {
        "label": '46.19',
        "predicted": '4?.1?',
        "confidences": [0.276, 0.009, 0.901, 0.046],
    },
    'ib_d_20260114_p1_r2_col3': {
        "label": '32.7',
        "predicted": '32.?',
        "confidences": [0.373, 0.717, 0.111],
    },
    'ib_d_20260114_p1_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.5],
    },
    'ib_d_20260114_p1_r3_col1': {
        "label": '5.3',
        "predicted": '5.?',
        "confidences": [0.198, 0.142],
    },
    'ib_d_20260114_p1_r3_col2': {
        "label": '5.79',
        "predicted": '5.7?',
        "confidences": [0.258, 0.738, 0.051],
    },
    'ib_d_20260114_p1_r3_col3': {
        "label": '4.28',
        "predicted": '4.28',
        "confidences": [0.331, 0.54, 0.461],
    },
    'ib_d_20260114_p1_r3_col4': {
        "label": '2.31',
        "predicted": '2.31',
        "confidences": [0.556, 0.501, 2.749],
    },
    'ib_d_20260114_p1_r4_col1': {
        "label": '1.07',
        "predicted": '1.07',
        "confidences": [2.67, 0.274, 0.316],
    },
    'ib_d_20260114_p1_r4_col2': {
        "label": '5.56',
        "predicted": '5.5?',
        "confidences": [0.505, 0.505, 0.069],
    },
    'ib_d_20260114_p1_r4_col3': {
        "label": '19.91',
        "predicted": '1?.?1',
        "confidences": [2.597, 0.083, 0.083, 2.597],
    },
    'ib_d_20260114_p1_r4_col4': {
        "label": '97.69',
        "predicted": '?7.??',
        "confidences": [0.026, 0.587, 0.066, 0.026],
    },
    'ib_d_20260114_p2_r0_col1': {
        "label": '63.99',
        "predicted": '6?.??',
        "confidences": [0.151, 0.012, 0.1, 0.1],
    },
    'ib_d_20260114_p2_r0_col2': {
        "label": '44.15',
        "predicted": '44.15',
        "confidences": [0.484, 0.484, 0.815, 0.347],
    },
    'ib_d_20260114_p2_r0_col3': {
        "label": '15.46',
        "predicted": '15.46',
        "confidences": [1.721, 0.454, 0.463, 0.168],
    },
    'ib_d_20260114_p2_r0_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.497],
    },
    'ib_d_20260114_p2_r1_col1': {
        "label": '18.68',
        "predicted": '18.?8',
        "confidences": [2.821, 0.277, 0.016, 0.277],
    },
    'ib_d_20260114_p2_r1_col2': {
        "label": '12.89',
        "predicted": '12.??',
        "confidences": [1.173, 0.75, 0.116, 0.091],
    },
    'ib_d_20260114_p2_r1_col3': {
        "label": '17.81',
        "predicted": '17.?1',
        "confidences": [2.185, 0.331, 0.007, 2.185],
    },
    'ib_d_20260114_p2_r1_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.493],
    },
    'ib_d_20260114_p2_r2_col1': {
        "label": '9.27',
        "predicted": '?.27',
        "confidences": [0.02, 0.544, 0.402],
    },
    'ib_d_20260114_p2_r2_col2': {
        "label": '21.97',
        "predicted": '21.?7',
        "confidences": [0.559, 0.412, 0.036, 0.172],
    },
    'ib_d_20260114_p2_r2_col3': {
        "label": '17.66',
        "predicted": '1?.??',
        "confidences": [1.258, 0.111, 0.06, 0.06],
    },
    'ib_d_20260114_p2_r2_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.595],
    },
    'ib_d_20260114_p2_r3_col1': {
        "label": '7.31',
        "predicted": '7.?1',
        "confidences": [0.327, 0.142, 1.004],
    },
    'ib_d_20260114_p2_r3_col2': {
        "label": '16.54',
        "predicted": '1?.54',
        "confidences": [1.172, 0.04, 0.363, 0.353],
    },
    'ib_d_20260114_p2_r3_col3': {
        "label": '33.91',
        "predicted": '33.?1',
        "confidences": [0.605, 0.605, 0.146, 1.721],
    },
    'ib_d_20260114_p2_r3_col4': {
        "label": '0',
        "predicted": '0',
        "confidences": [0.489],
    },
    'ib_d_20260114_p2_r4_col1': {
        "label": '0.75',
        "predicted": '0.7?',
        "confidences": [0.274, 0.316, 0.021],
    },
    'ib_d_20260114_p2_r4_col2': {
        "label": '4.45',
        "predicted": '4.45',
        "confidences": [0.292, 0.292, 0.758],
    },
    'ib_d_20260114_p2_r4_col3': {
        "label": '15.16',
        "predicted": '15.1?',
        "confidences": [2.597, 0.478, 2.597, 0.069],
    },
    'ib_d_20260114_p2_r4_col4': {
        "label": '100',
        "predicted": '100',
        "confidences": [2.189, 0.541, 0.541],
    },
}
