# auto-generated by tests/generate_stat_inputs.py — do not edit by hand
#
# CROPS: ground truth (pct, val) per cell part, grouped by source image.
#   Produced by pure-Tesseract labeling (--tess-only), NOT any blob engine's
#   own output -- so the same ground truth is a fair, engine-neutral
#   reference for every engine under test (dp, padded, ...), corrected by
#   stat_gt_overrides.json. See gfl2.stat_ocr._collect_cells(tess_only=True).
# META: per-image metadata used to judge how much each image contributes
#   to the held-out set — doll frames present,
#   which of those are rare across single/*.png, how many cells the full
#   pipeline itself could not resolve, and known structural outliers.
FONT = 'assets/fonts/stat_pct.py'

CROPS = {
  'fb_d_060518.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '44.84',
      'val': '2800K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '19.24',
      'val': '203',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '27.2',
      'val': '619',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '25.38',
      'val': '1584K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '46.44',
      'val': '490',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '16.12',
      'val': '367',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '13.25',
      'val': '827640',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '16.02',
      'val': '169',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '55.05',
      'val': '1253',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '8.4',
      'val': '524388',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '7.3',
      'val': '77',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '1.63',
      'val': '37',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '8.13',
      'val': '507817',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '11',
      'val': '116',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '100',
      'val': '1957',
    },
  ],
  'fb_d_20250930.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '48.46',
      'val': '855610',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '20.92',
      'val': '149',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '21.09',
      'val': '10477',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '26.07',
      'val': '460375',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '32.87',
      'val': '234',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '22.34',
      'val': '11096',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '14.64',
      'val': '258536',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '25.7',
      'val': '183',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '22.88',
      'val': '11361',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '6.99',
      'val': '123410',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '11.52',
      'val': '82',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '18.99',
      'val': '9429',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '3.84',
      'val': '67758',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '8.99',
      'val': '64',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '14.7',
      'val': '7300',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '100',
      'val': '44452',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '53.51',
      'val': '542822',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '32.73',
      'val': '214',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '23.54',
      'val': '12966',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '36.82',
      'val': '373621',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '14.83',
      'val': '',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '20.36',
      'val': '11213',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '5.11',
      'val': '51887',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '9.17',
      'val': '60',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '13.29',
      'val': '7318',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '16.25',
      'val': '13043',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '2.63',
      'val': '26673',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '33.18',
      'val': '217',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '12.41',
      'val': '6835',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '81.44',
      'val': '65354',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '1.93',
      'val': '19619',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '10.09',
      'val': '66',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '30.4',
      'val': '16739',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '2.3',
      'val': '1849',
    },
  ],
  'fb_d_20251019.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '38.47',
      'val': '659857',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '18.33',
      'val': '125',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '25.86',
      'val': '10080',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '6.31',
      'val': '2057',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '25.28',
      'val': '433654',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '25.95',
      'val': '177',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '13.78',
      'val': '5374',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '5.43',
      'val': '1768',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '24.36',
      'val': '417925',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '31.38',
      'val': '214',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '31.5',
      'val': '12284',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '20.37',
      'val': '6635',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '9.71',
      'val': '166635',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '11.88',
      'val': '81',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '16.89',
      'val': '6587',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '7.83',
      'val': '2550',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '2.18',
      'val': '37411',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '12.46',
      'val': '85',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '11.97',
      'val': '4669',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '60.06',
      'val': '19563',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '62.06',
      'val': '1226K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '27.36',
      'val': '151',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '40.99',
      'val': '24206',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '27.86',
      'val': '550540',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '39.31',
      'val': '217',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '10.07',
      'val': '5943',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '6.23',
      'val': '123149',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '11.41',
      'val': '63',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '9.09',
      'val': '5364',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '2.3',
      'val': '45491',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '7.61',
      'val': '42',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '11.15',
      'val': '6582',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '91.41',
      'val': '50710',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '1.55',
      'val': '30722',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '14.31',
      'val': '79',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '28.7',
      'val': '16943',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '8.59',
      'val': '4764',
    },
  ],
  'fb_d_20251112.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '72.76',
      'val': '2949K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '44.28',
      'val': '440',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '16.78',
      'val': '7629',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '9.73',
      'val': '394440',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '13.98',
      'val': '139',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '32.15',
      'val': '14610',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '8.86',
      'val': '359278',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '33.6',
      'val': '334',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '21.97',
      'val': '9983',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '8.03',
      'val': '325568',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '4.02',
      'val': '40',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '9.02',
      'val': '4099',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '32.48',
      'val': '12495',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '0.62',
      'val': '25317',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '4.12',
      'val': '41',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '20.08',
      'val': '9124',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '67.52',
      'val': '25978',
    },
  ],
  'fb_d_20260315.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '66.3',
      'val': '4406K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '38.19',
      'val': '215',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '18.52',
      'val': '3024',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '18.24',
      'val': '2421',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '23.32',
      'val': '1549K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '36.23',
      'val': '204',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '37.87',
      'val': '6184',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '3.46',
      'val': '460',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '5.38',
      'val': '357832',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '14.39',
      'val': '',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '19.81',
      'val': '3234',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '24.35',
      'val': '3234',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '2.14',
      'val': '139555',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '7.02',
      'val': '38',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '17.41',
      'val': '1219',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '66.3',
      'val': '4406K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '38.19',
      'val': '215',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '18.52',
      'val': '3024',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '18.24',
      'val': '2421',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '23.32',
      'val': '1549K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '36.23',
      'val': '204',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '37.87',
      'val': '6184',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '3.46',
      'val': '460',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '5.38',
      'val': '357832',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '14.39',
      'val': '',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '19.81',
      'val': '3234',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '24.35',
      'val': '3234',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '2.79',
      'val': '185715',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '5.15',
      'val': '29',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '11.44',
      'val': '1868',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '46.02',
      'val': '6112',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '2.21',
      'val': '146549',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '6.04',
      'val': '34',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '12.36',
      'val': '2019',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '7.93',
      'val': '1053',
    },
  ],
  'gm_d_20250908.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '39.65',
      'val': '722365',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '34.39',
      'val': '250',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '39.89',
      'val': '15849',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '10.4',
      'val': '3275',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '37.32',
      'val': '680164',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '23.11',
      'val': '168',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '26.28',
      'val': '10438',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '12.11',
      'val': '220786',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '20.08',
      'val': '146',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '11.47',
      'val': '4556',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '8.63',
      'val': '157312',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '11.97',
      'val': '87',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '10.68',
      'val': '4243',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '1.2',
      'val': '378',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '2.29',
      'val': '41820',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '10.45',
      'val': '76',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '11.68',
      'val': '4638',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '88.4',
      'val': '27836',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '43.33',
      'val': '282861',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '30.13',
      'val': '135',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '18.66',
      'val': '10546',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '34.71',
      'val': '226616',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '37.28',
      'val': '167',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '32.37',
      'val': '18292',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '16.48',
      'val': '107563',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '12.95',
      'val': '58',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '12.79',
      'val': '7231',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '12.45',
      'val': '7488',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '3.34',
      'val': '21830',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '7.14',
      'val': '32',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '26.47',
      'val': '14962',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '76.51',
      'val': '46033',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '2.14',
      'val': '13971',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '12.5',
      'val': '56',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '9.71',
      'val': '5486',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '11.05',
      'val': '6646',
    },
  ],
  'gm_d_20251019.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '57.27',
      'val': '1320K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '28.04',
      'val': '173',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '40.46',
      'val': '23439',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '27.24',
      'val': '628265',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '37.76',
      'val': '233',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '10.27',
      'val': '5953',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '11.29',
      'val': '260390',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '14.75',
      'val': '91',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '9.65',
      'val': '5593',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '2.76',
      'val': '63703',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '8.43',
      'val': '52',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '12.21',
      'val': '7077',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '88.35',
      'val': '46762',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '1.44',
      'val': '33245',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '11.02',
      'val': '68',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '27.41',
      'val': '15886',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '11.65',
      'val': '6166',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '40.58',
      'val': '1101K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '19.51',
      'val': '161',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '26.59',
      'val': '10094',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '5.32',
      'val': '1753',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '26.5',
      'val': '719109',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '24.97',
      'val': '206',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '10.61',
      'val': '4028',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '1.65',
      'val': '545',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '20.09',
      'val': '545190',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '32.97',
      'val': '272',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '30.58',
      'val': '11606',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '9.79',
      'val': '3224',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '11.24',
      'val': '305124',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '10.91',
      'val': '90',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '19.06',
      'val': '7235',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '6.46',
      'val': '2126',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '1.59',
      'val': '43035',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '11.64',
      'val': '96',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '13.16',
      'val': '4995',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '76.78',
      'val': '25283',
    },
  ],
  'gm_d_20260111.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '41.83',
      'val': '1789K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '17.84',
      'val': '327',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '19.89',
      'val': '8080',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '25.85',
      'val': '1105K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '26.02',
      'val': '',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '20.76',
      'val': '8429',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '23.4',
      'val': '1001K',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '30.99',
      'val': '568',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '16.22',
      'val': '6588',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '6.94',
      'val': '296770',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '17.08',
      'val': '313',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '23.55',
      'val': '9563',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '18.13',
      'val': '14538',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '1.98',
      'val': '84589',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '8.07',
      'val': '148',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '19.58',
      'val': '7951',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '81.87',
      'val': '65646',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '37.21',
      'val': '1251K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '51.71',
      'val': '1615',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '17.94',
      'val': '3798',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '36.83',
      'val': '1238K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '32.15',
      'val': '1004',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '16.5',
      'val': '3490',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '13',
      'val': '437213',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '6.44',
      'val': '201',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '38.56',
      'val': '8158',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '11.41',
      'val': '383538',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '6.53',
      'val': '204',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '8.56',
      'val': '1810',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '67.95',
      'val': '17866',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '1.55',
      'val': '52093',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '3.17',
      'val': '99',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '18.44',
      'val': '3901',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '32.05',
      'val': '8428',
    },
  ],
  'gm_d_20260201.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '44.32',
      'val': '2258K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '11.73',
      'val': '358',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '22.13',
      'val': '6638',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '35.67',
      'val': '1817K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '33.94',
      'val': '1037',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '11.23',
      'val': '3370',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '1.45',
      'val': '674',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '15.66',
      'val': '797732',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '44.32',
      'val': '1354',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '15.63',
      'val': '4690',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '2.47',
      'val': '1146',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '2.94',
      'val': '149702',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '5.17',
      'val': '158',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '15.25',
      'val': '4575',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '74.01',
      'val': '34317',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '1.41',
      'val': '71746',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '4.84',
      'val': '148',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '35.76',
      'val': '10730',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '22.07',
      'val': '10232',
    },
  ],
  'gm_d_20260202.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '32.23',
      'val': '2141K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '23.03',
      'val': '727',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '20.49',
      'val': '9835',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '31.62',
      'val': '2102K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '19.04',
      'val': '601',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '18.72',
      'val': '8987',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '15.79',
      'val': '1049K',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '25.94',
      'val': '819',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '20.91',
      'val': '10040',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '10.66',
      'val': '709035',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '17.64',
      'val': '557',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '19.83',
      'val': '9521',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '1.41',
      'val': '829',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '9.7',
      'val': '645216',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '14.35',
      'val': '453',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '20.05',
      'val': '9627',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '98.59',
      'val': '58029',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '46.17',
      'val': '2168K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '11.81',
      'val': '360',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '26.45',
      'val': '',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '1.89',
      'val': '829',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '34.99',
      'val': '1643K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '33.92',
      'val': '1035',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '11.94',
      'val': '3370',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '1.53',
      'val': '674',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '14.98',
      'val': '703564',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '43.95',
      'val': '1341',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '22.69',
      'val': '6407',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '6.36',
      'val': '2804',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '2.47',
      'val': '116063',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '5.57',
      'val': '170',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '15.99',
      'val': '4515',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '76.66',
      'val': '33783',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '1.39',
      'val': '65128',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '4.75',
      'val': '145',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '22.93',
      'val': '6474',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '13.56',
      'val': '5976',
    },
  ],
  'ib_d_20250928.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '58.52',
      'val': '1257K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '23.39',
      'val': '161',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '11.84',
      'val': '5715',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '15.09',
      'val': '324209',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '24.13',
      'val': '166',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '33.6',
      'val': '16225',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '14.97',
      'val': '321649',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '33.87',
      'val': '233',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '12.61',
      'val': '6090',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '1.32',
      'val': '565',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '9.22',
      'val': '198256',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '12.21',
      'val': '84',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '28.79',
      'val': '13903',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '3.5',
      'val': '1500',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '2.2',
      'val': '47292',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '6.4',
      'val': '44',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '13.16',
      'val': '6354',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '95.18',
      'val': '40810',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '36.26',
      'val': '1633K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '34.58',
      'val': '323',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '19.7',
      'val': '10619',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '100',
      'val': '52754',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '29.6',
      'val': '1333K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '18.74',
      'val': '175',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '9.97',
      'val': '5372',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '21',
      'val': '945996',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '25.59',
      'val': '239',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '33.72',
      'val': '18171',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '7.92',
      'val': '356691',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '4.28',
      'val': '40',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '10.28',
      'val': '5539',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '5.22',
      'val': '235368',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '16.81',
      'val': '157',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '26.33',
      'val': '14190',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '0',
      'val': '0',
    },
  ],
  'ib_d_20251004.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '36.62',
      'val': '1888K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '33.29',
      'val': '331',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '19.75',
      'val': '11348',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '98.95',
      'val': '54891',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '34.34',
      'val': '1771K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '17.81',
      'val': '177',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '34.83',
      'val': '20016',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '17.85',
      'val': '920921',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '26.36',
      'val': '262',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '10.69',
      'val': '6141',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '6.38',
      'val': '329208',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '4.73',
      'val': '47',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '10.32',
      'val': '5932',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '1.05',
      'val': '580',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '4.81',
      'val': '247966',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '17.81',
      'val': '177',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '24.41',
      'val': '14027',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '69.04',
      'val': '1967K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '22.87',
      'val': '174',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '40.92',
      'val': '22265',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '12.08',
      'val': '344201',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '32.59',
      'val': '248',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '11.46',
      'val': '6235',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '9.14',
      'val': '260655',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '23.65',
      'val': '180',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '10.06',
      'val': '5472',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '7.05',
      'val': '200885',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '12.48',
      'val': '95',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '25.66',
      'val': '13957',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '3.06',
      'val': '1506',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '2.69',
      'val': '76688',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '8.41',
      'val': '64',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '11.9',
      'val': '6472',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '96.94',
      'val': '47639',
    },
  ],
  'ib_d_20251020.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '40.73',
      'val': '2731K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '33.03',
      'val': '297',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '19.57',
      'val': '8606',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '100',
      'val': '47371',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '33.35',
      'val': '2236K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '18.69',
      'val': '168',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '33.95',
      'val': '14924',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '14.8',
      'val': '992240',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '25.25',
      'val': '227',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '10.48',
      'val': '4609',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '6.75',
      'val': '452757',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '5.12',
      'val': '46',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '9.95',
      'val': '4375',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '4.37',
      'val': '293187',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '17.91',
      'val': '161',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '26.05',
      'val': '11451',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '64.36',
      'val': '2201K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '23.33',
      'val': '174',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '44.77',
      'val': '23149',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '18.8',
      'val': '643418',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '33.11',
      'val': '247',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '22.43',
      'val': '11595',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '9.65',
      'val': '330225',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '23.59',
      'val': '',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '10.47',
      'val': '5414',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '4.45',
      'val': '152207',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '12.2',
      'val': '91',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '9.81',
      'val': '5070',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '2.24',
      'val': '1036',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '2.74',
      'val': '93762',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '7.77',
      'val': '58',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '12.52',
      'val': '6472',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '97.76',
      'val': '45270',
    },
  ],
  'ib_d_20251021.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '65.31',
      'val': '2257K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '22.27',
      'val': '175',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '44.11',
      'val': '22535',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '18.37',
      'val': '634830',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '32.82',
      'val': '258',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '22.7',
      'val': '11595',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '9.06',
      'val': '313072',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '23.79',
      'val': '187',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '10.6',
      'val': '5414',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '4.46',
      'val': '154219',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '12.47',
      'val': '98',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '9.92',
      'val': '5070',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '2.27',
      'val': '1036',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '2.8',
      'val': '96946',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '8.65',
      'val': '68',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '12.67',
      'val': '6472',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '97.73',
      'val': '44631',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '38.27',
      'val': '2527K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '18.51',
      'val': '188',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '33.37',
      'val': '18349',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '36.98',
      'val': '2442K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '33.37',
      'val': '339',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '20.54',
      'val': '11297',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '100',
      'val': '52970',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '14.24',
      'val': '940463',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '25.98',
      'val': '264',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '10.77',
      'val': '5923',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '6.34',
      'val': '418848',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '4.72',
      'val': '48',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '10.25',
      'val': '5636',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '4.17',
      'val': '275725',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '17.42',
      'val': '177',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '25.07',
      'val': '13784',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '0',
      'val': '0',
    },
  ],
  'ib_d_20251024.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '36.96',
      'val': '2320K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '18.15',
      'val': '186',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '33.77',
      'val': '18357',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '36.82',
      'val': '2312K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '34.15',
      'val': '350',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '20.6',
      'val': '11196',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '100',
      'val': '52546',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '16.39',
      'val': '1029K',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '27.9',
      'val': '286',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '10.66',
      'val': '5792',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '6.54',
      'val': '410992',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '5.07',
      'val': '52',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '10.09',
      'val': '5482',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '3.29',
      'val': '206838',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '14.73',
      'val': '151',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '24.88',
      'val': '13520',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '63.86',
      'val': '2246K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '21.77',
      'val': '169',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '44.58',
      'val': '22930',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0.8',
      'val': '367',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '18.93',
      'val': '665991',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '32.99',
      'val': '256',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '22.45',
      'val': '11543',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '9.58',
      'val': '336844',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '24.1',
      'val': '187',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '10.53',
      'val': '5414',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '4.79',
      'val': '168462',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '12.63',
      'val': '98',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '9.86',
      'val': '5070',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '2.25',
      'val': '1036',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '2.84',
      'val': '99797',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '8.51',
      'val': '66',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '12.58',
      'val': '6468',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '96.95',
      'val': '44580',
    },
  ],
  'ib_d_20251225.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '45.4',
      'val': '3613K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '31.16',
      'val': '215',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '24.28',
      'val': '2787',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '42.58',
      'val': '3387K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '16.67',
      'val': '115',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '32.66',
      'val': '3748',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '8.39',
      'val': '667739',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '40.14',
      'val': '277',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '18.6',
      'val': '2134',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '3.34',
      'val': '265713',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '6.52',
      'val': '45',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '14.23',
      'val': '1633',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '37.67',
      'val': '4193',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '0.29',
      'val': '23055',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '5.51',
      'val': '38',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '10.23',
      'val': '1174',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '62.33',
      'val': '6937',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '63.47',
      'val': '5051K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '26.79',
      'val': '127',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '32.66',
      'val': '8132',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '24.83',
      'val': '1975K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '24.47',
      'val': '',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '22.95',
      'val': '5716',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '5.87',
      'val': '466998',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '17.51',
      'val': '83',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '28.4',
      'val': '7072',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '4.72',
      'val': '375449',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '23.21',
      'val': '110',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '6.69',
      'val': '1667',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '1.11',
      'val': '88099',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '8.02',
      'val': '38',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '9.3',
      'val': '2315',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '100',
      'val': '24902',
    },
  ],
  'ib_d_20260112_1.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '45.89',
      'val': '4867K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '51.81',
      'val': '1200',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '19.71',
      'val': '2331',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '35.18',
      'val': '3731K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '12.22',
      'val': '283',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '33.67',
      'val': '3983',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '9.77',
      'val': '1036K',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '8.81',
      'val': '204',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '22.18',
      'val': '2624',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '5.31',
      'val': '4506',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '6.34',
      'val': '672332',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '8.98',
      'val': '208',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '5.2',
      'val': '615',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '1.74',
      'val': '1476',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '2.82',
      'val': '298963',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '18.18',
      'val': '421',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '19.24',
      'val': '2276',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '92.95',
      'val': '78823',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '45.56',
      'val': '4854K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '51.78',
      'val': '1247',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '18.41',
      'val': '2378',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '36.2',
      'val': '3857K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '12.38',
      'val': '298',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '40.56',
      'val': '5240',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '9.3',
      'val': '990859',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '8.97',
      'val': '216',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '20.77',
      'val': '2683',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '5.06',
      'val': '4378',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '6.2',
      'val': '660740',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '8.89',
      'val': '214',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '4.61',
      'val': '595',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '1.43',
      'val': '1242',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '2.74',
      'val': '292007',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '17.98',
      'val': '433',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '15.65',
      'val': '2022',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '93.51',
      'val': '80970',
    },
  ],
  'ib_d_20260114.png': [
    {
      'part': 'p1_r0_col1',
      'pct': '40.83',
      'val': '4349K',
    },
    {
      'part': 'p1_r0_col2',
      'pct': '34.28',
      'val': '1232',
    },
    {
      'part': 'p1_r0_col3',
      'pct': '17.47',
      'val': '2279',
    },
    {
      'part': 'p1_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r1_col1',
      'pct': '36.11',
      'val': '3847K',
    },
    {
      'part': 'p1_r1_col2',
      'pct': '8.18',
      'val': '294',
    },
    {
      'part': 'p1_r1_col3',
      'pct': '25.64',
      'val': '3343',
    },
    {
      'part': 'p1_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r2_col1',
      'pct': '16.69',
      'val': '1778K',
    },
    {
      'part': 'p1_r2_col2',
      'pct': '46.19',
      'val': '1660',
    },
    {
      'part': 'p1_r2_col3',
      'pct': '32.7',
      'val': '4264',
    },
    {
      'part': 'p1_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p1_r3_col1',
      'pct': '5.3',
      'val': '565102',
    },
    {
      'part': 'p1_r3_col2',
      'pct': '5.79',
      'val': '208',
    },
    {
      'part': 'p1_r3_col3',
      'pct': '4.28',
      'val': '558',
    },
    {
      'part': 'p1_r3_col4',
      'pct': '2.31',
      'val': '1936',
    },
    {
      'part': 'p1_r4_col1',
      'pct': '1.07',
      'val': '114181',
    },
    {
      'part': 'p1_r4_col2',
      'pct': '5.56',
      'val': '200',
    },
    {
      'part': 'p1_r4_col3',
      'pct': '19.91',
      'val': '2596',
    },
    {
      'part': 'p1_r4_col4',
      'pct': '97.69',
      'val': '81791',
    },
    {
      'part': 'p2_r0_col1',
      'pct': '63.99',
      'val': '6818K',
    },
    {
      'part': 'p2_r0_col2',
      'pct': '44.15',
      'val': '993',
    },
    {
      'part': 'p2_r0_col3',
      'pct': '15.46',
      'val': '6909',
    },
    {
      'part': 'p2_r0_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r1_col1',
      'pct': '18.68',
      'val': '1990K',
    },
    {
      'part': 'p2_r1_col2',
      'pct': '12.89',
      'val': '290',
    },
    {
      'part': 'p2_r1_col3',
      'pct': '17.81',
      'val': '7960',
    },
    {
      'part': 'p2_r1_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r2_col1',
      'pct': '9.27',
      'val': '987544',
    },
    {
      'part': 'p2_r2_col2',
      'pct': '21.97',
      'val': '494',
    },
    {
      'part': 'p2_r2_col3',
      'pct': '17.66',
      'val': '7890',
    },
    {
      'part': 'p2_r2_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r3_col1',
      'pct': '7.31',
      'val': '779202',
    },
    {
      'part': 'p2_r3_col2',
      'pct': '16.54',
      'val': '372',
    },
    {
      'part': 'p2_r3_col3',
      'pct': '33.91',
      'val': '15151',
    },
    {
      'part': 'p2_r3_col4',
      'pct': '0',
      'val': '0',
    },
    {
      'part': 'p2_r4_col1',
      'pct': '0.75',
      'val': '79987',
    },
    {
      'part': 'p2_r4_col2',
      'pct': '4.45',
      'val': '100',
    },
    {
      'part': 'p2_r4_col3',
      'pct': '15.16',
      'val': '6774',
    },
    {
      'part': 'p2_r4_col4',
      'pct': '100',
      'val': '72522',
    },
  ],
}

META = {
  'fb_d_060518.png': {
    'prefix': 'fb',
    'n_cells': 20,
    'dolls': [
      'Klukai',
      'Leva',
      'Lind',
      'Peritya',
      'Tololo',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'fb_d_20250930.png': {
    'prefix': 'fb',
    'n_cells': 40,
    'dolls': [
      'Colphne',
      'Nikketa',
      'QiongJiu',
      'Sharkry',
      'Springfield',
      'Suomi',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'fb_d_20251019.png': {
    'prefix': 'fb',
    'n_cells': 40,
    'dolls': [
      'Centaureissi',
      'Colphne',
      'Nikketa',
      'QiongJiu',
      'Qiuhua',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
      'Zhaohui',
    ],
    'rare_dolls': [
      'Zhaohui',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p2_r0_col1',
    ],
    'structural_outlier': None,
    'importance_score': 3,
  },
  'fb_d_20251112.png': {
    'prefix': 'fb',
    'n_cells': 20,
    'dolls': [
      'Colphne',
      'Klukai',
      'Lind',
      'Mechty',
      'Peritya',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
    ],
    'structural_outlier': 'known_issues.txt §10 — p2 header stats fail at blob extraction',
    'importance_score': 5,
  },
  'fb_d_20260315.png': {
    'prefix': 'fb',
    'n_cells': 36,
    'dolls': [
      'Daiyan',
      'Faye',
      'Vepley',
      'Voymastina',
      'Yoohee',
    ],
    'rare_dolls': [
      'Daiyan',
      'Faye',
      'Vepley',
      'Voymastina',
      'Yoohee',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 15,
  },
  'gm_d_20250908.png': {
    'prefix': 'gm',
    'n_cells': 40,
    'dolls': [
      'Andoris',
      'Centaureissi',
      'Colphne',
      'Florence',
      'Makiatto',
      'Sabrina',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [
      'Florence',
      'Makiatto',
      'Sabrina',
    ],
    'hard_cells': [],
    'km_suffix_cells': [],
    'structural_outlier': None,
    'importance_score': 9,
  },
  'gm_d_20251019.png': {
    'prefix': 'gm',
    'n_cells': 40,
    'dolls': [
      'Centaureissi',
      'Colphne',
      'Nikketa',
      'QiongJiu',
      'Qiuhua',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
      'Zhaohui',
    ],
    'rare_dolls': [
      'Zhaohui',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p2_r0_col1',
    ],
    'structural_outlier': None,
    'importance_score': 3,
  },
  'gm_d_20260111.png': {
    'prefix': 'gm',
    'n_cells': 40,
    'dolls': [
      'Colphne',
      'Klukai',
      'Lind',
      'Mechty',
      'Nikketa',
      'Papasha',
      'Peritya',
      'QiongJiu',
      'Springfield',
      'Tololo',
    ],
    'rare_dolls': [
      'Papasha',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p1_r2_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 3,
  },
  'gm_d_20260201.png': {
    'prefix': 'gm',
    'n_cells': 20,
    'dolls': [
      'Andoris',
      'Jiangyu',
      'Leva',
      'Springfield',
      'Tololo',
    ],
    'rare_dolls': [
      'Jiangyu',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 3,
  },
  'gm_d_20260202.png': {
    'prefix': 'gm',
    'n_cells': 40,
    'dolls': [
      'Andoris',
      'Jiangyu',
      'Leva',
      'QiongJiu',
      'Qiuhua',
      'Sakura',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [
      'Jiangyu',
      'Sakura',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p1_r2_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 6,
  },
  'ib_d_20250928.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Klukai',
      'Nikketa',
      'Peritya',
      'QiongJiu',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'ib_d_20251004.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Klukai',
      'Nikketa',
      'Peritya',
      'QiongJiu',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p2_r0_col1',
    ],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'ib_d_20251020.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Klukai',
      'Nikketa',
      'Peritya',
      'QiongJiu',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p2_r0_col1',
    ],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'ib_d_20251021.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Klukai',
      'Nikketa',
      'Peritya',
      'QiongJiu',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'ib_d_20251024.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Klukai',
      'Nikketa',
      'Peritya',
      'QiongJiu',
      'Sharkry',
      'Springfield',
      'Tololo',
      'Vector',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p1_r2_col1',
      'p2_r0_col1',
    ],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'ib_d_20251225.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Colphne',
      'Klukai',
      'Lind',
      'Mechty',
      'Peritya',
      'QiongJiu',
      'Springfield',
      'Tololo',
    ],
    'rare_dolls': [],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 0,
  },
  'ib_d_20260112_1.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Klukai',
      'Lind',
      'Makiatto',
      'Mechty',
      'Suomi',
    ],
    'rare_dolls': [
      'Makiatto',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p1_r2_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 3,
  },
  'ib_d_20260114.png': {
    'prefix': 'ib',
    'n_cells': 40,
    'dolls': [
      'Klukai',
      'Lewis',
      'Lind',
      'Mechty',
      'Nikketa',
      'Peritya',
      'QiongJiu',
      'Springfield',
      'Suomi',
      'Tololo',
    ],
    'rare_dolls': [
      'Lewis',
    ],
    'hard_cells': [],
    'km_suffix_cells': [
      'p1_r0_col1',
      'p1_r1_col1',
      'p1_r2_col1',
      'p2_r0_col1',
      'p2_r1_col1',
    ],
    'structural_outlier': None,
    'importance_score': 3,
  },
}
