# -*- coding: utf-8 -*-
"""
debugs/build_tess_gt_cache.py -- one-time (or refresh) pure-Tesseract
ground-truth cache for gfl2.stat_ocr._collect_cells(tess_only=True).

WHY: gfl2/stat_ocr.py, gfl2/stat_ocr_padded.py, and gfl2/stat_ocr_fft.py's
own --build/--verify CLIs all call _collect_cells(image_paths, tess_only=True)
against the same static single/*.png corpus, re-running Tesseract OCR on
every cell every time (~1200s / 20 min for 87 images, 3216 cells) even
though neither the images nor Tesseract's behavior on them changes between
runs.  We are not testing Tesseract here -- its output on a static image set
is exactly reproducible -- so there is no reason to keep re-paying that cost
on every --build/--verify iteration.

This script runs the Tesseract pass ONCE and caches every cell's (pct, val)
label to tests/inputs/daily/tess_gt_cache.py, keyed by the same source
string _collect_cells already uses ("<image_stem>_p<panel>_r<row>_<col>").
All three engines' _collect_cells(gt_cache=...) parameter (and their
--build/--verify CLIs, which auto-load this file by default) consult this
cache first and only fall back to live Tesseract for cells/images not
covered by it (e.g. a newly added image) -- so partial or stale coverage
degrades gracefully rather than silently misleading.

Usage:
    python debugs/build_tess_gt_cache.py                      # single/*.png
    python debugs/build_tess_gt_cache.py --images "single/gm_d_*.png"

Regenerate whenever single/*.png's contents change (new/removed/re-cropped
images) -- this is a plain cache, not a checked invariant; nothing detects
staleness automatically.  Use --no-gt-cache on any engine's CLI to bypass it
and confirm live Tesseract still agrees, if in doubt.
"""
from __future__ import annotations
import json, sys, time, glob as _glob
from datetime import datetime
from pathlib import Path

_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(_ROOT))

from gfl2.stat_ocr import _collect_cells

OUT_PY = _ROOT / "tests" / "inputs" / "daily" / "tess_gt_cache.py"


def main(argv=None):
    import argparse
    run_start = datetime.now().isoformat(timespec="seconds")
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--images", default="single/*.png",
                     help="Glob of images to cache  [default: single/*.png]")
    args = ap.parse_args(argv)

    image_paths = sorted(Path(p) for p in _glob.glob(args.images)
                         if "debug" not in Path(p).stem)
    if not image_paths:
        sys.exit(f"No images matched: {args.images}")

    print(f"Generated: {run_start}  (run start)")
    print(f"Collecting pure-Tesseract labels for {len(image_paths)} image(s) "
          f"-- this is the slow, one-time part ...")
    t0 = time.perf_counter()
    results = _collect_cells(image_paths, tess_only=True)
    elapsed = time.perf_counter() - t0
    print(f"  {len(results)} cells collected  ({elapsed:.1f}s)")

    cache = {item["source"]: {"pct": item["pct"], "val": item["val"]}
             for item in results}

    OUT_PY.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '# -*- coding: utf-8 -*-',
        '"""',
        'tess_gt_cache.py -- auto-generated by debugs/build_tess_gt_cache.py',
        '',
        f'Generated: {run_start}  (run start)',
        '',
        'Pure-Tesseract (pct, val) label per stat cell, across every image',
        f'matched by --images at generation time ({len(image_paths)} images,',
        f'{len(cache)} cells).  Consumed by gfl2.stat_ocr._collect_cells\'s',
        'gt_cache parameter (and its gfl2/stat_ocr_padded.py / '
        'gfl2/stat_ocr_fft.py',
        'mirrors) to skip re-running Tesseract against this static image set',
        'on every --build/--verify call -- we are not testing Tesseract, its',
        'output here is exactly reproducible.  A cache miss (image/cell not',
        'present below) falls back to live Tesseract automatically, so',
        'partial coverage is safe, just slower for the uncovered cells.',
        '',
        "Regenerate after changing single/*.png's contents:",
        '    python debugs/build_tess_gt_cache.py',
        '"""',
        '',
        f'IMAGES = {[p.name for p in image_paths]!r}',
        '',
        'DATA = ' + json.dumps(cache, indent=2),
        '',
    ]
    OUT_PY.write_text('\n'.join(lines), encoding='utf-8')
    print(f"\nWrote cache: {OUT_PY}  ({len(cache)} cells, {len(image_paths)} images)")


if __name__ == "__main__":
    main()
